// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package maskingevents

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const maskingEventCount = `-- name: MaskingEventCount :one
SELECT count(*) AS events
FROM masking_events AS e
WHERE e.account_id = $1 AND e.masked_at >= $2
`

type MaskingEventCountParams struct {
	AccountID string
	Since     pgtype.Timestamptz
}

// The masking events recorded since a time, for the system endpoint's corpus block (docs/UI.md
// section 8.1).
func (q *Queries) MaskingEventCount(ctx context.Context, arg MaskingEventCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, maskingEventCount, arg.AccountID, arg.Since)
	var events int64
	err := row.Scan(&events)
	return events, err
}
