// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing.sql

package maskingevents

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const maskingEventPage = `-- name: MaskingEventPage :many
SELECT
    e.id,
    e.message_id,
    e.field,
    e.rule_id,
    e.tier,
    e.masked_at
FROM masking_events AS e
WHERE
    e.account_id = $1
    AND ($2::timestamptz IS NULL OR e.masked_at >= $2::timestamptz)
    AND (
        $3::timestamptz IS NULL
        OR (e.masked_at, e.id) < ($3::timestamptz, $4::bigint)
    )
ORDER BY e.masked_at DESC, e.id DESC
LIMIT $5
`

type MaskingEventPageParams struct {
	AccountID      string
	Since          pgtype.Timestamptz
	BeforeMaskedAt pgtype.Timestamptz
	BeforeID       int64
	PageSize       int32
}

type MaskingEventPageRow struct {
	ID        int64
	MessageID string
	Field     string
	RuleID    string
	Tier      int32
	MaskedAt  pgtype.Timestamptz
}

// One page of the account's masking events, the latest first, masked at or after a time when one is
// given, and after the position a cursor names or from the start when it names none. An event records
// the rule and tier that fired and never the text it matched (ADR-0003).
func (q *Queries) MaskingEventPage(ctx context.Context, arg MaskingEventPageParams) ([]MaskingEventPageRow, error) {
	rows, err := q.db.Query(ctx, maskingEventPage,
		arg.AccountID,
		arg.Since,
		arg.BeforeMaskedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaskingEventPageRow
	for rows.Next() {
		var i MaskingEventPageRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Field,
			&i.RuleID,
			&i.Tier,
			&i.MaskedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
