// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package maskingevents

import (
	"context"
)

type Querier interface {
	// The masking events recorded since a time, for the system endpoint's corpus block (docs/UI.md
	// section 8.1).
	MaskingEventCount(ctx context.Context, arg MaskingEventCountParams) (int64, error)
	// One page of the account's masking events, the latest first, masked at or after a time when one is
	// given, and after the position a cursor names or from the start when it names none. An event records
	// the rule and tier that fired and never the text it matched (ADR-0003).
	MaskingEventPage(ctx context.Context, arg MaskingEventPageParams) ([]MaskingEventPageRow, error)
}

var _ Querier = (*Queries)(nil)
