// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package maskingevents

import (
	"context"
)

type Querier interface {
	// The masking events recorded since a time, for the system endpoint's corpus block (docs/UI.md
	// section 8.1).
	MaskingEventCount(ctx context.Context, arg MaskingEventCountParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
