// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package maskingrecord

import (
	"context"
)

type Querier interface {
	// Records one mask applied to a message's subject as the subject was masked, naming the rule and tier
	// that detected what was masked and never the text (ADR-0003), and the scanner version and
	// configuration revision the masking ran under (ADR-0120).
	RecordMaskingEvent(ctx context.Context, arg RecordMaskingEventParams) error
	// Records a batch of masks applied to the subjects of the account's messages, one row for each
	// message, rule and tier named in the same position of the three lists, naming never the text
	// (ADR-0003), all under the scanner version and configuration revision given, in one statement, as a
	// backfill run's start masks the stored subjects again in batches (ADR-0120).
	RecordMaskingEvents(ctx context.Context, arg RecordMaskingEventsParams) error
}

var _ Querier = (*Queries)(nil)
