// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package record

import (
	"context"
)

type Querier interface {
	// Records one mask applied to a message's subject as the subject was masked, naming the rule and tier
	// that detected what was masked and never the text (ADR-0003), and the scanner version and
	// configuration revision the masking ran under (ADR-0096).
	RecordMaskingEvent(ctx context.Context, arg RecordMaskingEventParams) error
}

var _ Querier = (*Queries)(nil)
