// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record.sql

package record

import (
	"context"
)

const recordMaskingEvent = `-- name: RecordMaskingEvent :exec
INSERT INTO masking_events (account_id, message_id, field, rule_id, tier)
VALUES ($1, $2, 'subject', $3, $4)
`

type RecordMaskingEventParams struct {
	AccountID string
	MessageID string
	RuleID    string
	Tier      int32
}

// Records one mask applied to a message's subject as it entered the index, naming the rule and tier
// that detected what was masked and never the text (ADR-0003).
func (q *Queries) RecordMaskingEvent(ctx context.Context, arg RecordMaskingEventParams) error {
	_, err := q.db.Exec(ctx, recordMaskingEvent,
		arg.AccountID,
		arg.MessageID,
		arg.RuleID,
		arg.Tier,
	)
	return err
}
