// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record.sql

package maskingrecord

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordMaskingEvent = `-- name: RecordMaskingEvent :exec
INSERT INTO masking_events (account_id, message_id, field, rule_id, tier, scanner_version, scanner_revision)
VALUES ($1, $2, 'subject', $3, $4, $5, $6)
`

type RecordMaskingEventParams struct {
	AccountID       string
	MessageID       string
	RuleID          string
	Tier            int32
	ScannerVersion  pgtype.Int4
	ScannerRevision pgtype.Text
}

// Records one mask applied to a message's subject as the subject was masked, naming the rule and tier
// that detected what was masked and never the text (ADR-0003), and the scanner version and
// configuration revision the masking ran under (ADR-0120).
func (q *Queries) RecordMaskingEvent(ctx context.Context, arg RecordMaskingEventParams) error {
	_, err := q.db.Exec(ctx, recordMaskingEvent,
		arg.AccountID,
		arg.MessageID,
		arg.RuleID,
		arg.Tier,
		arg.ScannerVersion,
		arg.ScannerRevision,
	)
	return err
}

const recordMaskingEvents = `-- name: RecordMaskingEvents :exec
INSERT INTO masking_events (account_id, message_id, field, rule_id, tier, scanner_version, scanner_revision)
SELECT
    $1,
    e.message_id,
    'subject' AS field,
    e.rule_id,
    e.tier,
    $2::int AS scanner_version,
    $3::text AS scanner_revision
FROM (
    SELECT
        unnest($4::text[]) AS message_id,
        unnest($5::text[]) AS rule_id,
        unnest($6::int[]) AS tier
) AS e
`

type RecordMaskingEventsParams struct {
	AccountID       string
	ScannerVersion  int32
	ScannerRevision string
	MessageIds      []string
	RuleIds         []string
	Tiers           []int32
}

// Records a batch of masks applied to the subjects of the account's messages, one row for each
// message, rule and tier named in the same position of the three lists, naming never the text
// (ADR-0003), all under the scanner version and configuration revision given, in one statement, as a
// backfill run's start masks the stored subjects again in batches (ADR-0120).
func (q *Queries) RecordMaskingEvents(ctx context.Context, arg RecordMaskingEventsParams) error {
	_, err := q.db.Exec(ctx, recordMaskingEvents,
		arg.AccountID,
		arg.ScannerVersion,
		arg.ScannerRevision,
		arg.MessageIds,
		arg.RuleIds,
		arg.Tiers,
	)
	return err
}
