// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manage.sql

package manage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRule = `-- name: AddRule :exec
INSERT INTO policy_rules (account_id, rule_id, class, domain_suffix, source, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AddRuleParams struct {
	AccountID    pgtype.Text
	RuleID       string
	Class        string
	DomainSuffix []string
	Source       string
	CreatedBy    string
}

// Adds one of the account's own rules, which the operator's policy management writes, or a confirmed
// candidate's (ADR-0004, ADR-0084). The table's key refuses an identifier the account already holds
// (ADR-0110).
func (q *Queries) AddRule(ctx context.Context, arg AddRuleParams) error {
	_, err := q.db.Exec(ctx, addRule,
		arg.AccountID,
		arg.RuleID,
		arg.Class,
		arg.DomainSuffix,
		arg.Source,
		arg.CreatedBy,
	)
	return err
}

const composedRules = `-- name: ComposedRules :many
SELECT
    r.rule_id,
    r.account_id,
    r.class,
    r.domain_suffix,
    r.source,
    r.created_at,
    r.created_by
FROM policy_rules AS r
WHERE r.account_id = $1::text OR r.account_id IS NULL
ORDER BY r.rule_id, r.account_id NULLS FIRST
`

type ComposedRulesRow struct {
	RuleID       string
	AccountID    pgtype.Text
	Class        string
	DomainSuffix []string
	Source       string
	CreatedAt    pgtype.Timestamptz
	CreatedBy    string
}

// The rules the account's policy screen lists, the base rules every account inherits and the
// account's own, with what the screen shows of each (docs/UI.md section 8.7). A base rule carries a
// null account. The screen sorts, searches and pages them, and counts what each matches, in the UI's
// server, which reads the account's senders beside them.
func (q *Queries) ComposedRules(ctx context.Context, accountID string) ([]ComposedRulesRow, error) {
	rows, err := q.db.Query(ctx, composedRules, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComposedRulesRow
	for rows.Next() {
		var i ComposedRulesRow
		if err := rows.Scan(
			&i.RuleID,
			&i.AccountID,
			&i.Class,
			&i.DomainSuffix,
			&i.Source,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const editRule = `-- name: EditRule :execrows
UPDATE policy_rules
SET domain_suffix = $1
WHERE account_id = $2 AND rule_id = $3 AND domain_suffix = $4::text[]
`

type EditRuleParams struct {
	DomainSuffix   []string
	AccountID      pgtype.Text
	RuleID         string
	SuffixesBefore []string
}

// Sets one of the account's own rules' domain suffixes, only while they are still the suffixes the
// edit was made against, so an edit over a change the operator never saw changes nothing.
func (q *Queries) EditRule(ctx context.Context, arg EditRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, editRule,
		arg.DomainSuffix,
		arg.AccountID,
		arg.RuleID,
		arg.SuffixesBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const liftRule = `-- name: LiftRule :execrows
DELETE FROM policy_rules
WHERE account_id = $1 AND rule_id = $2 AND domain_suffix = $3::text[]
`

type LiftRuleParams struct {
	AccountID      pgtype.Text
	RuleID         string
	SuffixesBefore []string
}

// Removes one of the account's own rules, only while its suffixes are still the ones the lift was
// confirmed against.
func (q *Queries) LiftRule(ctx context.Context, arg LiftRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, liftRule, arg.AccountID, arg.RuleID, arg.SuffixesBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
