// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package manage

import (
	"context"
)

type Querier interface {
	// Adds one of the account's own rules, which the operator's policy management writes, or a confirmed
	// candidate's (ADR-0004, ADR-0084). The table's key refuses an identifier the account already holds
	// (ADR-0110).
	AddRule(ctx context.Context, arg AddRuleParams) error
	// The rules the account's policy screen lists, the base rules every account inherits and the
	// account's own, with what the screen shows of each (docs/UI.md section 8.7). A base rule carries a
	// null account. The screen sorts, searches and pages them, and counts what each matches, in the UI's
	// server, which reads the account's senders beside them.
	ComposedRules(ctx context.Context, accountID string) ([]ComposedRulesRow, error)
	// Sets one of the account's own rules' domain suffixes, only while they are still the suffixes the
	// edit was made against, so an edit over a change the operator never saw changes nothing.
	EditRule(ctx context.Context, arg EditRuleParams) (int64, error)
	// Removes one of the account's own rules, only while its suffixes are still the ones the lift was
	// confirmed against.
	LiftRule(ctx context.Context, arg LiftRuleParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
