// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package scangatedecisions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gateDecisionCount = `-- name: GateDecisionCount :one
SELECT count(*) AS decisions
FROM scan_gate_decisions AS d
WHERE d.account_id = $1 AND d.decision = $2 AND d.decided_at >= $3
`

type GateDecisionCountParams struct {
	AccountID string
	Decision  string
	Since     pgtype.Timestamptz
}

// The scan gate's decisions of one kind since a time, the skips on the system endpoint's corpus block
// (docs/UI.md section 8.1).
func (q *Queries) GateDecisionCount(ctx context.Context, arg GateDecisionCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, gateDecisionCount, arg.AccountID, arg.Decision, arg.Since)
	var decisions int64
	err := row.Scan(&decisions)
	return decisions, err
}
