// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scangatedecisions

import (
	"context"
)

type Querier interface {
	// The scan gate's decisions of one kind since a time, the skips on the system endpoint's corpus block
	// (docs/UI.md section 8.1).
	GateDecisionCount(ctx context.Context, arg GateDecisionCountParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
