// Code generated by hand to prove generated files are linted. DO NOT EDIT.

//go:build banproof

package gmail

// This file breaks the provider import list on purpose. Its header marks it as generated, so its
// finding is reported only while the configuration lints generated files.
import (
	_ "github.com/ppat/mediated-mailbox-mcp/db/tx" // want depguard "list 'provider'"
)
