// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cursor.sql

package cursor

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceCursor = `-- name: AdvanceCursor :execrows
UPDATE account_state
SET sync_cursor = $1, sync_cursor_at = now()
WHERE account_id = $2
`

type AdvanceCursorParams struct {
	SyncCursor pgtype.Text
	AccountID  string
}

// Stores the account's change cursor and records the instant it was written, in the transaction that
// made the changes it follows durable, so the cursor never runs ahead of the index (ADR-0018). An
// account with no state row counts no row.
func (q *Queries) AdvanceCursor(ctx context.Context, arg AdvanceCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceCursor, arg.SyncCursor, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const syncCursor = `-- name: SyncCursor :one
SELECT
    s.sync_cursor,
    s.sync_cursor_at
FROM account_state AS s
WHERE s.account_id = $1
`

type SyncCursorRow struct {
	SyncCursor   pgtype.Text
	SyncCursorAt pgtype.Timestamptz
}

// The account's change cursor and when delta sync last wrote it, both null before its first tick
// (ADR-0016). A gap's recovery starts its window from the write time (ADR-0105).
func (q *Queries) SyncCursor(ctx context.Context, accountID string) (SyncCursorRow, error) {
	row := q.db.QueryRow(ctx, syncCursor, accountID)
	var i SyncCursorRow
	err := row.Scan(&i.SyncCursor, &i.SyncCursorAt)
	return i, err
}
