// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package accounts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accounts = `-- name: Accounts :many
SELECT
    account_id,
    provider AS account_provider,
    oauth_client
FROM accounts
ORDER BY account_id
`

type AccountsRow struct {
	AccountID       string
	AccountProvider string
	OauthClient     pgtype.Text
}

// Every account's identifier, provider and the OAuth client it connects through, NULL for a provider
// without one, the one statement left without an account predicate. The roles that list accounts
// read every row of the table (ADR-0091, ADR-0106).
func (q *Queries) Accounts(ctx context.Context) ([]AccountsRow, error) {
	rows, err := q.db.Query(ctx, accounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountsRow
	for rows.Next() {
		var i AccountsRow
		if err := rows.Scan(&i.AccountID, &i.AccountProvider, &i.OauthClient); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
