// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accounts

import (
	"context"
)

type Querier interface {
	// Every account's identifier and provider, the one statement left without an account predicate. The
	// roles that list accounts read every row of the table (ADR-0091).
	Accounts(ctx context.Context) ([]AccountsRow, error)
}

var _ Querier = (*Queries)(nil)
