// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scan

import (
	"context"
)

type Querier interface {
	// How many of the account's messages wait for their content scan, the scan backlog depth a scanning
	// workload emits as a metric (ADR-0093).
	Backlog(ctx context.Context, accountID string) (int64, error)
	// The account's messages the scan gate skipped, in the order of their identifiers, each with what the
	// gate reads of it and of its sender, the sender's volume and prior hits, read as PendingPage reads
	// them, so a backfill run decides each skip again under the gate it holds (ADR-0098). A message with no
	// sender statistics reads a volume and hits of zero.
	GateSkips(ctx context.Context, accountID string) ([]GateSkipsRow, error)
	// The delisting transition for one domain the policy in force no longer restricts. Its messages stored
	// restricted or skipped as restricted return to a normal sender class with no rule naming it, and to
	// pending scan (ADR-0037, ADR-0016).
	MarkDelisted(ctx context.Context, arg MarkDelistedParams) (int64, error)
	// Restricts the stored class of one domain the policy in force now restricts under a rule. Its
	// messages stored as normal take the restricted class and the rule that sets it, and their scan state
	// is left as it is (ADR-0113, ADR-0016).
	MarkListed(ctx context.Context, arg MarkListedParams) (int64, error)
	// The sender domains of the account whose messages the index stores as normal, each once, which every
	// scanning workload compares with the policy in force, so a rule added since restricts the stored
	// classes (ADR-0113).
	NormalDomains(ctx context.Context, accountID string) ([]string, error)
	// The account's messages waiting for their content scan after the message identified by after, in
	// the order of their identifiers, each with what the scan gate reads of it and of its sender, the
	// sender's volume and prior hits (ADR-0093, ADR-0017). A message with no sender statistics reads a
	// volume and hits of zero. The page is keyed on the identifier, so a message left waiting is read
	// once per pass.
	PendingPage(ctx context.Context, arg PendingPageParams) ([]PendingPageRow, error)
	// Records that the scan gate skipped a waiting message, as skipped_restricted or skipped_gate
	// (ADR-0093). A message no longer waiting is left as it is and counts no row.
	RecordSkip(ctx context.Context, arg RecordSkipParams) (int64, error)
	// Records a waiting message's scan verdict, its content flags, the identifiers of the content rules
	// that fired, the scanner version and the configuration's revision (ADR-0009). The rules are the
	// content rules alone. A message no longer waiting is left as it is and counts no row.
	RecordVerdict(ctx context.Context, arg RecordVerdictParams) (int64, error)
	// Returns to pending scan each of the given messages the scan gate skipped, the skips the gate no
	// longer decides as the same skip (ADR-0098). A message no longer skipped by the gate is left as it is
	// and counts no row.
	RequeueGateSkips(ctx context.Context, arg RequeueGateSkipsParams) (int64, error)
	// Returns each of the account's messages the gate skipped whose subject is now masked to pending scan,
	// since the gate decided without that signal (ADR-0096, ADR-0093).
	RequeueSignalledSkips(ctx context.Context, accountID string) (int64, error)
	// Returns each of the account's scanned messages whose verdict was made under another scanner version
	// or configuration revision than the one given to pending scan, its verdict cleared, so the Redaction
	// Gate denies its body as pending its content scan (ADR-0096). A backfill run makes it at its start,
	// before the first pass. It returns each message's sender domain, whose prior hits the caller counts
	// again.
	RequeueStaleVerdicts(ctx context.Context, arg RequeueStaleVerdictsParams) ([]string, error)
	// The sender domains of the account whose messages the index stores as restricted or holds skipped as
	// restricted, each once, which the delisting transition compares with the policy in force (ADR-0037).
	// A rule added after a message was stored can leave its stored class normal while the gate skips it as
	// restricted, until the comparison for an added rule restricts the stored class (ADR-0113), so the
	// skip state is read as well.
	RestrictedDomains(ctx context.Context, accountID string) ([]string, error)
}

var _ Querier = (*Queries)(nil)
