// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan.sql

package scan

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backlog = `-- name: Backlog :one
SELECT count(*) AS pending
FROM messages AS m
WHERE m.account_id = $1 AND m.scan_state = 'pending'
`

// How many of the account's messages wait for their content scan, the scan backlog depth a scanning
// workload emits as a metric (ADR-0093).
func (q *Queries) Backlog(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, backlog, accountID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const markDelisted = `-- name: MarkDelisted :execrows
UPDATE messages
SET sender_class = 'normal', scan_state = 'pending'
WHERE
    account_id = $1
    AND from_domain = $2
    AND (sender_class = 'restricted' OR scan_state = 'skipped_restricted')
`

type MarkDelistedParams struct {
	AccountID string
	Domain    string
}

// The delisting transition for one domain the policy in force no longer restricts. Its messages stored
// restricted or skipped as restricted return to a normal sender class and to pending scan (ADR-0037).
func (q *Queries) MarkDelisted(ctx context.Context, arg MarkDelistedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDelisted, arg.AccountID, arg.Domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pendingPage = `-- name: PendingPage :many
SELECT
    m.message_id,
    m.from_email,
    m.from_domain,
    m.subject_masked,
    m.sent_at,
    (m.list_id IS NOT NULL)::boolean AS has_list_id,
    coalesce(m.size_bytes, 0)::bigint AS size_bytes,
    coalesce(s.message_count, 0)::bigint AS sender_volume,
    coalesce(s.scan_hit_count, 0)::bigint AS sender_hits
FROM messages AS m
LEFT JOIN senders AS s ON m.account_id = s.account_id AND m.from_domain = s.domain
WHERE m.account_id = $1 AND m.scan_state = 'pending' AND m.message_id > $2
ORDER BY m.message_id
LIMIT $3
`

type PendingPageParams struct {
	AccountID string
	After     string
	PageSize  int32
}

type PendingPageRow struct {
	MessageID     string
	FromEmail     string
	FromDomain    string
	SubjectMasked bool
	SentAt        pgtype.Timestamptz
	HasListID     bool
	SizeBytes     int64
	SenderVolume  int64
	SenderHits    int64
}

// The account's messages waiting for their content scan after the message identified by after, in
// the order of their identifiers, each with what the scan gate reads of it and of its sender, the
// sender's volume and prior hits (ADR-0093, ADR-0017). A message with no sender statistics reads a
// volume and hits of zero. The page is keyed on the identifier, so a message left waiting is read
// once per pass.
func (q *Queries) PendingPage(ctx context.Context, arg PendingPageParams) ([]PendingPageRow, error) {
	rows, err := q.db.Query(ctx, pendingPage, arg.AccountID, arg.After, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingPageRow
	for rows.Next() {
		var i PendingPageRow
		if err := rows.Scan(
			&i.MessageID,
			&i.FromEmail,
			&i.FromDomain,
			&i.SubjectMasked,
			&i.SentAt,
			&i.HasListID,
			&i.SizeBytes,
			&i.SenderVolume,
			&i.SenderHits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSkip = `-- name: RecordSkip :execrows
UPDATE messages
SET scan_state = $1
WHERE account_id = $2 AND message_id = $3 AND scan_state = 'pending'
`

type RecordSkipParams struct {
	ScanState string
	AccountID string
	MessageID string
}

// Records that the scan gate skipped a waiting message, as skipped_restricted or skipped_gate
// (ADR-0093). A message no longer waiting is left as it is and counts no row.
func (q *Queries) RecordSkip(ctx context.Context, arg RecordSkipParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordSkip, arg.ScanState, arg.AccountID, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordVerdict = `-- name: RecordVerdict :execrows
UPDATE messages
SET
    scan_state = 'scanned',
    content_flags = $1,
    rule_ids = $2,
    scanned_at = now(),
    scanner_version = $3,
    scanner_revision = $4
WHERE account_id = $5 AND message_id = $6 AND scan_state = 'pending'
`

type RecordVerdictParams struct {
	ContentFlags    []string
	RuleIds         []string
	ScannerVersion  pgtype.Int4
	ScannerRevision pgtype.Text
	AccountID       string
	MessageID       string
}

// Records a waiting message's scan verdict, its content flags, the identifiers of the content rules
// that fired, the scanner version and the configuration's revision (ADR-0009). The rules are the
// content rules alone. A message no longer waiting is left as it is and counts no row.
func (q *Queries) RecordVerdict(ctx context.Context, arg RecordVerdictParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordVerdict,
		arg.ContentFlags,
		arg.RuleIds,
		arg.ScannerVersion,
		arg.ScannerRevision,
		arg.AccountID,
		arg.MessageID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restrictedDomains = `-- name: RestrictedDomains :many
SELECT DISTINCT m.from_domain
FROM messages AS m
WHERE m.account_id = $1 AND (m.sender_class = 'restricted' OR m.scan_state = 'skipped_restricted')
ORDER BY m.from_domain
`

// The sender domains of the account whose messages the index stores as restricted or holds skipped as
// restricted, each once, which the delisting transition compares with the policy in force (ADR-0037).
// A rule added after a message was stored leaves its stored class normal while the gate skips it as
// restricted, so the skip state is read as well.
func (q *Queries) RestrictedDomains(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, restrictedDomains, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var from_domain string
		if err := rows.Scan(&from_domain); err != nil {
			return nil, err
		}
		items = append(items, from_domain)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
