// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan.sql

package scan

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backlog = `-- name: Backlog :one
SELECT count(*) AS pending
FROM messages AS m
WHERE m.account_id = $1 AND m.scan_state = 'pending'
`

// How many of the account's messages wait for their content scan, the scan backlog depth a scanning
// workload emits as a metric (ADR-0093).
func (q *Queries) Backlog(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, backlog, accountID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const gateSkips = `-- name: GateSkips :many
SELECT
    m.message_id,
    m.from_email,
    m.from_domain,
    m.subject_masked,
    m.sent_at,
    (m.list_id IS NOT NULL)::boolean AS has_list_id,
    coalesce(m.size_bytes, 0)::bigint AS size_bytes,
    coalesce(s.message_count, 0)::bigint AS sender_volume,
    coalesce(s.scan_hit_count, 0)::bigint AS sender_hits
FROM messages AS m
LEFT JOIN senders AS s ON m.account_id = s.account_id AND m.from_domain = s.domain
WHERE m.account_id = $1 AND m.scan_state = 'skipped_gate'
ORDER BY m.message_id
`

type GateSkipsRow struct {
	MessageID     string
	FromEmail     string
	FromDomain    string
	SubjectMasked bool
	SentAt        pgtype.Timestamptz
	HasListID     bool
	SizeBytes     int64
	SenderVolume  int64
	SenderHits    int64
}

// The account's messages the scan gate skipped, in the order of their identifiers, each with what the
// gate reads of it and of its sender, the sender's volume and prior hits, read as PendingPage reads
// them, so a backfill run decides each skip again under the gate it holds (ADR-0098). A message with no
// sender statistics reads a volume and hits of zero.
func (q *Queries) GateSkips(ctx context.Context, accountID string) ([]GateSkipsRow, error) {
	rows, err := q.db.Query(ctx, gateSkips, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GateSkipsRow
	for rows.Next() {
		var i GateSkipsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.FromEmail,
			&i.FromDomain,
			&i.SubjectMasked,
			&i.SentAt,
			&i.HasListID,
			&i.SizeBytes,
			&i.SenderVolume,
			&i.SenderHits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDelisted = `-- name: MarkDelisted :execrows
UPDATE messages
SET sender_class = 'normal', class_rule_id = NULL, scan_state = 'pending'
WHERE
    account_id = $1
    AND from_domain = $2
    AND (sender_class = 'restricted' OR scan_state = 'skipped_restricted')
`

type MarkDelistedParams struct {
	AccountID string
	Domain    string
}

// The delisting transition for one domain the policy in force no longer restricts. Its messages stored
// restricted or skipped as restricted return to a normal sender class with no rule naming it, and to
// pending scan (ADR-0037, ADR-0016).
func (q *Queries) MarkDelisted(ctx context.Context, arg MarkDelistedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDelisted, arg.AccountID, arg.Domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markListed = `-- name: MarkListed :execrows
UPDATE messages
SET sender_class = 'restricted', class_rule_id = $1
WHERE account_id = $2 AND from_domain = $3 AND sender_class = 'normal'
`

type MarkListedParams struct {
	ClassRuleID pgtype.Text
	AccountID   string
	Domain      string
}

// Restricts the stored class of one domain the policy in force now restricts under a rule. Its
// messages stored as normal take the restricted class and the rule that sets it, and their scan state
// is left as it is (ADR-0113, ADR-0016).
func (q *Queries) MarkListed(ctx context.Context, arg MarkListedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markListed, arg.ClassRuleID, arg.AccountID, arg.Domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const normalDomains = `-- name: NormalDomains :many
SELECT DISTINCT m.from_domain
FROM messages AS m
WHERE m.account_id = $1 AND m.sender_class = 'normal'
ORDER BY m.from_domain
`

// The sender domains of the account whose messages the index stores as normal, each once, which every
// scanning workload compares with the policy in force, so a rule added since restricts the stored
// classes (ADR-0113).
func (q *Queries) NormalDomains(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, normalDomains, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var from_domain string
		if err := rows.Scan(&from_domain); err != nil {
			return nil, err
		}
		items = append(items, from_domain)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingPage = `-- name: PendingPage :many
SELECT
    m.message_id,
    m.from_email,
    m.from_domain,
    m.subject_masked,
    m.sent_at,
    (m.list_id IS NOT NULL)::boolean AS has_list_id,
    coalesce(m.size_bytes, 0)::bigint AS size_bytes,
    coalesce(s.message_count, 0)::bigint AS sender_volume,
    coalesce(s.scan_hit_count, 0)::bigint AS sender_hits
FROM messages AS m
LEFT JOIN senders AS s ON m.account_id = s.account_id AND m.from_domain = s.domain
WHERE m.account_id = $1 AND m.scan_state = 'pending' AND m.message_id > $2
ORDER BY m.message_id
LIMIT $3
`

type PendingPageParams struct {
	AccountID string
	After     string
	PageSize  int32
}

type PendingPageRow struct {
	MessageID     string
	FromEmail     string
	FromDomain    string
	SubjectMasked bool
	SentAt        pgtype.Timestamptz
	HasListID     bool
	SizeBytes     int64
	SenderVolume  int64
	SenderHits    int64
}

// The account's messages waiting for their content scan after the message identified by after, in
// the order of their identifiers, each with what the scan gate reads of it and of its sender, the
// sender's volume and prior hits (ADR-0093, ADR-0017). A message with no sender statistics reads a
// volume and hits of zero. The page is keyed on the identifier, so a message left waiting is read
// once per pass.
func (q *Queries) PendingPage(ctx context.Context, arg PendingPageParams) ([]PendingPageRow, error) {
	rows, err := q.db.Query(ctx, pendingPage, arg.AccountID, arg.After, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingPageRow
	for rows.Next() {
		var i PendingPageRow
		if err := rows.Scan(
			&i.MessageID,
			&i.FromEmail,
			&i.FromDomain,
			&i.SubjectMasked,
			&i.SentAt,
			&i.HasListID,
			&i.SizeBytes,
			&i.SenderVolume,
			&i.SenderHits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSkip = `-- name: RecordSkip :execrows
UPDATE messages
SET scan_state = $1
WHERE account_id = $2 AND message_id = $3 AND scan_state = 'pending'
`

type RecordSkipParams struct {
	ScanState string
	AccountID string
	MessageID string
}

// Records that the scan gate skipped a waiting message, as skipped_restricted or skipped_gate
// (ADR-0093). A message no longer waiting is left as it is and counts no row.
func (q *Queries) RecordSkip(ctx context.Context, arg RecordSkipParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordSkip, arg.ScanState, arg.AccountID, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordVerdict = `-- name: RecordVerdict :execrows
UPDATE messages
SET
    scan_state = 'scanned',
    content_flags = $1,
    rule_ids = $2,
    scanned_at = now(),
    scanner_version = $3,
    scanner_revision = $4
WHERE account_id = $5 AND message_id = $6 AND scan_state = 'pending'
`

type RecordVerdictParams struct {
	ContentFlags    []string
	RuleIds         []string
	ScannerVersion  pgtype.Int4
	ScannerRevision pgtype.Text
	AccountID       string
	MessageID       string
}

// Records a waiting message's scan verdict, its content flags, the identifiers of the content rules
// that fired, the scanner version and the configuration's revision (ADR-0009). The rules are the
// content rules alone. A message no longer waiting is left as it is and counts no row.
func (q *Queries) RecordVerdict(ctx context.Context, arg RecordVerdictParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordVerdict,
		arg.ContentFlags,
		arg.RuleIds,
		arg.ScannerVersion,
		arg.ScannerRevision,
		arg.AccountID,
		arg.MessageID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueGateSkips = `-- name: RequeueGateSkips :execrows
UPDATE messages
SET scan_state = 'pending'
WHERE account_id = $1 AND scan_state = 'skipped_gate' AND message_id = any($2::text[])
`

type RequeueGateSkipsParams struct {
	AccountID  string
	MessageIds []string
}

// Returns to pending scan each of the given messages the scan gate skipped, the skips the gate no
// longer decides as the same skip (ADR-0098). A message no longer skipped by the gate is left as it is
// and counts no row.
func (q *Queries) RequeueGateSkips(ctx context.Context, arg RequeueGateSkipsParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueGateSkips, arg.AccountID, arg.MessageIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueSignalledSkips = `-- name: RequeueSignalledSkips :execrows
UPDATE messages
SET scan_state = 'pending'
WHERE account_id = $1 AND scan_state = 'skipped_gate' AND subject_masked
`

// Returns each of the account's messages the gate skipped whose subject is now masked to pending scan,
// since the gate decided without that signal (ADR-0096, ADR-0093).
func (q *Queries) RequeueSignalledSkips(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, requeueSignalledSkips, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueStaleVerdicts = `-- name: RequeueStaleVerdicts :many
UPDATE messages
SET
    scan_state = 'pending',
    content_flags = '{}',
    rule_ids = '{}',
    scanned_at = NULL,
    scanner_version = NULL,
    scanner_revision = NULL
WHERE
    account_id = $1
    AND scan_state = 'scanned'
    AND (
        scanner_version IS DISTINCT FROM $2::int
        OR scanner_revision IS DISTINCT FROM $3::text
    )
RETURNING from_domain
`

type RequeueStaleVerdictsParams struct {
	AccountID       string
	ScannerVersion  int32
	ScannerRevision string
}

// Returns each of the account's scanned messages whose verdict was made under another scanner version
// or configuration revision than the one given to pending scan, its verdict cleared, so the Redaction
// Gate denies its body as pending its content scan (ADR-0096). A backfill run makes it at its start,
// before the first pass. It returns each message's sender domain, whose prior hits the caller counts
// again.
func (q *Queries) RequeueStaleVerdicts(ctx context.Context, arg RequeueStaleVerdictsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, requeueStaleVerdicts, arg.AccountID, arg.ScannerVersion, arg.ScannerRevision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var from_domain string
		if err := rows.Scan(&from_domain); err != nil {
			return nil, err
		}
		items = append(items, from_domain)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restrictedDomains = `-- name: RestrictedDomains :many
SELECT DISTINCT m.from_domain
FROM messages AS m
WHERE m.account_id = $1 AND (m.sender_class = 'restricted' OR m.scan_state = 'skipped_restricted')
ORDER BY m.from_domain
`

// The sender domains of the account whose messages the index stores as restricted or holds skipped as
// restricted, each once, which the delisting transition compares with the policy in force (ADR-0037).
// A rule added after a message was stored leaves its stored class normal while the gate skips it as
// restricted, so the skip state is read as well.
func (q *Queries) RestrictedDomains(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, restrictedDomains, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var from_domain string
		if err := rows.Scan(&from_domain); err != nil {
			return nil, err
		}
		items = append(items, from_domain)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
