// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package listing

import (
	"context"
)

type Querier interface {
	ListSenders(ctx context.Context, arg ListSendersParams) ([]ListSendersRow, error)
}

var _ Querier = (*Queries)(nil)
