// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: removed.sql

package listing

import (
	"context"
)

const countSenders = `-- name: CountSenders :one
SELECT count(*) FROM fixture_senders WHERE account_id = $1
`

func (q *Queries) CountSenders(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSenders, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
