// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: senders.sql

package listing

import (
	"context"
)

const listSenders = `-- name: ListSenders :many
SELECT
    domain,
    message_count
FROM fixture_senders
WHERE account_id = $1
ORDER BY message_count DESC, domain ASC
LIMIT $2
`

type ListSendersParams struct {
	AccountID string
	PageSize  int32
}

type ListSendersRow struct {
	Domain       string
	MessageCount int64
}

func (q *Queries) ListSenders(ctx context.Context, arg ListSendersParams) ([]ListSendersRow, error) {
	rows, err := q.db.Query(ctx, listSenders, arg.AccountID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSendersRow
	for rows.Next() {
		var i ListSendersRow
		if err := rows.Scan(&i.Domain, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
