// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reuse

import (
	"context"
)

type Querier interface {
	// Selects every column of fixture_senders in table order, so sqlc reuses the table's struct as the
	// result type and declares it in models.go. The declares-no-types assertion must report it.
	GetSender(ctx context.Context, arg GetSenderParams) (FixtureSender, error)
}

var _ Querier = (*Queries)(nil)
