// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sender.sql

package reuse

import (
	"context"
)

const getSender = `-- name: GetSender :one
SELECT account_id, domain, message_count
FROM fixture_senders
WHERE account_id = $1 AND domain = $2
`

type GetSenderParams struct {
	AccountID string
	Domain    string
}

// Selects every column of fixture_senders in table order, so sqlc reuses the table's struct as the
// result type and declares it in models.go. The declares-no-types assertion must report it.
func (q *Queries) GetSender(ctx context.Context, arg GetSenderParams) (FixtureSender, error) {
	row := q.db.QueryRow(ctx, getSender, arg.AccountID, arg.Domain)
	var i FixtureSender
	err := row.Scan(&i.AccountID, &i.Domain, &i.MessageCount)
	return i, err
}
