// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package record

import (
	"context"
)

type Querier interface {
	// Records the scan gate's decision on one message with its reason, scans as well as skips
	// (ADR-0093). A message decided again, as one the delisting transition returned to pending scan is,
	// has its decision replaced.
	RecordDecision(ctx context.Context, arg RecordDecisionParams) error
}

var _ Querier = (*Queries)(nil)
