// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record.sql

package gaterecord

import (
	"context"
)

const recordDecision = `-- name: RecordDecision :exec
INSERT INTO scan_gate_decisions AS d (account_id, message_id, decision, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, message_id) DO UPDATE
    SET decision = excluded.decision, reason = excluded.reason, decided_at = now()
`

type RecordDecisionParams struct {
	AccountID string
	MessageID string
	Decision  string
	Reason    string
}

// Records the scan gate's decision on one message with its reason, scans as well as skips
// (ADR-0093). A message decided again, as one the delisting transition returned to pending scan is,
// has its decision replaced.
func (q *Queries) RecordDecision(ctx context.Context, arg RecordDecisionParams) error {
	_, err := q.db.Exec(ctx, recordDecision,
		arg.AccountID,
		arg.MessageID,
		arg.Decision,
		arg.Reason,
	)
	return err
}
