// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listing.sql

package senders

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const senderPage = `-- name: SenderPage :many
SELECT
    s.domain,
    s.local_part_sample,
    s.display_names,
    s.message_count,
    s.first_seen,
    s.last_seen,
    s.has_list_id_ratio,
    s.label_distribution
FROM senders AS s
WHERE
    s.account_id = $1
    AND (
        $2::boolean
        OR s.message_count < $3::bigint
        OR (s.message_count = $3::bigint AND s.domain > $4::citext)
    )
ORDER BY s.message_count DESC, s.domain ASC
LIMIT $5
`

type SenderPageParams struct {
	AccountID   string
	FirstPage   bool
	AfterCount  int64
	AfterDomain string
	PageSize    int32
}

type SenderPageRow struct {
	Domain            string
	LocalPartSample   []string
	DisplayNames      []string
	MessageCount      int64
	FirstSeen         pgtype.Timestamptz
	LastSeen          pgtype.Timestamptz
	HasListIDRatio    pgtype.Float4
	LabelDistribution []byte
}

// One page of the account's sender statistics, the sender with the most messages first, after the
// position a cursor names or from the start when it names none (ADR-0017). The stored sender class and
// the prior scan hits are not read. The class is decided again against the policy in force (ADR-0002),
// and the hits are a signal derived from bodies that no read serves.
func (q *Queries) SenderPage(ctx context.Context, arg SenderPageParams) ([]SenderPageRow, error) {
	rows, err := q.db.Query(ctx, senderPage,
		arg.AccountID,
		arg.FirstPage,
		arg.AfterCount,
		arg.AfterDomain,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SenderPageRow
	for rows.Next() {
		var i SenderPageRow
		if err := rows.Scan(
			&i.Domain,
			&i.LocalPartSample,
			&i.DisplayNames,
			&i.MessageCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.HasListIDRatio,
			&i.LabelDistribution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
