// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package senders

import (
	"context"
)

type Querier interface {
	// Rebuilds the statistics of the account's sender at domain from the messages the index holds for
	// it, its volume, first and last message, List-Id share, label distribution, the first twenty of its
	// local parts and display names in sorted order, and its class (ADR-0016, ADR-0017). A sender is
	// restricted when any of its messages was classified restricted. The statistics are read from the
	// stored messages rather than added to, so a page ingested twice leaves them as one ingestion does.
	RebuildSender(ctx context.Context, arg RebuildSenderParams) error
}

var _ Querier = (*Queries)(nil)
