// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package senders

import (
	"context"
)

type Querier interface {
	// One page of the account's sender statistics, the sender with the most messages first, after the
	// position a cursor names or from the start when it names none (ADR-0017). The stored sender class and
	// the prior scan hits are not read. The class is decided again against the policy in force (ADR-0002),
	// and the hits are a signal derived from bodies that no read serves.
	SenderPage(ctx context.Context, arg SenderPageParams) ([]SenderPageRow, error)
}

var _ Querier = (*Queries)(nil)
