// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package accountstate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountProgress = `-- name: AccountProgress :one
SELECT
    s.backfill_pass1_complete,
    s.backfill_pass2_complete,
    s.sync_cursor_at,
    s.last_auth_at,
    s.last_auth_outcome
FROM account_state AS s
WHERE s.account_id = $1
`

type AccountProgressRow struct {
	BackfillPass1Complete bool
	BackfillPass2Complete bool
	SyncCursorAt          pgtype.Timestamptz
	LastAuthAt            pgtype.Timestamptz
	LastAuthOutcome       pgtype.Text
}

// An account's progress through its workloads and its last provider authentication, which the system
// endpoint's operational block and the jobs backfill card read (docs/UI.md sections 8.3 and 8.8). It
// reads no credential, and the role that runs it holds no grant on one (ADR-0084, ADR-0091).
func (q *Queries) AccountProgress(ctx context.Context, accountID string) (AccountProgressRow, error) {
	row := q.db.QueryRow(ctx, accountProgress, accountID)
	var i AccountProgressRow
	err := row.Scan(
		&i.BackfillPass1Complete,
		&i.BackfillPass2Complete,
		&i.SyncCursorAt,
		&i.LastAuthAt,
		&i.LastAuthOutcome,
	)
	return i, err
}
