// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountstate

import (
	"context"
)

type Querier interface {
	// Writes a sealed credential back only if the stored bytes are still the ones the process last read
	// or wrote, so a value the operator replaced is never put back (ADR-0089). A write that finds other
	// bytes changes no row.
	ReplaceSealed(ctx context.Context, arg ReplaceSealedParams) (int64, error)
	// The account's sealed credential, as its state row holds it. No row means the account has no state
	// row and is not connected, and a null credential means it holds none (ADR-0091).
	Sealed(ctx context.Context, accountID string) ([][]byte, error)
}

var _ Querier = (*Queries)(nil)
