// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sealed.sql

package accountstate

import (
	"context"
)

const replaceSealed = `-- name: ReplaceSealed :execrows
UPDATE account_state
SET credential = $1
WHERE account_id = $2 AND credential = $3
`

type ReplaceSealedParams struct {
	Credential []byte
	AccountID  string
	Known      []byte
}

// Writes a sealed credential back only if the stored bytes are still the ones the process last read
// or wrote, so a value the operator replaced is never put back (ADR-0089). A write that finds other
// bytes changes no row.
func (q *Queries) ReplaceSealed(ctx context.Context, arg ReplaceSealedParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceSealed, arg.Credential, arg.AccountID, arg.Known)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sealed = `-- name: Sealed :many
SELECT credential
FROM account_state
WHERE account_id = $1
`

// The account's sealed credential, as its state row holds it. No row means the account has no state
// row and is not connected, and a null credential means it holds none (ADR-0091).
func (q *Queries) Sealed(ctx context.Context, accountID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, sealed, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var credential []byte
		if err := rows.Scan(&credential); err != nil {
			return nil, err
		}
		items = append(items, credential)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
