// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: target.sql

package accountstate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const loweredTarget = `-- name: LoweredTarget :one
SELECT s.lowered_target_rate
FROM account_state AS s
WHERE s.account_id = $1
`

// The lower target the operator set for the account, a fraction of its provider's declared ceiling, or
// null for none. The rate limiter takes it for the account when a spending process builds it (ADR-0024).
func (q *Queries) LoweredTarget(ctx context.Context, accountID string) (pgtype.Float4, error) {
	row := q.db.QueryRow(ctx, loweredTarget, accountID)
	var lowered_target_rate pgtype.Float4
	err := row.Scan(&lowered_target_rate)
	return lowered_target_rate, err
}
