// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changes.sql

package policychanges

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeFigures = `-- name: ChangeFigures :one
SELECT
    count(*) AS changes,
    count(*) FILTER (
        WHERE c.action IN ('added', 'confirmed') OR (c.action = 'edited' AND c.suffixes_before <@ c.suffixes_after)
    ) AS added,
    count(*) FILTER (
        WHERE c.action = 'lifted' OR (c.action = 'edited' AND NOT c.suffixes_before <@ c.suffixes_after)
    ) AS lifted
FROM policy_changes AS c
WHERE
    (c.account_id = $1::text OR c.account_id IS NULL)
    AND ($2::boolean OR c.account_id IS NOT NULL)
    AND ($3::boolean OR c.account_id IS NULL)
    AND ($4::timestamptz IS NULL OR c.ts >= $4::timestamptz)
    AND ($5::timestamptz IS NULL OR c.ts < $5::timestamptz)
    AND ($6::text[] IS NULL OR c.action = any($6::text[]))
    AND ($7::text[] IS NULL OR c.action != all($7::text[]))
    AND ($8::text[] IS NULL OR c.actor = any($8::text[]))
    AND ($9::text[] IS NULL OR c.actor != all($9::text[]))
    AND ($10::text[] IS NULL OR c.rule_id = any($10::text[]))
    AND ($11::text[] IS NULL OR c.rule_id != all($11::text[]))
    AND ($12::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date = any($12::date[]))
    AND ($13::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date != all($13::date[]))
`

type ChangeFiguresParams struct {
	AccountID  string
	BaseRows   bool
	OwnRows    bool
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	ActionIn   []string
	ActionOut  []string
	ActorIn    []string
	ActorOut   []string
	RuleIn     []string
	RuleOut    []string
	DayIn      []pgtype.Date
	DayOut     []pgtype.Date
}

type ChangeFiguresRow struct {
	Changes int64
	Added   int64
	Lifted  int64
}

// The policy_changes dataset's figures, the changes the account's history holds under the dataset's
// range and filters, those that added restriction and those that lifted it (docs/UI.md section 17.1).
// An edit lifts when it removed a suffix and adds when it removed none. The account's history is its
// own changes and the base policy's (ADR-0102). base_rows and own_rows say which scopes the scope
// filter keeps. A null array is no filter.
func (q *Queries) ChangeFigures(ctx context.Context, arg ChangeFiguresParams) (ChangeFiguresRow, error) {
	row := q.db.QueryRow(ctx, changeFigures,
		arg.AccountID,
		arg.BaseRows,
		arg.OwnRows,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ActionIn,
		arg.ActionOut,
		arg.ActorIn,
		arg.ActorOut,
		arg.RuleIn,
		arg.RuleOut,
		arg.DayIn,
		arg.DayOut,
	)
	var i ChangeFiguresRow
	err := row.Scan(&i.Changes, &i.Added, &i.Lifted)
	return i, err
}

const changeRows = `-- name: ChangeRows :many
SELECT
    c.id,
    c.ts,
    c.account_id,
    c.actor,
    c.action,
    c.rule_id,
    c.suffixes_before,
    c.suffixes_after
FROM policy_changes AS c
WHERE
    (c.account_id = $1::text OR c.account_id IS NULL)
    AND ($2::boolean OR c.account_id IS NOT NULL)
    AND ($3::boolean OR c.account_id IS NULL)
    AND ($4::timestamptz IS NULL OR c.ts >= $4::timestamptz)
    AND ($5::timestamptz IS NULL OR c.ts < $5::timestamptz)
    AND ($6::text[] IS NULL OR c.action = any($6::text[]))
    AND ($7::text[] IS NULL OR c.action != all($7::text[]))
    AND ($8::text[] IS NULL OR c.actor = any($8::text[]))
    AND ($9::text[] IS NULL OR c.actor != all($9::text[]))
    AND ($10::text[] IS NULL OR c.rule_id = any($10::text[]))
    AND ($11::text[] IS NULL OR c.rule_id != all($11::text[]))
    AND ($12::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date = any($12::date[]))
    AND ($13::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date != all($13::date[]))
ORDER BY
    CASE WHEN $14::boolean THEN c.ts END DESC,
    CASE WHEN NOT $14::boolean THEN c.ts END ASC,
    c.id ASC
LIMIT 50 OFFSET $15
`

type ChangeRowsParams struct {
	AccountID  string
	BaseRows   bool
	OwnRows    bool
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	ActionIn   []string
	ActionOut  []string
	ActorIn    []string
	ActorOut   []string
	RuleIn     []string
	RuleOut    []string
	DayIn      []pgtype.Date
	DayOut     []pgtype.Date
	Descending bool
	RowOffset  int32
}

type ChangeRowsRow struct {
	ID             int64
	Ts             pgtype.Timestamptz
	AccountID      pgtype.Text
	Actor          string
	Action         string
	RuleID         string
	SuffixesBefore []string
	SuffixesAfter  []string
}

// One page of the policy_changes dataset, fifty rows, under the same filters, newest first by default,
// the change's identifier ending the sort.
func (q *Queries) ChangeRows(ctx context.Context, arg ChangeRowsParams) ([]ChangeRowsRow, error) {
	rows, err := q.db.Query(ctx, changeRows,
		arg.AccountID,
		arg.BaseRows,
		arg.OwnRows,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ActionIn,
		arg.ActionOut,
		arg.ActorIn,
		arg.ActorOut,
		arg.RuleIn,
		arg.RuleOut,
		arg.DayIn,
		arg.DayOut,
		arg.Descending,
		arg.RowOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeRowsRow
	for rows.Next() {
		var i ChangeRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.AccountID,
			&i.Actor,
			&i.Action,
			&i.RuleID,
			&i.SuffixesBefore,
			&i.SuffixesAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changesByAction = `-- name: ChangesByAction :many
SELECT
    c.action,
    count(*) AS changes
FROM policy_changes AS c
WHERE
    (c.account_id = $1::text OR c.account_id IS NULL)
    AND ($2::boolean OR c.account_id IS NOT NULL)
    AND ($3::boolean OR c.account_id IS NULL)
    AND ($4::timestamptz IS NULL OR c.ts >= $4::timestamptz)
    AND ($5::timestamptz IS NULL OR c.ts < $5::timestamptz)
    AND ($6::text[] IS NULL OR c.action = any($6::text[]))
    AND ($7::text[] IS NULL OR c.action != all($7::text[]))
    AND ($8::text[] IS NULL OR c.actor = any($8::text[]))
    AND ($9::text[] IS NULL OR c.actor != all($9::text[]))
    AND ($10::text[] IS NULL OR c.rule_id = any($10::text[]))
    AND ($11::text[] IS NULL OR c.rule_id != all($11::text[]))
    AND ($12::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date = any($12::date[]))
    AND ($13::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date != all($13::date[]))
GROUP BY c.action
ORDER BY changes DESC, c.action ASC
`

type ChangesByActionParams struct {
	AccountID  string
	BaseRows   bool
	OwnRows    bool
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	ActionIn   []string
	ActionOut  []string
	ActorIn    []string
	ActorOut   []string
	RuleIn     []string
	RuleOut    []string
	DayIn      []pgtype.Date
	DayOut     []pgtype.Date
}

type ChangesByActionRow struct {
	Action  string
	Changes int64
}

// Every group of the policy_changes dataset by action, under the same filters, ordered by count and
// then by the group's key, the order the bars draw (docs/UI.md section 17.1).
func (q *Queries) ChangesByAction(ctx context.Context, arg ChangesByActionParams) ([]ChangesByActionRow, error) {
	rows, err := q.db.Query(ctx, changesByAction,
		arg.AccountID,
		arg.BaseRows,
		arg.OwnRows,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ActionIn,
		arg.ActionOut,
		arg.ActorIn,
		arg.ActorOut,
		arg.RuleIn,
		arg.RuleOut,
		arg.DayIn,
		arg.DayOut,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangesByActionRow
	for rows.Next() {
		var i ChangesByActionRow
		if err := rows.Scan(&i.Action, &i.Changes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changesByActor = `-- name: ChangesByActor :many
SELECT
    c.actor,
    count(*) AS changes
FROM policy_changes AS c
WHERE
    (c.account_id = $1::text OR c.account_id IS NULL)
    AND ($2::boolean OR c.account_id IS NOT NULL)
    AND ($3::boolean OR c.account_id IS NULL)
    AND ($4::timestamptz IS NULL OR c.ts >= $4::timestamptz)
    AND ($5::timestamptz IS NULL OR c.ts < $5::timestamptz)
    AND ($6::text[] IS NULL OR c.action = any($6::text[]))
    AND ($7::text[] IS NULL OR c.action != all($7::text[]))
    AND ($8::text[] IS NULL OR c.actor = any($8::text[]))
    AND ($9::text[] IS NULL OR c.actor != all($9::text[]))
    AND ($10::text[] IS NULL OR c.rule_id = any($10::text[]))
    AND ($11::text[] IS NULL OR c.rule_id != all($11::text[]))
    AND ($12::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date = any($12::date[]))
    AND ($13::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date != all($13::date[]))
GROUP BY c.actor
ORDER BY changes DESC, c.actor ASC
`

type ChangesByActorParams struct {
	AccountID  string
	BaseRows   bool
	OwnRows    bool
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	ActionIn   []string
	ActionOut  []string
	ActorIn    []string
	ActorOut   []string
	RuleIn     []string
	RuleOut    []string
	DayIn      []pgtype.Date
	DayOut     []pgtype.Date
}

type ChangesByActorRow struct {
	Actor   string
	Changes int64
}

// Every group of the policy_changes dataset by the identity that made the change, as ChangesByAction.
func (q *Queries) ChangesByActor(ctx context.Context, arg ChangesByActorParams) ([]ChangesByActorRow, error) {
	rows, err := q.db.Query(ctx, changesByActor,
		arg.AccountID,
		arg.BaseRows,
		arg.OwnRows,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ActionIn,
		arg.ActionOut,
		arg.ActorIn,
		arg.ActorOut,
		arg.RuleIn,
		arg.RuleOut,
		arg.DayIn,
		arg.DayOut,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangesByActorRow
	for rows.Next() {
		var i ChangesByActorRow
		if err := rows.Scan(&i.Actor, &i.Changes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changesByDay = `-- name: ChangesByDay :many
SELECT
    (c.ts AT TIME ZONE 'UTC')::date AS day,
    count(*) AS changes
FROM policy_changes AS c
WHERE
    (c.account_id = $1::text OR c.account_id IS NULL)
    AND ($2::boolean OR c.account_id IS NOT NULL)
    AND ($3::boolean OR c.account_id IS NULL)
    AND ($4::timestamptz IS NULL OR c.ts >= $4::timestamptz)
    AND ($5::timestamptz IS NULL OR c.ts < $5::timestamptz)
    AND ($6::text[] IS NULL OR c.action = any($6::text[]))
    AND ($7::text[] IS NULL OR c.action != all($7::text[]))
    AND ($8::text[] IS NULL OR c.actor = any($8::text[]))
    AND ($9::text[] IS NULL OR c.actor != all($9::text[]))
    AND ($10::text[] IS NULL OR c.rule_id = any($10::text[]))
    AND ($11::text[] IS NULL OR c.rule_id != all($11::text[]))
    AND ($12::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date = any($12::date[]))
    AND ($13::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date != all($13::date[]))
GROUP BY day
ORDER BY changes DESC, day ASC
`

type ChangesByDayParams struct {
	AccountID  string
	BaseRows   bool
	OwnRows    bool
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	ActionIn   []string
	ActionOut  []string
	ActorIn    []string
	ActorOut   []string
	RuleIn     []string
	RuleOut    []string
	DayIn      []pgtype.Date
	DayOut     []pgtype.Date
}

type ChangesByDayRow struct {
	Day     pgtype.Date
	Changes int64
}

// Every group of the policy_changes dataset by the UTC day of the change, as ChangesByAction.
func (q *Queries) ChangesByDay(ctx context.Context, arg ChangesByDayParams) ([]ChangesByDayRow, error) {
	rows, err := q.db.Query(ctx, changesByDay,
		arg.AccountID,
		arg.BaseRows,
		arg.OwnRows,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ActionIn,
		arg.ActionOut,
		arg.ActorIn,
		arg.ActorOut,
		arg.RuleIn,
		arg.RuleOut,
		arg.DayIn,
		arg.DayOut,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangesByDayRow
	for rows.Next() {
		var i ChangesByDayRow
		if err := rows.Scan(&i.Day, &i.Changes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changesByScope = `-- name: ChangesByScope :many
SELECT
    c.account_id,
    count(*) AS changes
FROM policy_changes AS c
WHERE
    (c.account_id = $1::text OR c.account_id IS NULL)
    AND ($2::boolean OR c.account_id IS NOT NULL)
    AND ($3::boolean OR c.account_id IS NULL)
    AND ($4::timestamptz IS NULL OR c.ts >= $4::timestamptz)
    AND ($5::timestamptz IS NULL OR c.ts < $5::timestamptz)
    AND ($6::text[] IS NULL OR c.action = any($6::text[]))
    AND ($7::text[] IS NULL OR c.action != all($7::text[]))
    AND ($8::text[] IS NULL OR c.actor = any($8::text[]))
    AND ($9::text[] IS NULL OR c.actor != all($9::text[]))
    AND ($10::text[] IS NULL OR c.rule_id = any($10::text[]))
    AND ($11::text[] IS NULL OR c.rule_id != all($11::text[]))
    AND ($12::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date = any($12::date[]))
    AND ($13::date[] IS NULL OR (c.ts AT TIME ZONE 'UTC')::date != all($13::date[]))
GROUP BY c.account_id
ORDER BY changes DESC, c.account_id ASC NULLS LAST
`

type ChangesByScopeParams struct {
	AccountID  string
	BaseRows   bool
	OwnRows    bool
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	ActionIn   []string
	ActionOut  []string
	ActorIn    []string
	ActorOut   []string
	RuleIn     []string
	RuleOut    []string
	DayIn      []pgtype.Date
	DayOut     []pgtype.Date
}

type ChangesByScopeRow struct {
	AccountID pgtype.Text
	Changes   int64
}

// Every group of the policy_changes dataset by scope, as ChangesByAction. The base policy's changes
// are the null group, last.
func (q *Queries) ChangesByScope(ctx context.Context, arg ChangesByScopeParams) ([]ChangesByScopeRow, error) {
	rows, err := q.db.Query(ctx, changesByScope,
		arg.AccountID,
		arg.BaseRows,
		arg.OwnRows,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ActionIn,
		arg.ActionOut,
		arg.ActorIn,
		arg.ActorOut,
		arg.RuleIn,
		arg.RuleOut,
		arg.DayIn,
		arg.DayOut,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangesByScopeRow
	for rows.Next() {
		var i ChangesByScopeRow
		if err := rows.Scan(&i.AccountID, &i.Changes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestChange = `-- name: LatestChange :one
SELECT max(c.ts)::timestamptz AS latest
FROM policy_changes AS c
WHERE c.account_id = $1::text OR c.account_id IS NULL
`

// When the account's policy last changed, its own rules or the base policy's, null before its first
// change, for the policy screen's L0 strip.
func (q *Queries) LatestChange(ctx context.Context, accountID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestChange, accountID)
	var latest pgtype.Timestamptz
	err := row.Scan(&latest)
	return latest, err
}

const recordChange = `-- name: RecordChange :exec
INSERT INTO policy_changes (account_id, actor, action, rule_id, suffixes_before, suffixes_after)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordChangeParams struct {
	AccountID      pgtype.Text
	Actor          string
	Action         string
	RuleID         string
	SuffixesBefore []string
	SuffixesAfter  []string
}

// Appends one change to one of the account's own rules to the policy history, in the transaction that
// made it (ADR-0102).
func (q *Queries) RecordChange(ctx context.Context, arg RecordChangeParams) error {
	_, err := q.db.Exec(ctx, recordChange,
		arg.AccountID,
		arg.Actor,
		arg.Action,
		arg.RuleID,
		arg.SuffixesBefore,
		arg.SuffixesAfter,
	)
	return err
}

const ruleHistory = `-- name: RuleHistory :many
SELECT
    c.id,
    c.ts,
    c.account_id,
    c.actor,
    c.action,
    c.rule_id,
    c.suffixes_before,
    c.suffixes_after
FROM policy_changes AS c
WHERE
    (c.account_id = $1::text OR c.account_id IS NULL)
    AND c.rule_id = $2
    AND $3::boolean = (c.account_id IS NULL)
ORDER BY c.ts DESC, c.id DESC
`

type RuleHistoryParams struct {
	AccountID string
	RuleID    string
	Base      bool
}

type RuleHistoryRow struct {
	ID             int64
	Ts             pgtype.Timestamptz
	AccountID      pgtype.Text
	Actor          string
	Action         string
	RuleID         string
	SuffixesBefore []string
	SuffixesAfter  []string
}

// One rule's changes, newest first, the changes recorded under its identifier and its scope, the
// account's own when base is false and the base policy's when it is true (docs/UI.md section 8.7).
func (q *Queries) RuleHistory(ctx context.Context, arg RuleHistoryParams) ([]RuleHistoryRow, error) {
	rows, err := q.db.Query(ctx, ruleHistory, arg.AccountID, arg.RuleID, arg.Base)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleHistoryRow
	for rows.Next() {
		var i RuleHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.AccountID,
			&i.Actor,
			&i.Action,
			&i.RuleID,
			&i.SuffixesBefore,
			&i.SuffixesAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
