// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package policychanges

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// The policy_changes dataset's figures, the changes the account's history holds under the dataset's
	// range and filters, those that added restriction and those that lifted it (docs/UI.md section 17.1).
	// An edit lifts when it removed a suffix and adds when it removed none. The account's history is its
	// own changes and the base policy's (ADR-0102). base_rows and own_rows say which scopes the scope
	// filter keeps. A null array is no filter.
	ChangeFigures(ctx context.Context, arg ChangeFiguresParams) (ChangeFiguresRow, error)
	// One page of the policy_changes dataset, fifty rows, under the same filters, newest first by default,
	// the change's identifier ending the sort.
	ChangeRows(ctx context.Context, arg ChangeRowsParams) ([]ChangeRowsRow, error)
	// Every group of the policy_changes dataset by action, under the same filters, ordered by count and
	// then by the group's key, the order the bars draw (docs/UI.md section 17.1).
	ChangesByAction(ctx context.Context, arg ChangesByActionParams) ([]ChangesByActionRow, error)
	// Every group of the policy_changes dataset by the identity that made the change, as ChangesByAction.
	ChangesByActor(ctx context.Context, arg ChangesByActorParams) ([]ChangesByActorRow, error)
	// Every group of the policy_changes dataset by the UTC day of the change, as ChangesByAction.
	ChangesByDay(ctx context.Context, arg ChangesByDayParams) ([]ChangesByDayRow, error)
	// Every group of the policy_changes dataset by scope, as ChangesByAction. The base policy's changes
	// are the null group, last.
	ChangesByScope(ctx context.Context, arg ChangesByScopeParams) ([]ChangesByScopeRow, error)
	// When the account's policy last changed, its own rules or the base policy's, null before its first
	// change, for the policy screen's L0 strip.
	LatestChange(ctx context.Context, accountID string) (pgtype.Timestamptz, error)
	// Appends one change to one of the account's own rules to the policy history, in the transaction that
	// made it (ADR-0102).
	RecordChange(ctx context.Context, arg RecordChangeParams) error
	// One rule's changes, newest first, the changes recorded under its identifier and its scope, the
	// account's own when base is false and the base policy's when it is true (docs/UI.md section 8.7).
	RuleHistory(ctx context.Context, arg RuleHistoryParams) ([]RuleHistoryRow, error)
}

var _ Querier = (*Queries)(nil)
