// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: base.sql

package base

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBaseRule = `-- name: AddBaseRule :exec
INSERT INTO policy_rules (account_id, rule_id, class, domain_suffix, source, created_by)
VALUES (NULL, $1, $2, $3, $4, $5)
`

type AddBaseRuleParams struct {
	RuleID       string
	Class        string
	DomainSuffix []string
	Source       string
	CreatedBy    string
}

// Adds a base rule, which every account inherits (ADR-0004). The table's key refuses an identifier
// the base policy already holds (ADR-0110).
func (q *Queries) AddBaseRule(ctx context.Context, arg AddBaseRuleParams) error {
	_, err := q.db.Exec(ctx, addBaseRule,
		arg.RuleID,
		arg.Class,
		arg.DomainSuffix,
		arg.Source,
		arg.CreatedBy,
	)
	return err
}

const baseHistory = `-- name: BaseHistory :many
SELECT
    c.id,
    c.ts,
    c.actor,
    c.action,
    c.rule_id,
    c.suffixes_before,
    c.suffixes_after
FROM policy_changes AS c
WHERE
    c.account_id IS NULL
    AND ($1::timestamptz IS NULL OR c.ts >= $1::timestamptz)
    AND ($2::timestamptz IS NULL OR c.ts < $2::timestamptz)
    AND ($3::text IS NULL OR c.rule_id = $3::text)
ORDER BY c.ts DESC, c.id DESC
`

type BaseHistoryParams struct {
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	RuleID     string
}

type BaseHistoryRow struct {
	ID             int64
	Ts             pgtype.Timestamptz
	Actor          string
	Action         string
	RuleID         string
	SuffixesBefore []string
	SuffixesAfter  []string
}

// The base policy's changes, newest first, under a range and narrowed to one rule's when a rule is
// given (docs/UI.md sections 8.14 and 17.4). A null bound is no bound, and a null rule every rule.
func (q *Queries) BaseHistory(ctx context.Context, arg BaseHistoryParams) ([]BaseHistoryRow, error) {
	rows, err := q.db.Query(ctx, baseHistory, arg.RangeStart, arg.RangeEnd, arg.RuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BaseHistoryRow
	for rows.Next() {
		var i BaseHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Actor,
			&i.Action,
			&i.RuleID,
			&i.SuffixesBefore,
			&i.SuffixesAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const baseLatestChange = `-- name: BaseLatestChange :one
SELECT max(c.ts)::timestamptz AS latest
FROM policy_changes AS c
WHERE c.account_id IS NULL
`

// When the base policy last changed, null before its first change, for the base policy screen's L0
// strip.
func (q *Queries) BaseLatestChange(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, baseLatestChange)
	var latest pgtype.Timestamptz
	err := row.Scan(&latest)
	return latest, err
}

const baseRules = `-- name: BaseRules :many
SELECT
    r.rule_id,
    r.class,
    r.domain_suffix,
    r.source,
    r.created_at,
    r.created_by
FROM policy_rules AS r
WHERE r.account_id IS NULL
ORDER BY r.rule_id
`

type BaseRulesRow struct {
	RuleID       string
	Class        string
	DomainSuffix []string
	Source       string
	CreatedAt    pgtype.Timestamptz
	CreatedBy    string
}

// The base policy's rules, with what the base policy screen shows of each (docs/UI.md section 8.14).
// Run only in a base-policy transaction, which names no account (ADR-0112).
func (q *Queries) BaseRules(ctx context.Context) ([]BaseRulesRow, error) {
	rows, err := q.db.Query(ctx, baseRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BaseRulesRow
	for rows.Next() {
		var i BaseRulesRow
		if err := rows.Scan(
			&i.RuleID,
			&i.Class,
			&i.DomainSuffix,
			&i.Source,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const editBaseRule = `-- name: EditBaseRule :execrows
UPDATE policy_rules
SET domain_suffix = $1
WHERE account_id IS NULL AND rule_id = $2 AND domain_suffix = $3::text[]
`

type EditBaseRuleParams struct {
	DomainSuffix   []string
	RuleID         string
	SuffixesBefore []string
}

// Sets a base rule's domain suffixes, only while they are still the suffixes the edit was made
// against.
func (q *Queries) EditBaseRule(ctx context.Context, arg EditBaseRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, editBaseRule, arg.DomainSuffix, arg.RuleID, arg.SuffixesBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const liftBaseRule = `-- name: LiftBaseRule :execrows
DELETE FROM policy_rules
WHERE account_id IS NULL AND rule_id = $1 AND domain_suffix = $2::text[]
`

type LiftBaseRuleParams struct {
	RuleID         string
	SuffixesBefore []string
}

// Removes a base rule, only while its suffixes are still the ones the lift was confirmed against.
func (q *Queries) LiftBaseRule(ctx context.Context, arg LiftBaseRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, liftBaseRule, arg.RuleID, arg.SuffixesBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordBaseChange = `-- name: RecordBaseChange :exec
INSERT INTO policy_changes (account_id, actor, action, rule_id, suffixes_before, suffixes_after)
VALUES (NULL, $1, $2, $3, $4, $5)
`

type RecordBaseChangeParams struct {
	Actor          string
	Action         string
	RuleID         string
	SuffixesBefore []string
	SuffixesAfter  []string
}

// Appends one change to a base rule to the policy history, in the transaction that made it (ADR-0102).
func (q *Queries) RecordBaseChange(ctx context.Context, arg RecordBaseChangeParams) error {
	_, err := q.db.Exec(ctx, recordBaseChange,
		arg.Actor,
		arg.Action,
		arg.RuleID,
		arg.SuffixesBefore,
		arg.SuffixesAfter,
	)
	return err
}
