// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package base

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Adds a base rule, which every account inherits (ADR-0004). The table's key refuses an identifier
	// the base policy already holds (ADR-0110).
	AddBaseRule(ctx context.Context, arg AddBaseRuleParams) error
	// The base policy's changes, newest first, under a range and narrowed to one rule's when a rule is
	// given (docs/UI.md sections 8.14 and 17.4). A null bound is no bound, and an empty rule every rule.
	BaseHistory(ctx context.Context, arg BaseHistoryParams) ([]BaseHistoryRow, error)
	// When the base policy last changed, null before its first change, for the base policy screen's L0
	// strip.
	BaseLatestChange(ctx context.Context) (pgtype.Timestamptz, error)
	// The base policy's rules, with what the base policy screen shows of each (docs/UI.md section 8.14).
	// Run only in a base-policy transaction, which names no account (ADR-0112).
	BaseRules(ctx context.Context) ([]BaseRulesRow, error)
	// Sets a base rule's domain suffixes, only while they are still the suffixes the edit was made
	// against.
	EditBaseRule(ctx context.Context, arg EditBaseRuleParams) (int64, error)
	// Removes a base rule, only while its suffixes are still the ones the lift was confirmed against.
	LiftBaseRule(ctx context.Context, arg LiftBaseRuleParams) (int64, error)
	// Appends one change to a base rule to the policy history, in the transaction that made it (ADR-0102).
	RecordBaseChange(ctx context.Context, arg RecordBaseChangeParams) error
}

var _ Querier = (*Queries)(nil)
