// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package policyrules

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const policyRules = `-- name: PolicyRules :many
SELECT
    account_id,
    rule_id,
    class,
    domain_suffix
FROM policy_rules
WHERE account_id = $1::text OR account_id IS NULL
ORDER BY rule_id
`

type PolicyRulesRow struct {
	AccountID    pgtype.Text
	RuleID       string
	Class        string
	DomainSuffix []string
}

// The rules the account's policy is composed from, the base rules every account inherits and the
// account's own, in one read (ADR-0004, ADR-0026). A base rule carries a null account, so the
// account predicate is the account or null (ADR-0047). The account is null for a base rule.
func (q *Queries) PolicyRules(ctx context.Context, accountID string) ([]PolicyRulesRow, error) {
	rows, err := q.db.Query(ctx, policyRules, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyRulesRow
	for rows.Next() {
		var i PolicyRulesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.RuleID,
			&i.Class,
			&i.DomainSuffix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
