// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package ingest

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    account_id,
    message_id,
    thread_id,
    from_email,
    from_domain,
    from_name,
    subject,
    subject_masked,
    sent_at,
    labels,
    flags,
    has_attachments,
    list_id,
    size_bytes,
    auth_results,
    sender_class,
    class_rule_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
ON CONFLICT (account_id, message_id) DO NOTHING
RETURNING message_id
`

type InsertMessageParams struct {
	AccountID      string
	MessageID      string
	ThreadID       string
	FromEmail      string
	FromDomain     string
	FromName       pgtype.Text
	Subject        pgtype.Text
	SubjectMasked  bool
	SentAt         pgtype.Timestamptz
	Labels         []string
	Flags          []byte
	HasAttachments bool
	ListID         pgtype.Text
	SizeBytes      pgtype.Int4
	AuthResults    []byte
	SenderClass    string
	ClassRuleID    pgtype.Text
}

// Adds one message's metadata to the index, with its sender class, the policy rule that set it or
// null when none did, and its subject already masked (ADR-0003, ADR-0016, ADR-0017). A message the
// index already holds is left as it is and returns no row, so a page ingested twice adds nothing the
// second time and its caller records masking events only for the messages this call added. The row
// holds no body, snippet or attachment name (ADR-0016).
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (string, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.AccountID,
		arg.MessageID,
		arg.ThreadID,
		arg.FromEmail,
		arg.FromDomain,
		arg.FromName,
		arg.Subject,
		arg.SubjectMasked,
		arg.SentAt,
		arg.Labels,
		arg.Flags,
		arg.HasAttachments,
		arg.ListID,
		arg.SizeBytes,
		arg.AuthResults,
		arg.SenderClass,
		arg.ClassRuleID,
	)
	var message_id string
	err := row.Scan(&message_id)
	return message_id, err
}
