// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ingest

import (
	"context"
)

type Querier interface {
	// How many of the account's stored subjects were masked under another scanner version or
	// configuration revision than the one given, or under none recorded. Any makes the first pass due
	// again, and once its enumeration has ended the first pass records the count in its checkpoint, as
	// the subjects it has still to fetch again (ADR-0120).
	CountStaleSubjects(ctx context.Context, arg CountStaleSubjectsParams) (int64, error)
	// Adds the media of a message's attachments, each normalized media type paired with the extension at
	// the same position, once each, from which the types a client is served are derived when read
	// (ADR-0123). It is run for a message InsertMessage has just added, whose media never change once
	// stored, so a pair already stored is left as it is.
	InsertAttachmentMedia(ctx context.Context, arg InsertAttachmentMediaParams) error
	// Adds one message's metadata to the index, with its sender class, the policy rule that set it or
	// null when none did, its subject already masked (ADR-0003, ADR-0016, ADR-0017) and the scanner
	// version and configuration revision the masking ran under (ADR-0120). A message the index already
	// holds is left as it is and returns no row, so a page ingested twice adds nothing the second time.
	// The row holds no body, snippet or attachment name (ADR-0016).
	InsertMessage(ctx context.Context, arg InsertMessageParams) (string, error)
	// Replaces each stored subject named, unmasked and masked under another scanner version or
	// configuration revision than the one given, or under none recorded, with the subject given, masked
	// again from what was stored, and records the pair given, all in one statement, so masking again
	// every unmasked subject of a mailbox costs a statement a batch and not one a message (ADR-0120). No
	// other column of the row changes. A subject stored masked is left as it is, since only the provider
	// holds what its masks hid.
	RemaskStoredSubjects(ctx context.Context, arg RemaskStoredSubjectsParams) (int64, error)
	// Replaces a stored subject masked under another scanner version or configuration revision, or under
	// none recorded, with the subject masked under the pair given, and records the pair (ADR-0120). No
	// other column of the row changes. A subject already masked under the pair given is left as it is and
	// counts no row, so a page taken twice masks nothing twice.
	RemaskSubject(ctx context.Context, arg RemaskSubjectParams) (int64, error)
	// Whether any of the account's stored subjects was masked under another scanner version or
	// configuration revision than the one given, or under none recorded, which makes the first pass due
	// again (ADR-0120).
	StaleSubject(ctx context.Context, arg StaleSubjectParams) (bool, error)
	// Up to the number given of the account's messages whose stored subject was masked under another
	// scanner version or configuration revision than the one given, or under none recorded, with the
	// subject as stored, in the order of their identifiers. They are the subjects the first pass fetches
	// again by identifier once its enumeration has ended, each masked again under the pair given, so a
	// subject it fetched leaves the set (ADR-0120).
	StaleSubjects(ctx context.Context, arg StaleSubjectsParams) ([]StaleSubjectsRow, error)
	// Up to the number given of the account's messages after the identifier given whose stored subject
	// is unmasked and was masked under another scanner version or configuration revision than the one
	// given, or under none recorded, with the subject as stored, in the order of their identifiers. A
	// subject stored unmasked is the subject the provider returned, so backfill's run-start step masks
	// it again from what is stored (ADR-0120).
	StaleUnmaskedSubjects(ctx context.Context, arg StaleUnmaskedSubjectsParams) ([]StaleUnmaskedSubjectsRow, error)
}

var _ Querier = (*Queries)(nil)
