// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: corpus.sql

package classification

import (
	"context"
)

const corpusFigures = `-- name: CorpusFigures :one
SELECT
    count(*) AS messages,
    count(DISTINCT m.thread_id) AS threads,
    count(*) FILTER (WHERE m.labels = '{}') AS unfiled,
    count(*) FILTER (WHERE m.sender_class = 'restricted') AS restricted
FROM messages AS m
WHERE m.account_id = $1
`

type CorpusFiguresRow struct {
	Messages   int64
	Threads    int64
	Unfiled    int64
	Restricted int64
}

// The account's corpus at a glance, for the system endpoint's corpus block (docs/UI.md section 8.1).
// Unfiled is a message with no label, and restricted one whose sender class reads restricted now.
func (q *Queries) CorpusFigures(ctx context.Context, accountID string) (CorpusFiguresRow, error) {
	row := q.db.QueryRow(ctx, corpusFigures, accountID)
	var i CorpusFiguresRow
	err := row.Scan(
		&i.Messages,
		&i.Threads,
		&i.Unfiled,
		&i.Restricted,
	)
	return i, err
}
