// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package classification

import (
	"context"
)

type Querier interface {
	// The account's corpus at a glance, for the system endpoint's corpus block (docs/UI.md section 8.1).
	// Unfiled is a message with no label, and restricted one whose sender class reads restricted now.
	CorpusFigures(ctx context.Context, accountID string) (CorpusFiguresRow, error)
}

var _ Querier = (*Queries)(nil)
