// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountsetup

import (
	"context"
)

type Querier interface {
	// What account setup and account settings read of the account, its provider and client, whether it
	// has a state row, the mailbox it remembers and its lowered target. It reads no credential (ADR-0084,
	// ADR-0091). No row means no account holds the identifier.
	AccountSetup(ctx context.Context, accountID string) ([]AccountSetupRow, error)
	// Writes a new account's listing row with the client it connects through, in the transaction that
	// writes its state row (ADR-0091, ADR-0106). The primary key refuses an identifier another account
	// holds.
	AddAccount(ctx context.Context, arg AddAccountParams) error
	// Writes a connected account's state row, its sealed credential, the mailbox the consent confirmed
	// and the lowered target the operator set, or NULL for none (ADR-0080, ADR-0081, ADR-0024).
	AddState(ctx context.Context, arg AddStateParams) error
	// Moves the account to another client of its provider, in the transaction that writes the credential
	// issued to that client (ADR-0106).
	MoveAccount(ctx context.Context, arg MoveAccountParams) (int64, error)
	// Replaces a re-authorized account's credential, unconditionally, since the operator's write is the
	// newest (ADR-0089). The mailbox is written only where the row remembers none, so a remembered one
	// never changes (ADR-0080). No row means the account has no state row.
	Reauthorize(ctx context.Context, arg ReauthorizeParams) (int64, error)
	// Stores the lowered target the operator set, a fraction of the provider's declared ceiling, or NULL
	// for none (ADR-0024). No row means the account has no state row.
	SetLoweredTarget(ctx context.Context, arg SetLoweredTargetParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
