// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package setup

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountSetup = `-- name: AccountSetup :many
SELECT
    a.provider AS account_provider,
    a.oauth_client,
    s.mailbox,
    s.lowered_target_rate,
    (s.account_id IS NOT NULL)::boolean AS connected
FROM accounts AS a
LEFT JOIN account_state AS s ON a.account_id = s.account_id
WHERE a.account_id = $1
`

type AccountSetupRow struct {
	AccountProvider   string
	OauthClient       pgtype.Text
	Mailbox           pgtype.Text
	LoweredTargetRate pgtype.Float4
	Connected         bool
}

// What account setup and account settings read of the account, its provider and client, whether it
// has a state row, the mailbox it remembers and its lowered target. It reads no credential (ADR-0084,
// ADR-0091). No row means no account holds the identifier.
func (q *Queries) AccountSetup(ctx context.Context, accountID string) ([]AccountSetupRow, error) {
	rows, err := q.db.Query(ctx, accountSetup, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountSetupRow
	for rows.Next() {
		var i AccountSetupRow
		if err := rows.Scan(
			&i.AccountProvider,
			&i.OauthClient,
			&i.Mailbox,
			&i.LoweredTargetRate,
			&i.Connected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addAccount = `-- name: AddAccount :exec
INSERT INTO accounts (account_id, provider, oauth_client)
VALUES ($1, $2, $3)
`

type AddAccountParams struct {
	AccountID   string
	Provider    string
	OauthClient pgtype.Text
}

// Writes a new account's listing row with the client it connects through, in the transaction that
// writes its state row (ADR-0091, ADR-0106). The primary key refuses an identifier another account
// holds.
func (q *Queries) AddAccount(ctx context.Context, arg AddAccountParams) error {
	_, err := q.db.Exec(ctx, addAccount, arg.AccountID, arg.Provider, arg.OauthClient)
	return err
}

const addState = `-- name: AddState :exec
INSERT INTO account_state (account_id, credential, mailbox, lowered_target_rate)
VALUES ($1, $2, $3, $4)
`

type AddStateParams struct {
	AccountID     string
	Credential    []byte
	Mailbox       pgtype.Text
	LoweredTarget pgtype.Float4
}

// Writes a connected account's state row, its sealed credential, the mailbox the consent confirmed
// and the lowered target the operator set, or NULL for none (ADR-0080, ADR-0081, ADR-0024).
func (q *Queries) AddState(ctx context.Context, arg AddStateParams) error {
	_, err := q.db.Exec(ctx, addState,
		arg.AccountID,
		arg.Credential,
		arg.Mailbox,
		arg.LoweredTarget,
	)
	return err
}

const moveAccount = `-- name: MoveAccount :execrows
UPDATE accounts
SET oauth_client = $1
WHERE account_id = $2 AND provider = $3
`

type MoveAccountParams struct {
	OauthClient pgtype.Text
	AccountID   string
	Provider    string
}

// Moves the account to another client of its provider, in the transaction that writes the credential
// issued to that client (ADR-0106).
func (q *Queries) MoveAccount(ctx context.Context, arg MoveAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveAccount, arg.OauthClient, arg.AccountID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reauthorize = `-- name: Reauthorize :execrows
UPDATE account_state
SET
    credential = $1,
    mailbox = coalesce(mailbox, $2::text)
WHERE account_id = $3
`

type ReauthorizeParams struct {
	Credential []byte
	Mailbox    string
	AccountID  string
}

// Replaces a re-authorized account's credential, unconditionally, since the operator's write is the
// newest (ADR-0089). The mailbox is written only where the row remembers none, so a remembered one
// never changes (ADR-0080). No row means the account has no state row.
func (q *Queries) Reauthorize(ctx context.Context, arg ReauthorizeParams) (int64, error) {
	result, err := q.db.Exec(ctx, reauthorize, arg.Credential, arg.Mailbox, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLoweredTarget = `-- name: SetLoweredTarget :execrows
UPDATE account_state
SET lowered_target_rate = $1
WHERE account_id = $2
`

type SetLoweredTargetParams struct {
	LoweredTarget pgtype.Float4
	AccountID     string
}

// Stores the lowered target the operator set, a fraction of the provider's declared ceiling, or NULL
// for none (ADR-0024). No row means the account has no state row.
func (q *Queries) SetLoweredTarget(ctx context.Context, arg SetLoweredTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLoweredTarget, arg.LoweredTarget, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
