// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: senders.sql

package classification

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const senderClasses = `-- name: SenderClasses :many
SELECT
    s.domain,
    s.sender_class,
    s.message_count
FROM senders AS s
WHERE s.account_id = $1
ORDER BY s.domain
`

type SenderClassesRow struct {
	Domain       string
	SenderClass  string
	MessageCount int64
}

// Every one of the account's senders with its stored class and message count, which the policy
// screens match against the rules to count what each rule matches and restricts (docs/UI.md section
// 8.7). Matching a sender against a rule is the sender classifier's, so it is made in the UI's server.
func (q *Queries) SenderClasses(ctx context.Context, accountID string) ([]SenderClassesRow, error) {
	rows, err := q.db.Query(ctx, senderClasses, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SenderClassesRow
	for rows.Next() {
		var i SenderClassesRow
		if err := rows.Scan(&i.Domain, &i.SenderClass, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const senderSearchDomains = `-- name: SenderSearchDomains :many
SELECT
    s.domain,
    s.message_count
FROM senders AS s
WHERE
    s.account_id = $1
    AND ($2::text = '' OR strpos(lower(s.domain::text), lower($2::text)) > 0)
ORDER BY s.message_count DESC, s.domain ASC
`

type SenderSearchDomainsParams struct {
	AccountID string
	Search    string
}

type SenderSearchDomainsRow struct {
	Domain       string
	MessageCount int64
}

// Every domain the search matches with its message count, which a selection of every match hands to
// Add a rule (docs/UI.md section 8.7).
func (q *Queries) SenderSearchDomains(ctx context.Context, arg SenderSearchDomainsParams) ([]SenderSearchDomainsRow, error) {
	rows, err := q.db.Query(ctx, senderSearchDomains, arg.AccountID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SenderSearchDomainsRow
	for rows.Next() {
		var i SenderSearchDomainsRow
		if err := rows.Scan(&i.Domain, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const senderSearchFigures = `-- name: SenderSearchFigures :one
SELECT
    count(*) AS senders,
    coalesce(sum(s.message_count), 0)::bigint AS messages
FROM senders AS s
WHERE
    s.account_id = $1
    AND ($2::text = '' OR strpos(lower(s.domain::text), lower($2::text)) > 0)
`

type SenderSearchFiguresParams struct {
	AccountID string
	Search    string
}

type SenderSearchFiguresRow struct {
	Senders  int64
	Messages int64
}

// The senders dataset's figures under its search filter, the senders it matches and their messages
// (docs/UI.md section 8.7). The search is a case-insensitive substring of the domain, and a null
// search matches every sender.
func (q *Queries) SenderSearchFigures(ctx context.Context, arg SenderSearchFiguresParams) (SenderSearchFiguresRow, error) {
	row := q.db.QueryRow(ctx, senderSearchFigures, arg.AccountID, arg.Search)
	var i SenderSearchFiguresRow
	err := row.Scan(&i.Senders, &i.Messages)
	return i, err
}

const senderSearchRows = `-- name: SenderSearchRows :many
SELECT
    s.domain,
    s.sender_class,
    s.message_count,
    s.first_seen,
    s.last_seen,
    s.has_list_id_ratio,
    s.scan_hit_count
FROM senders AS s
WHERE
    s.account_id = $1
    AND ($2::text = '' OR strpos(lower(s.domain::text), lower($2::text)) > 0)
ORDER BY
    CASE WHEN $3::boolean THEN s.message_count END DESC,
    CASE WHEN NOT $3::boolean THEN s.message_count END ASC,
    s.domain ASC
LIMIT 50 OFFSET $4
`

type SenderSearchRowsParams struct {
	AccountID  string
	Search     string
	Descending bool
	RowOffset  int32
}

type SenderSearchRowsRow struct {
	Domain         string
	SenderClass    string
	MessageCount   int64
	FirstSeen      pgtype.Timestamptz
	LastSeen       pgtype.Timestamptz
	HasListIDRatio pgtype.Float4
	ScanHitCount   int64
}

// One page of the senders dataset, fifty rows, under the same filter, with the sender row's fields
// (docs/UI.md section 7.2), the sender with the most messages first by default, the domain ending the
// sort.
func (q *Queries) SenderSearchRows(ctx context.Context, arg SenderSearchRowsParams) ([]SenderSearchRowsRow, error) {
	rows, err := q.db.Query(ctx, senderSearchRows,
		arg.AccountID,
		arg.Search,
		arg.Descending,
		arg.RowOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SenderSearchRowsRow
	for rows.Next() {
		var i SenderSearchRowsRow
		if err := rows.Scan(
			&i.Domain,
			&i.SenderClass,
			&i.MessageCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.HasListIDRatio,
			&i.ScanHitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
