// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package oauthclients

import (
	"context"
)

const oAuthClients = `-- name: OAuthClients :many
SELECT
    name AS client_name,
    provider,
    client_id,
    client_secret AS sealed_client_secret
FROM oauth_clients
ORDER BY name
`

type OAuthClientsRow struct {
	ClientName         string
	Provider           string
	ClientID           string
	SealedClientSecret []byte
}

// Every stored OAuth client, any number for each provider that authenticates through one, keyed on
// the name the person running the installation gave it (ADR-0080, ADR-0106). The table belongs to no
// account.
func (q *Queries) OAuthClients(ctx context.Context) ([]OAuthClientsRow, error) {
	rows, err := q.db.Query(ctx, oAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OAuthClientsRow
	for rows.Next() {
		var i OAuthClientsRow
		if err := rows.Scan(
			&i.ClientName,
			&i.Provider,
			&i.ClientID,
			&i.SealedClientSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
