// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package oauthclients

import (
	"context"
)

const oAuthClients = `-- name: OAuthClients :many
SELECT
    provider,
    client_id,
    client_secret AS sealed_client_secret
FROM oauth_clients
ORDER BY provider
`

type OAuthClientsRow struct {
	Provider           string
	ClientID           string
	SealedClientSecret []byte
}

// Every stored OAuth client, one for each provider that authenticates through one (ADR-0080,
// ADR-0083). The table belongs to no account.
func (q *Queries) OAuthClients(ctx context.Context) ([]OAuthClientsRow, error) {
	rows, err := q.db.Query(ctx, oAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OAuthClientsRow
	for rows.Next() {
		var i OAuthClientsRow
		if err := rows.Scan(&i.Provider, &i.ClientID, &i.SealedClientSecret); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
