// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package oauthclients

import (
	"context"
)

type Querier interface {
	// Every stored OAuth client, any number for each provider that authenticates through one, keyed on
	// the name the person running the installation gave it (ADR-0080, ADR-0106). The table belongs to no
	// account.
	OAuthClients(ctx context.Context) ([]OAuthClientsRow, error)
}

var _ Querier = (*Queries)(nil)
