// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package oauthclients

import (
	"context"
)

type Querier interface {
	// Every stored OAuth client, one for each provider that authenticates through one (ADR-0080,
	// ADR-0083). The table belongs to no account.
	OAuthClients(ctx context.Context) ([]OAuthClientsRow, error)
}

var _ Querier = (*Queries)(nil)
