// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gate.sql

package messages

import (
	"context"
)

const bodyGate = `-- name: BodyGate :many
SELECT
    m.from_email,
    m.content_flags,
    m.scan_state,
    m.rule_ids
FROM messages AS m
WHERE m.account_id = $1 AND m.message_id = $2
`

type BodyGateParams struct {
	AccountID string
	MessageID string
}

type BodyGateRow struct {
	FromEmail    string
	ContentFlags []string
	ScanState    string
	RuleIds      []string
}

// What the Redaction Gate decides a body request from, read at fetch time (ADR-0002): the sender it
// classifies again under the policy in force, the content flags and scan state the index stores, and
// the content rules that set the flags, which the request's audit row names. Never the stored sender
// class. No row means the account holds no such message.
func (q *Queries) BodyGate(ctx context.Context, arg BodyGateParams) ([]BodyGateRow, error) {
	rows, err := q.db.Query(ctx, bodyGate, arg.AccountID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BodyGateRow
	for rows.Next() {
		var i BodyGateRow
		if err := rows.Scan(
			&i.FromEmail,
			&i.ContentFlags,
			&i.ScanState,
			&i.RuleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
