// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package messages

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const labels = `-- name: Labels :many
SELECT DISTINCT l.label::text AS label
FROM messages AS m
CROSS JOIN LATERAL unnest(m.labels) AS l (label)
WHERE m.account_id = $1
ORDER BY label
`

// Every distinct value the account's messages hold in their labels, in order. These are the values the
// other operations take as a label.
func (q *Queries) Labels(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, labels, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const message = `-- name: Message :many
SELECT
    m.message_id,
    m.thread_id,
    m.from_email,
    m.from_name,
    m.subject,
    m.sent_at,
    m.labels,
    m.flags,
    m.has_attachments,
    m.attachment_types,
    m.content_flags,
    m.scan_state
FROM messages AS m
WHERE m.account_id = $1 AND m.message_id = $2
`

type MessageParams struct {
	AccountID string
	MessageID string
}

type MessageRow struct {
	MessageID       string
	ThreadID        string
	FromEmail       string
	FromName        pgtype.Text
	Subject         pgtype.Text
	SentAt          pgtype.Timestamptz
	Labels          []string
	Flags           []byte
	HasAttachments  bool
	AttachmentTypes []string
	ContentFlags    []string
	ScanState       string
}

// One message of the account by its identifier, with the same columns as a page. No row means the
// account holds no such message.
func (q *Queries) Message(ctx context.Context, arg MessageParams) ([]MessageRow, error) {
	rows, err := q.db.Query(ctx, message, arg.AccountID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageRow
	for rows.Next() {
		var i MessageRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ThreadID,
			&i.FromEmail,
			&i.FromName,
			&i.Subject,
			&i.SentAt,
			&i.Labels,
			&i.Flags,
			&i.HasAttachments,
			&i.AttachmentTypes,
			&i.ContentFlags,
			&i.ScanState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagePage = `-- name: MessagePage :many
SELECT
    m.message_id,
    m.thread_id,
    m.from_email,
    m.from_name,
    m.subject,
    m.sent_at,
    m.labels,
    m.flags,
    m.has_attachments,
    m.attachment_types,
    m.content_flags,
    m.scan_state
FROM messages AS m
WHERE
    m.account_id = $1
    AND (
        $2::timestamptz IS NULL
        OR (m.sent_at, m.message_id) < ($2::timestamptz, $3::text)
    )
ORDER BY m.sent_at DESC, m.message_id DESC
LIMIT $4
`

type MessagePageParams struct {
	AccountID      string
	AfterSentAt    pgtype.Timestamptz
	AfterMessageID string
	PageSize       int32
}

type MessagePageRow struct {
	MessageID       string
	ThreadID        string
	FromEmail       string
	FromName        pgtype.Text
	Subject         pgtype.Text
	SentAt          pgtype.Timestamptz
	Labels          []string
	Flags           []byte
	HasAttachments  bool
	AttachmentTypes []string
	ContentFlags    []string
	ScanState       string
}

// One page of the account's messages, newest first, after the position a cursor names or from the
// start when it names none. The columns are the metadata the client surface serves and the content
// flags and scan state the Redaction Gate decides from. The stored sender class is not read, because
// the gate classifies the sender again against the policy in force (ADR-0001, ADR-0002).
func (q *Queries) MessagePage(ctx context.Context, arg MessagePageParams) ([]MessagePageRow, error) {
	rows, err := q.db.Query(ctx, messagePage,
		arg.AccountID,
		arg.AfterSentAt,
		arg.AfterMessageID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessagePageRow
	for rows.Next() {
		var i MessagePageRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ThreadID,
			&i.FromEmail,
			&i.FromName,
			&i.Subject,
			&i.SentAt,
			&i.Labels,
			&i.Flags,
			&i.HasAttachments,
			&i.AttachmentTypes,
			&i.ContentFlags,
			&i.ScanState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadMessages = `-- name: ThreadMessages :many
SELECT
    m.message_id,
    m.thread_id,
    m.from_email,
    m.from_name,
    m.subject,
    m.sent_at,
    m.labels,
    m.flags,
    m.has_attachments,
    m.attachment_types,
    m.content_flags,
    m.scan_state
FROM messages AS m
WHERE m.account_id = $1 AND m.thread_id = $2
ORDER BY m.sent_at ASC, m.message_id ASC
`

type ThreadMessagesParams struct {
	AccountID string
	ThreadID  string
}

type ThreadMessagesRow struct {
	MessageID       string
	ThreadID        string
	FromEmail       string
	FromName        pgtype.Text
	Subject         pgtype.Text
	SentAt          pgtype.Timestamptz
	Labels          []string
	Flags           []byte
	HasAttachments  bool
	AttachmentTypes []string
	ContentFlags    []string
	ScanState       string
}

// Every message of one of the account's threads, oldest first, with the same columns as a page. No
// row means the account holds no such thread.
func (q *Queries) ThreadMessages(ctx context.Context, arg ThreadMessagesParams) ([]ThreadMessagesRow, error) {
	rows, err := q.db.Query(ctx, threadMessages, arg.AccountID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadMessagesRow
	for rows.Next() {
		var i ThreadMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ThreadID,
			&i.FromEmail,
			&i.FromName,
			&i.Subject,
			&i.SentAt,
			&i.Labels,
			&i.Flags,
			&i.HasAttachments,
			&i.AttachmentTypes,
			&i.ContentFlags,
			&i.ScanState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadPage = `-- name: ThreadPage :many
SELECT
    m.thread_id,
    count(*) AS messages,
    max(m.sent_at)::timestamptz AS latest_at
FROM messages AS m
WHERE m.account_id = $1
GROUP BY m.thread_id
HAVING
    $2::timestamptz IS NULL
    OR (max(m.sent_at), m.thread_id) < ($2::timestamptz, $3::text)
ORDER BY latest_at DESC, m.thread_id DESC
LIMIT $4
`

type ThreadPageParams struct {
	AccountID      string
	BeforeLatestAt pgtype.Timestamptz
	BeforeThreadID string
	PageSize       int32
}

type ThreadPageRow struct {
	ThreadID string
	Messages int64
	LatestAt pgtype.Timestamptz
}

// One page of the account's threads, the one with the latest message first, each with its number of
// messages and the time of its latest, after the position a cursor names or from the start when it
// names none.
func (q *Queries) ThreadPage(ctx context.Context, arg ThreadPageParams) ([]ThreadPageRow, error) {
	rows, err := q.db.Query(ctx, threadPage,
		arg.AccountID,
		arg.BeforeLatestAt,
		arg.BeforeThreadID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadPageRow
	for rows.Next() {
		var i ThreadPageRow
		if err := rows.Scan(&i.ThreadID, &i.Messages, &i.LatestAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
