// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package messages

import (
	"context"
)

type Querier interface {
	// How many of the account's messages wait for their content scan, the scan backlog the system status
	// exposes (ADR-0034, docs/UI.md section 8.8).
	ScanBacklog(ctx context.Context, accountID string) (int64, error)
}

var _ Querier = (*Queries)(nil)
