// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package messages

import (
	"context"
)

type Querier interface {
	// What the Redaction Gate decides a body request from, read at fetch time (ADR-0002): the sender it
	// classifies again under the policy in force, the content flags and scan state the index stores, and
	// the content rules that set the flags, which the request's audit row names. Never the stored sender
	// class. No row means the account holds no such message.
	BodyGate(ctx context.Context, arg BodyGateParams) ([]BodyGateRow, error)
	// Every group the query's labelled messages form by label, the group with the most messages first and
	// ties by label. A message counts in the group of each label it carries. The messages with no label
	// are counted by SearchSummary with labels_within set to the empty list. The groups are as many as the
	// account's labels, so the service layer pages them rather than the statement.
	CountByLabel(ctx context.Context, arg CountByLabelParams) ([]CountByLabelRow, error)
	// Every group the query's messages form by the UTC calendar month they were sent in, keyed by the
	// instant the month starts, the group with the most messages first and ties by month. The groups are as
	// many as the months the account's mail spans, so the service layer pages them rather than the
	// statement.
	CountByMonth(ctx context.Context, arg CountByMonthParams) ([]CountByMonthRow, error)
	// One page of the groups the query's messages form by sender address, the group with the most
	// messages first and ties by address, after the position a cursor names or from the start.
	CountBySender(ctx context.Context, arg CountBySenderParams) ([]CountBySenderRow, error)
	// One page of the groups the query's messages form by sender domain, ordered and continued as the
	// groups by sender address are.
	CountBySenderDomain(ctx context.Context, arg CountBySenderDomainParams) ([]CountBySenderDomainRow, error)
	// Every distinct value the account's messages hold in their labels, in order. These are the values the
	// other operations take as a label.
	Labels(ctx context.Context, accountID string) ([]string, error)
	// One message of the account by its identifier, with the same columns as a page. No row means the
	// account holds no such message.
	Message(ctx context.Context, arg MessageParams) ([]MessageRow, error)
	// One page of the account's messages, newest first, after the position a cursor names or from the
	// start when it names none. The columns are the metadata the client surface serves and the content
	// flags and scan state the Redaction Gate decides from. The stored sender class is not read, because
	// the gate classifies the sender again against the policy in force (ADR-0001, ADR-0002).
	MessagePage(ctx context.Context, arg MessagePageParams) ([]MessagePageRow, error)
	// How many of the account's messages wait for their content scan, the scan backlog the system status
	// exposes (ADR-0034, docs/UI.md section 8.8).
	ScanBacklog(ctx context.Context, accountID string) (int64, error)
	// One page of the messages the query selects, in the order sort_by and descending name, after the
	// position a cursor names or from the start when it names none. Ties within one sort value are
	// broken by the message identifier, ascending, so the order is total.
	SearchPage(ctx context.Context, arg SearchPageParams) ([]SearchPageRow, error)
	// The number of messages the query selects, of their threads, of the unread among them and of those
	// with attachments, and the dates of the oldest and the newest. A message whose flags do not say it
	// was read counts as unread.
	SearchSummary(ctx context.Context, arg SearchSummaryParams) (SearchSummaryRow, error)
	// Every distinct sender address the account's messages hold, with its domain, which the service layer
	// classifies under the policy in force before a read that filters, groups or lists by sender class.
	SenderAddresses(ctx context.Context, accountID string) ([]SenderAddressesRow, error)
	// Every message of one of the account's threads, oldest first, with the same columns as a page. No
	// row means the account holds no such thread.
	ThreadMessages(ctx context.Context, arg ThreadMessagesParams) ([]ThreadMessagesRow, error)
	// One page of the account's threads, the one with the latest message first, each with its number of
	// messages and the time of its latest, after the position a cursor names or from the start when it
	// names none.
	ThreadPage(ctx context.Context, arg ThreadPageParams) ([]ThreadPageRow, error)
}

var _ Querier = (*Queries)(nil)
