// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package messages

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countByLabel = `-- name: CountByLabel :many
SELECT
    l.label::text AS label,
    count(*) AS messages,
    count(DISTINCT m.thread_id) AS threads,
    count(*) FILTER (WHERE NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) AS unread,
    count(*) FILTER (WHERE m.has_attachments) AS with_attachments,
    min(m.sent_at)::timestamptz AS oldest_at,
    max(m.sent_at)::timestamptz AS newest_at
FROM messages AS m
CROSS JOIN LATERAL unnest(m.labels) AS l (label)
WHERE
    m.account_id = $1
    AND ($2::timestamptz IS NULL OR m.sent_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR m.sent_at < $3::timestamptz)
    AND ($4::citext[] IS NULL OR m.from_email = any($4::citext[]))
    AND ($5::text[] IS NULL OR m.from_domain = any($5::text[]))
    AND ($6::text[] IS NULL OR m.labels @> $6::text[])
    AND ($7::text[] IS NULL OR NOT m.labels && $7::text[])
    AND ($8::text[] IS NULL OR m.labels <@ $8::text[])
    AND ($9::text[] IS NULL OR m.subject ILIKE all($9::text[]))
    AND (
        $10::boolean[] IS NULL
        OR (NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) = any($10::boolean[])
    )
    AND (
        $11::boolean[] IS NULL
        OR coalesce((m.flags ->> 'starred')::boolean, FALSE) = any($11::boolean[])
    )
    AND ($12::boolean[] IS NULL OR m.has_attachments = any($12::boolean[]))
    AND (
        $13::boolean[] IS NULL
        OR (
            NOT EXISTS (
                SELECT 1 FROM unnest($14::text[]) AS n (d)
                WHERE n.d = m.from_domain::text
            )
        ) = any($13::boolean[])
    )
GROUP BY l.label
ORDER BY messages DESC, l.label ASC
`

type CountByLabelParams struct {
	AccountID       string
	After           pgtype.Timestamptz
	Before          pgtype.Timestamptz
	FromEmails      []string
	FromDomains     []string
	Labels          []string
	ExcludedLabels  []string
	LabelsWithin    []string
	SubjectPatterns []string
	Unread          []bool
	Starred         []bool
	HasAttachments  []bool
	Restricted      []bool
	NormalDomains   []string
}

type CountByLabelRow struct {
	Label           string
	Messages        int64
	Threads         int64
	Unread          int64
	WithAttachments int64
	OldestAt        pgtype.Timestamptz
	NewestAt        pgtype.Timestamptz
}

// Every group the query's labelled messages form by label, the group with the most messages first and
// ties by label. A message counts in the group of each label it carries. The messages with no label
// are counted by SearchSummary with labels_within set to the empty list. The groups are as many as the
// account's labels, so the service layer pages them rather than the statement.
func (q *Queries) CountByLabel(ctx context.Context, arg CountByLabelParams) ([]CountByLabelRow, error) {
	rows, err := q.db.Query(ctx, countByLabel,
		arg.AccountID,
		arg.After,
		arg.Before,
		arg.FromEmails,
		arg.FromDomains,
		arg.Labels,
		arg.ExcludedLabels,
		arg.LabelsWithin,
		arg.SubjectPatterns,
		arg.Unread,
		arg.Starred,
		arg.HasAttachments,
		arg.Restricted,
		arg.NormalDomains,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountByLabelRow
	for rows.Next() {
		var i CountByLabelRow
		if err := rows.Scan(
			&i.Label,
			&i.Messages,
			&i.Threads,
			&i.Unread,
			&i.WithAttachments,
			&i.OldestAt,
			&i.NewestAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countByMonth = `-- name: CountByMonth :many
SELECT
    g.month::timestamptz AS month,
    count(*) AS messages,
    count(DISTINCT g.thread_id) AS threads,
    count(*) FILTER (WHERE NOT coalesce((g.flags ->> 'read')::boolean, FALSE)) AS unread,
    count(*) FILTER (WHERE g.has_attachments) AS with_attachments,
    min(g.sent_at)::timestamptz AS oldest_at,
    max(g.sent_at)::timestamptz AS newest_at
FROM (
    SELECT
        m.thread_id,
        m.flags,
        m.has_attachments,
        m.sent_at,
        date_trunc('month', m.sent_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC' AS month
    FROM messages AS m
    WHERE
        m.account_id = $1
        AND ($2::timestamptz IS NULL OR m.sent_at >= $2::timestamptz)
        AND ($3::timestamptz IS NULL OR m.sent_at < $3::timestamptz)
        AND ($4::citext[] IS NULL OR m.from_email = any($4::citext[]))
        AND ($5::text[] IS NULL OR m.from_domain = any($5::text[]))
        AND ($6::text[] IS NULL OR m.labels @> $6::text[])
        AND ($7::text[] IS NULL OR NOT m.labels && $7::text[])
        AND ($8::text[] IS NULL OR m.labels <@ $8::text[])
        AND ($9::text[] IS NULL OR m.subject ILIKE all($9::text[]))
        AND (
            $10::boolean[] IS NULL
            OR (NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) = any($10::boolean[])
        )
        AND (
            $11::boolean[] IS NULL
            OR coalesce((m.flags ->> 'starred')::boolean, FALSE) = any($11::boolean[])
        )
        AND ($12::boolean[] IS NULL OR m.has_attachments = any($12::boolean[]))
        AND (
            $13::boolean[] IS NULL
            OR (
                NOT EXISTS (
                    SELECT 1 FROM unnest($14::text[]) AS n (d)
                    WHERE n.d = m.from_domain::text
                )
            ) = any($13::boolean[])
        )
) AS g
GROUP BY g.month
ORDER BY messages DESC, g.month ASC
`

type CountByMonthParams struct {
	AccountID       string
	After           pgtype.Timestamptz
	Before          pgtype.Timestamptz
	FromEmails      []string
	FromDomains     []string
	Labels          []string
	ExcludedLabels  []string
	LabelsWithin    []string
	SubjectPatterns []string
	Unread          []bool
	Starred         []bool
	HasAttachments  []bool
	Restricted      []bool
	NormalDomains   []string
}

type CountByMonthRow struct {
	Month           pgtype.Timestamptz
	Messages        int64
	Threads         int64
	Unread          int64
	WithAttachments int64
	OldestAt        pgtype.Timestamptz
	NewestAt        pgtype.Timestamptz
}

// Every group the query's messages form by the UTC calendar month they were sent in, keyed by the
// instant the month starts, the group with the most messages first and ties by month. The groups are as
// many as the months the account's mail spans, so the service layer pages them rather than the
// statement.
func (q *Queries) CountByMonth(ctx context.Context, arg CountByMonthParams) ([]CountByMonthRow, error) {
	rows, err := q.db.Query(ctx, countByMonth,
		arg.AccountID,
		arg.After,
		arg.Before,
		arg.FromEmails,
		arg.FromDomains,
		arg.Labels,
		arg.ExcludedLabels,
		arg.LabelsWithin,
		arg.SubjectPatterns,
		arg.Unread,
		arg.Starred,
		arg.HasAttachments,
		arg.Restricted,
		arg.NormalDomains,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountByMonthRow
	for rows.Next() {
		var i CountByMonthRow
		if err := rows.Scan(
			&i.Month,
			&i.Messages,
			&i.Threads,
			&i.Unread,
			&i.WithAttachments,
			&i.OldestAt,
			&i.NewestAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBySender = `-- name: CountBySender :many
SELECT
    m.from_email,
    count(*) AS messages,
    count(DISTINCT m.thread_id) AS threads,
    count(*) FILTER (WHERE NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) AS unread,
    count(*) FILTER (WHERE m.has_attachments) AS with_attachments,
    min(m.sent_at)::timestamptz AS oldest_at,
    max(m.sent_at)::timestamptz AS newest_at
FROM messages AS m
WHERE
    m.account_id = $1
    AND ($2::timestamptz IS NULL OR m.sent_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR m.sent_at < $3::timestamptz)
    AND ($4::citext[] IS NULL OR m.from_email = any($4::citext[]))
    AND ($5::text[] IS NULL OR m.from_domain = any($5::text[]))
    AND ($6::text[] IS NULL OR m.labels @> $6::text[])
    AND ($7::text[] IS NULL OR NOT m.labels && $7::text[])
    AND ($8::text[] IS NULL OR m.labels <@ $8::text[])
    AND ($9::text[] IS NULL OR m.subject ILIKE all($9::text[]))
    AND (
        $10::boolean[] IS NULL
        OR (NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) = any($10::boolean[])
    )
    AND (
        $11::boolean[] IS NULL
        OR coalesce((m.flags ->> 'starred')::boolean, FALSE) = any($11::boolean[])
    )
    AND ($12::boolean[] IS NULL OR m.has_attachments = any($12::boolean[]))
    AND (
        $13::boolean[] IS NULL
        OR (
            NOT EXISTS (
                SELECT 1 FROM unnest($14::text[]) AS n (d)
                WHERE n.d = m.from_domain::text
            )
        ) = any($13::boolean[])
    )
GROUP BY m.from_email
HAVING
    $15::boolean
    OR count(*) < $16::bigint
    OR (count(*) = $16::bigint AND m.from_email > $17::citext)
ORDER BY messages DESC, m.from_email ASC
LIMIT $18
`

type CountBySenderParams struct {
	AccountID       string
	After           pgtype.Timestamptz
	Before          pgtype.Timestamptz
	FromEmails      []string
	FromDomains     []string
	Labels          []string
	ExcludedLabels  []string
	LabelsWithin    []string
	SubjectPatterns []string
	Unread          []bool
	Starred         []bool
	HasAttachments  []bool
	Restricted      []bool
	NormalDomains   []string
	FirstPage       bool
	AfterCount      int64
	AfterKey        string
	PageSize        int32
}

type CountBySenderRow struct {
	FromEmail       string
	Messages        int64
	Threads         int64
	Unread          int64
	WithAttachments int64
	OldestAt        pgtype.Timestamptz
	NewestAt        pgtype.Timestamptz
}

// One page of the groups the query's messages form by sender address, the group with the most
// messages first and ties by address, after the position a cursor names or from the start.
func (q *Queries) CountBySender(ctx context.Context, arg CountBySenderParams) ([]CountBySenderRow, error) {
	rows, err := q.db.Query(ctx, countBySender,
		arg.AccountID,
		arg.After,
		arg.Before,
		arg.FromEmails,
		arg.FromDomains,
		arg.Labels,
		arg.ExcludedLabels,
		arg.LabelsWithin,
		arg.SubjectPatterns,
		arg.Unread,
		arg.Starred,
		arg.HasAttachments,
		arg.Restricted,
		arg.NormalDomains,
		arg.FirstPage,
		arg.AfterCount,
		arg.AfterKey,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountBySenderRow
	for rows.Next() {
		var i CountBySenderRow
		if err := rows.Scan(
			&i.FromEmail,
			&i.Messages,
			&i.Threads,
			&i.Unread,
			&i.WithAttachments,
			&i.OldestAt,
			&i.NewestAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBySenderDomain = `-- name: CountBySenderDomain :many
SELECT
    m.from_domain,
    count(*) AS messages,
    count(DISTINCT m.thread_id) AS threads,
    count(*) FILTER (WHERE NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) AS unread,
    count(*) FILTER (WHERE m.has_attachments) AS with_attachments,
    min(m.sent_at)::timestamptz AS oldest_at,
    max(m.sent_at)::timestamptz AS newest_at
FROM messages AS m
WHERE
    m.account_id = $1
    AND ($2::timestamptz IS NULL OR m.sent_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR m.sent_at < $3::timestamptz)
    AND ($4::citext[] IS NULL OR m.from_email = any($4::citext[]))
    AND ($5::text[] IS NULL OR m.from_domain = any($5::text[]))
    AND ($6::text[] IS NULL OR m.labels @> $6::text[])
    AND ($7::text[] IS NULL OR NOT m.labels && $7::text[])
    AND ($8::text[] IS NULL OR m.labels <@ $8::text[])
    AND ($9::text[] IS NULL OR m.subject ILIKE all($9::text[]))
    AND (
        $10::boolean[] IS NULL
        OR (NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) = any($10::boolean[])
    )
    AND (
        $11::boolean[] IS NULL
        OR coalesce((m.flags ->> 'starred')::boolean, FALSE) = any($11::boolean[])
    )
    AND ($12::boolean[] IS NULL OR m.has_attachments = any($12::boolean[]))
    AND (
        $13::boolean[] IS NULL
        OR (
            NOT EXISTS (
                SELECT 1 FROM unnest($14::text[]) AS n (d)
                WHERE n.d = m.from_domain::text
            )
        ) = any($13::boolean[])
    )
GROUP BY m.from_domain
HAVING
    $15::boolean
    OR count(*) < $16::bigint
    OR (count(*) = $16::bigint AND m.from_domain > $17::text)
ORDER BY messages DESC, m.from_domain ASC
LIMIT $18
`

type CountBySenderDomainParams struct {
	AccountID       string
	After           pgtype.Timestamptz
	Before          pgtype.Timestamptz
	FromEmails      []string
	FromDomains     []string
	Labels          []string
	ExcludedLabels  []string
	LabelsWithin    []string
	SubjectPatterns []string
	Unread          []bool
	Starred         []bool
	HasAttachments  []bool
	Restricted      []bool
	NormalDomains   []string
	FirstPage       bool
	AfterCount      int64
	AfterKey        string
	PageSize        int32
}

type CountBySenderDomainRow struct {
	FromDomain      string
	Messages        int64
	Threads         int64
	Unread          int64
	WithAttachments int64
	OldestAt        pgtype.Timestamptz
	NewestAt        pgtype.Timestamptz
}

// One page of the groups the query's messages form by sender domain, ordered and continued as the
// groups by sender address are.
func (q *Queries) CountBySenderDomain(ctx context.Context, arg CountBySenderDomainParams) ([]CountBySenderDomainRow, error) {
	rows, err := q.db.Query(ctx, countBySenderDomain,
		arg.AccountID,
		arg.After,
		arg.Before,
		arg.FromEmails,
		arg.FromDomains,
		arg.Labels,
		arg.ExcludedLabels,
		arg.LabelsWithin,
		arg.SubjectPatterns,
		arg.Unread,
		arg.Starred,
		arg.HasAttachments,
		arg.Restricted,
		arg.NormalDomains,
		arg.FirstPage,
		arg.AfterCount,
		arg.AfterKey,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountBySenderDomainRow
	for rows.Next() {
		var i CountBySenderDomainRow
		if err := rows.Scan(
			&i.FromDomain,
			&i.Messages,
			&i.Threads,
			&i.Unread,
			&i.WithAttachments,
			&i.OldestAt,
			&i.NewestAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPage = `-- name: SearchPage :many
SELECT
    m.message_id,
    m.thread_id,
    m.from_email,
    m.from_name,
    m.subject,
    m.sent_at,
    m.labels,
    m.flags,
    m.has_attachments,
    m.content_flags,
    m.scan_state,
    -- The attachments' media, each media type paired with the extension at the same position, in
    -- the order of the table's key, from which the service layer derives the types (ADR-0123).
    coalesce((
        SELECT array_agg(x.media_type ORDER BY x.media_type, x.extension)
        FROM attachment_media AS x
        WHERE x.account_id = m.account_id AND x.message_id = m.message_id
    ), '{}')::text[] AS attachment_media_types,
    coalesce((
        SELECT array_agg(x.extension ORDER BY x.media_type, x.extension)
        FROM attachment_media AS x
        WHERE x.account_id = m.account_id AND x.message_id = m.message_id
    ), '{}')::text[] AS attachment_extensions
FROM messages AS m
WHERE
    m.account_id = $1
    AND ($2::timestamptz IS NULL OR m.sent_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR m.sent_at < $3::timestamptz)
    AND ($4::citext[] IS NULL OR m.from_email = any($4::citext[]))
    AND ($5::text[] IS NULL OR m.from_domain = any($5::text[]))
    AND ($6::text[] IS NULL OR m.labels @> $6::text[])
    AND ($7::text[] IS NULL OR NOT m.labels && $7::text[])
    AND ($8::text[] IS NULL OR m.labels <@ $8::text[])
    AND ($9::text[] IS NULL OR m.subject ILIKE all($9::text[]))
    AND (
        $10::boolean[] IS NULL
        OR (NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) = any($10::boolean[])
    )
    AND (
        $11::boolean[] IS NULL
        OR coalesce((m.flags ->> 'starred')::boolean, FALSE) = any($11::boolean[])
    )
    AND ($12::boolean[] IS NULL OR m.has_attachments = any($12::boolean[]))
    AND (
        $13::boolean[] IS NULL
        OR (
            NOT EXISTS (
                SELECT 1 FROM unnest($14::text[]) AS n (d)
                WHERE n.d = m.from_domain::text
            )
        ) = any($13::boolean[])
    )
    AND (
        $15::boolean
        OR (
            $16::text = 'date' AND $17::boolean AND (
                m.sent_at < $18::timestamptz
                OR (m.sent_at = $18::timestamptz AND m.message_id > $19::text)
            )
        )
        OR (
            $16::text = 'date' AND NOT $17::boolean AND (
                m.sent_at > $18::timestamptz
                OR (m.sent_at = $18::timestamptz AND m.message_id > $19::text)
            )
        )
        OR (
            $16::text = 'sender' AND $17::boolean AND (
                m.from_email < $20::citext
                OR (m.from_email = $20::citext AND m.message_id > $19::text)
            )
        )
        OR (
            $16::text = 'sender' AND NOT $17::boolean AND (
                m.from_email > $20::citext
                OR (m.from_email = $20::citext AND m.message_id > $19::text)
            )
        )
        OR (
            $16::text = 'subject' AND $17::boolean AND (
                coalesce(m.subject, '') < $21::text
                OR (coalesce(m.subject, '') = $21::text AND m.message_id > $19::text)
            )
        )
        OR (
            $16::text = 'subject' AND NOT $17::boolean AND (
                coalesce(m.subject, '') > $21::text
                OR (coalesce(m.subject, '') = $21::text AND m.message_id > $19::text)
            )
        )
    )
ORDER BY
    CASE WHEN $16::text = 'date' AND $17::boolean THEN m.sent_at END DESC,
    CASE WHEN $16::text = 'date' AND NOT $17::boolean THEN m.sent_at END ASC,
    CASE WHEN $16::text = 'sender' AND $17::boolean THEN m.from_email END DESC,
    CASE WHEN $16::text = 'sender' AND NOT $17::boolean THEN m.from_email END ASC,
    CASE WHEN $16::text = 'subject' AND $17::boolean THEN coalesce(m.subject, '') END DESC,
    CASE WHEN $16::text = 'subject' AND NOT $17::boolean THEN coalesce(m.subject, '') END ASC,
    m.message_id ASC
LIMIT $22
`

type SearchPageParams struct {
	AccountID       string
	After           pgtype.Timestamptz
	Before          pgtype.Timestamptz
	FromEmails      []string
	FromDomains     []string
	Labels          []string
	ExcludedLabels  []string
	LabelsWithin    []string
	SubjectPatterns []string
	Unread          []bool
	Starred         []bool
	HasAttachments  []bool
	Restricted      []bool
	NormalDomains   []string
	FirstPage       bool
	SortBy          string
	Descending      bool
	AfterSentAt     pgtype.Timestamptz
	AfterMessageID  string
	AfterSender     string
	AfterSubject    string
	PageSize        int32
}

type SearchPageRow struct {
	MessageID            string
	ThreadID             string
	FromEmail            string
	FromName             pgtype.Text
	Subject              pgtype.Text
	SentAt               pgtype.Timestamptz
	Labels               []string
	Flags                []byte
	HasAttachments       bool
	ContentFlags         []string
	ScanState            string
	AttachmentMediaTypes []string
	AttachmentExtensions []string
}

// One page of the messages the query selects, in the order sort_by and descending name, after the
// position a cursor names or from the start when it names none. Ties within one sort value are
// broken by the message identifier, ascending, so the order is total.
func (q *Queries) SearchPage(ctx context.Context, arg SearchPageParams) ([]SearchPageRow, error) {
	rows, err := q.db.Query(ctx, searchPage,
		arg.AccountID,
		arg.After,
		arg.Before,
		arg.FromEmails,
		arg.FromDomains,
		arg.Labels,
		arg.ExcludedLabels,
		arg.LabelsWithin,
		arg.SubjectPatterns,
		arg.Unread,
		arg.Starred,
		arg.HasAttachments,
		arg.Restricted,
		arg.NormalDomains,
		arg.FirstPage,
		arg.SortBy,
		arg.Descending,
		arg.AfterSentAt,
		arg.AfterMessageID,
		arg.AfterSender,
		arg.AfterSubject,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPageRow
	for rows.Next() {
		var i SearchPageRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ThreadID,
			&i.FromEmail,
			&i.FromName,
			&i.Subject,
			&i.SentAt,
			&i.Labels,
			&i.Flags,
			&i.HasAttachments,
			&i.ContentFlags,
			&i.ScanState,
			&i.AttachmentMediaTypes,
			&i.AttachmentExtensions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSummary = `-- name: SearchSummary :one
SELECT
    count(*) AS messages,
    count(DISTINCT m.thread_id) AS threads,
    count(*) FILTER (WHERE NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) AS unread,
    count(*) FILTER (WHERE m.has_attachments) AS with_attachments,
    min(m.sent_at)::timestamptz AS oldest_at,
    max(m.sent_at)::timestamptz AS newest_at
FROM messages AS m
WHERE
    m.account_id = $1
    AND ($2::timestamptz IS NULL OR m.sent_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR m.sent_at < $3::timestamptz)
    AND ($4::citext[] IS NULL OR m.from_email = any($4::citext[]))
    AND ($5::text[] IS NULL OR m.from_domain = any($5::text[]))
    AND ($6::text[] IS NULL OR m.labels @> $6::text[])
    AND ($7::text[] IS NULL OR NOT m.labels && $7::text[])
    AND ($8::text[] IS NULL OR m.labels <@ $8::text[])
    AND ($9::text[] IS NULL OR m.subject ILIKE all($9::text[]))
    AND (
        $10::boolean[] IS NULL
        OR (NOT coalesce((m.flags ->> 'read')::boolean, FALSE)) = any($10::boolean[])
    )
    AND (
        $11::boolean[] IS NULL
        OR coalesce((m.flags ->> 'starred')::boolean, FALSE) = any($11::boolean[])
    )
    AND ($12::boolean[] IS NULL OR m.has_attachments = any($12::boolean[]))
    AND (
        $13::boolean[] IS NULL
        OR (
            NOT EXISTS (
                SELECT 1 FROM unnest($14::text[]) AS n (d)
                WHERE n.d = m.from_domain::text
            )
        ) = any($13::boolean[])
    )
`

type SearchSummaryParams struct {
	AccountID       string
	After           pgtype.Timestamptz
	Before          pgtype.Timestamptz
	FromEmails      []string
	FromDomains     []string
	Labels          []string
	ExcludedLabels  []string
	LabelsWithin    []string
	SubjectPatterns []string
	Unread          []bool
	Starred         []bool
	HasAttachments  []bool
	Restricted      []bool
	NormalDomains   []string
}

type SearchSummaryRow struct {
	Messages        int64
	Threads         int64
	Unread          int64
	WithAttachments int64
	OldestAt        pgtype.Timestamptz
	NewestAt        pgtype.Timestamptz
}

// The number of messages the query selects, of their threads, of the unread among them and of those
// with attachments, and the dates of the oldest and the newest. A message whose flags do not say it
// was read counts as unread.
func (q *Queries) SearchSummary(ctx context.Context, arg SearchSummaryParams) (SearchSummaryRow, error) {
	row := q.db.QueryRow(ctx, searchSummary,
		arg.AccountID,
		arg.After,
		arg.Before,
		arg.FromEmails,
		arg.FromDomains,
		arg.Labels,
		arg.ExcludedLabels,
		arg.LabelsWithin,
		arg.SubjectPatterns,
		arg.Unread,
		arg.Starred,
		arg.HasAttachments,
		arg.Restricted,
		arg.NormalDomains,
	)
	var i SearchSummaryRow
	err := row.Scan(
		&i.Messages,
		&i.Threads,
		&i.Unread,
		&i.WithAttachments,
		&i.OldestAt,
		&i.NewestAt,
	)
	return i, err
}
