// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package change

import (
	"context"
)

type Querier interface {
	// Sets a stored message's labels and flags to the ones the provider reports, which delta sync applies
	// for a message the change feed names (ADR-0018). A message that already carries them is left as it
	// is and counts no row, so a change applied twice changes nothing the second time.
	ApplyLabelsAndFlags(ctx context.Context, arg ApplyLabelsAndFlagsParams) (int64, error)
	// Removes the statistics of the account's sender at domain once the index stores none of its
	// messages, after delta sync removed its last one, since rebuilding them from no messages writes
	// nothing (ADR-0016).
	DropEmptySender(ctx context.Context, arg DropEmptySenderParams) (int64, error)
	// The identifiers of the account's stored messages dated at or after since, which a gap recovery
	// compares with what its listing of the window returned, to find a message removed during the gap
	// (ADR-0105).
	MessagesSince(ctx context.Context, arg MessagesSinceParams) ([]string, error)
	// Removes from the index each of the given messages the change feed reports the provider no longer
	// holds, so the index tracks the live mailbox (ADR-0018). It returns each removed message's sender
	// domain, whose statistics the caller rebuilds. A message the index does not hold is no row.
	RemoveMessages(ctx context.Context, arg RemoveMessagesParams) ([]string, error)
}

var _ Querier = (*Queries)(nil)
