// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actions.sql

package auditlog

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditActionCounts = `-- name: AuditActionCounts :many
SELECT
    a.action,
    count(*) AS entries
FROM audit_log AS a
WHERE a.account_id = $1 AND a.ts >= $2
GROUP BY a.action
ORDER BY a.action
`

type AuditActionCountsParams struct {
	AccountID string
	Since     pgtype.Timestamptz
}

type AuditActionCountsRow struct {
	Action  string
	Entries int64
}

// The audit rows written since a time, counted per action, for the system endpoint's corpus block
// (docs/UI.md section 8.1). An action with no row has no count.
func (q *Queries) AuditActionCounts(ctx context.Context, arg AuditActionCountsParams) ([]AuditActionCountsRow, error) {
	rows, err := q.db.Query(ctx, auditActionCounts, arg.AccountID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditActionCountsRow
	for rows.Next() {
		var i AuditActionCountsRow
		if err := rows.Scan(&i.Action, &i.Entries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
