// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package auditlog

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const messageAuditCount = `-- name: MessageAuditCount :one
SELECT count(*) AS entries
FROM audit_log AS a
WHERE a.account_id = $1 AND a.message_id = $2
`

type MessageAuditCountParams struct {
	AccountID string
	MessageID pgtype.Text
}

// How many audit rows one message has, beside the newest fifty a row detail lists.
func (q *Queries) MessageAuditCount(ctx context.Context, arg MessageAuditCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, messageAuditCount, arg.AccountID, arg.MessageID)
	var entries int64
	err := row.Scan(&entries)
	return entries, err
}

const messageAuditRows = `-- name: MessageAuditRows :many
SELECT
    a.id,
    a.ts,
    a.actor,
    a.action
FROM audit_log AS a
WHERE a.account_id = $1 AND a.message_id = $2
ORDER BY a.ts DESC, a.id DESC
LIMIT 50
`

type MessageAuditRowsParams struct {
	AccountID string
	MessageID pgtype.Text
}

type MessageAuditRowsRow struct {
	ID     int64
	Ts     pgtype.Timestamptz
	Actor  string
	Action string
}

// The newest fifty audit rows of one message, which a row detail lists (docs/UI.md sections 7.1 and
// 17.1), newest first, the row's identity ending the sort.
func (q *Queries) MessageAuditRows(ctx context.Context, arg MessageAuditRowsParams) ([]MessageAuditRowsRow, error) {
	rows, err := q.db.Query(ctx, messageAuditRows, arg.AccountID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAuditRowsRow
	for rows.Next() {
		var i MessageAuditRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Actor,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
