// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditlog

import (
	"context"
)

type Querier interface {
	// The audit rows written since a time, counted per action, for the system endpoint's corpus block
	// (docs/UI.md section 8.1). An action with no row has no count.
	AuditActionCounts(ctx context.Context, arg AuditActionCountsParams) ([]AuditActionCountsRow, error)
}

var _ Querier = (*Queries)(nil)
