// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: serves.sql

package auditlog

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bodyServesByDay = `-- name: BodyServesByDay :many
SELECT
    (a.ts AT TIME ZONE 'UTC')::date AS day,
    count(*) AS serves
FROM audit_log AS a
WHERE
    a.account_id = $1
    AND a.action = 'READ_BODY'
    AND a.ts >= $2
    AND a.ts < $3
GROUP BY day
ORDER BY day
`

type BodyServesByDayParams struct {
	AccountID  string
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
}

type BodyServesByDayRow struct {
	Day    pgtype.Date
	Serves int64
}

// The bodies served on each UTC day from one time up to another, one row per day that has a serve, the
// daily counts the body-serve rule takes its median of (docs/UI.md section 8.1).
func (q *Queries) BodyServesByDay(ctx context.Context, arg BodyServesByDayParams) ([]BodyServesByDayRow, error) {
	rows, err := q.db.Query(ctx, bodyServesByDay, arg.AccountID, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BodyServesByDayRow
	for rows.Next() {
		var i BodyServesByDayRow
		if err := rows.Scan(&i.Day, &i.Serves); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bodyServesSince = `-- name: BodyServesSince :one
SELECT
    count(*) AS serves,
    min(a.ts)::timestamptz AS first_at
FROM audit_log AS a
WHERE a.account_id = $1 AND a.action = 'READ_BODY' AND a.ts >= $2
`

type BodyServesSinceParams struct {
	AccountID string
	Since     pgtype.Timestamptz
}

type BodyServesSinceRow struct {
	Serves  int64
	FirstAt pgtype.Timestamptz
}

// How many bodies were served since a time and when the first of them was, for the body-serve rule of
// Home's worth-a-look cards (docs/UI.md section 8.1). A denial is not a serve.
func (q *Queries) BodyServesSince(ctx context.Context, arg BodyServesSinceParams) (BodyServesSinceRow, error) {
	row := q.db.QueryRow(ctx, bodyServesSince, arg.AccountID, arg.Since)
	var i BodyServesSinceRow
	err := row.Scan(&i.Serves, &i.FirstAt)
	return i, err
}
