// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package secret

import (
	"context"
)

type Querier interface {
	// Writes a provider's re-sealed client secret only if the stored bytes are still the ones delta sync
	// last read, so a client the operator set up again is never put back (ADR-0089, ADR-0092). A write
	// that finds other bytes changes no row.
	ReplaceSealedClient(ctx context.Context, arg ReplaceSealedClientParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
