// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clock.sql

package ratestate

import (
	"context"
)

const clockMillis = `-- name: ClockMillis :one
SELECT floor(extract(EPOCH FROM clock_timestamp()) * 1000)::bigint AS now_ms
`

// The database's clock in Unix milliseconds. It is read in its own statement after the lock is held,
// because now() is fixed when the transaction starts and a worker that waited on the lock would stamp
// its lease early (ADR-0025).
func (q *Queries) ClockMillis(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, clockMillis)
	var now_ms int64
	err := row.Scan(&now_ms)
	return now_ms, err
}
