// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package ratestate

import (
	"context"
)

const clampGrants = `-- name: ClampGrants :exec
UPDATE rate_grants
SET issued_at = timestamptz 'epoch' + ($1::bigint) * interval '1 millisecond'
WHERE
    account_id = $2
    AND issued_at > timestamptz 'epoch' + ($1::bigint) * interval '1 millisecond'
`

type ClampGrantsParams struct {
	NowMs     int64
	AccountID string
}

// Moves a grant stamped later than the instant issuance has reached back to that instant, as the rules
// take it (ratelimit/core). It then counts for one second from there, rather than for as long as its
// stamp lies ahead.
func (q *Queries) ClampGrants(ctx context.Context, arg ClampGrantsParams) error {
	_, err := q.db.Exec(ctx, clampGrants, arg.NowMs, arg.AccountID)
	return err
}

const deleteGrantsBefore = `-- name: DeleteGrantsBefore :exec
DELETE FROM rate_grants
WHERE
    account_id = $1
    AND issued_at <= timestamptz 'epoch' + ($2::bigint) * interval '1 millisecond'
`

type DeleteGrantsBeforeParams struct {
	AccountID string
	CutoffMs  int64
}

// Deletes the grants issued at or before the cutoff, one second before the clock the issuer read.
func (q *Queries) DeleteGrantsBefore(ctx context.Context, arg DeleteGrantsBeforeParams) error {
	_, err := q.db.Exec(ctx, deleteGrantsBefore, arg.AccountID, arg.CutoffMs)
	return err
}

const grants = `-- name: Grants :many
SELECT
    class,
    tokens,
    floor(extract(EPOCH FROM issued_at) * 1000)::bigint AS issued_ms
FROM rate_grants
WHERE account_id = $1
`

type GrantsRow struct {
	Class    string
	Tokens   float32
	IssuedMs int64
}

// Every grant the account holds a row for, which the issuer keeps to the last second.
func (q *Queries) Grants(ctx context.Context, accountID string) ([]GrantsRow, error) {
	rows, err := q.db.Query(ctx, grants, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrantsRow
	for rows.Next() {
		var i GrantsRow
		if err := rows.Scan(&i.Class, &i.Tokens, &i.IssuedMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO rate_grants (account_id, class, tokens, issued_at)
VALUES ($1, $2, $3, timestamptz 'epoch' + ($4::bigint) * interval '1 millisecond')
`

type InsertGrantParams struct {
	AccountID string
	Class     string
	Tokens    float32
	IssuedMs  int64
}

func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.Exec(ctx, insertGrant,
		arg.AccountID,
		arg.Class,
		arg.Tokens,
		arg.IssuedMs,
	)
	return err
}
