// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ratestate

import (
	"context"
)

type Querier interface {
	// The rate state the UI's jobs screen and event stream show, the current rate, the target, the cap,
	// the backoff and the last throttle, and each priority class's reservation and use as the limiter
	// records them (ADR-0024, ADR-0025, docs/UI.md section 8.3).
	RateStatus(ctx context.Context, accountID string) (RateStatusRow, error)
}

var _ Querier = (*Queries)(nil)
