// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate.sql

package ratestate

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const rateStatus = `-- name: RateStatus :one
SELECT
    r.current_rate,
    r.target_rate,
    r.hard_cap,
    r.backoff_until,
    r.last_throttle_at,
    r.classes
FROM rate_state AS r
WHERE r.account_id = $1
`

type RateStatusRow struct {
	CurrentRate    float32
	TargetRate     float32
	HardCap        float32
	BackoffUntil   pgtype.Timestamptz
	LastThrottleAt pgtype.Timestamptz
	Classes        []byte
}

// The rate state the UI's jobs screen and event stream show, the current rate, the target, the cap,
// the backoff and the last throttle, and each priority class's reservation and use as the limiter
// records them (ADR-0024, ADR-0025, docs/UI.md section 8.3).
func (q *Queries) RateStatus(ctx context.Context, accountID string) (RateStatusRow, error) {
	row := q.db.QueryRow(ctx, rateStatus, accountID)
	var i RateStatusRow
	err := row.Scan(
		&i.CurrentRate,
		&i.TargetRate,
		&i.HardCap,
		&i.BackoffUntil,
		&i.LastThrottleAt,
		&i.Classes,
	)
	return i, err
}
