// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: state.sql

package ratestate

import (
	"context"
)

const insertRateState = `-- name: InsertRateState :exec
INSERT INTO rate_state (account_id, current_rate, target_rate, hard_cap)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id) DO NOTHING
`

type InsertRateStateParams struct {
	AccountID   string
	CurrentRate float32
	TargetRate  float32
	HardCap     float32
}

// Gives an account its rate state the first time it spends. An account that already has one keeps it.
func (q *Queries) InsertRateState(ctx context.Context, arg InsertRateStateParams) error {
	_, err := q.db.Exec(ctx, insertRateState,
		arg.AccountID,
		arg.CurrentRate,
		arg.TargetRate,
		arg.HardCap,
	)
	return err
}

const rateState = `-- name: RateState :one
SELECT
    current_rate,
    throttles,
    bucket_level,
    coalesce(floor(extract(EPOCH FROM backoff_until) * 1000), 0)::bigint AS backoff_until_ms,
    coalesce(floor(extract(EPOCH FROM bucket_filled_at) * 1000), 0)::bigint AS bucket_filled_ms,
    coalesce(floor(extract(EPOCH FROM class_asked_at[1]) * 1000), 0)::bigint AS interactive_asked_ms,
    coalesce(floor(extract(EPOCH FROM class_asked_at[2]) * 1000), 0)::bigint AS sync_asked_ms,
    coalesce(floor(extract(EPOCH FROM class_asked_at[3]) * 1000), 0)::bigint AS batch_asked_ms,
    coalesce(floor(extract(EPOCH FROM last_granted_at) * 1000), 0)::bigint AS last_granted_ms,
    coalesce(floor(extract(EPOCH FROM latency_window_start) * 1000), 0)::bigint AS latency_window_start_ms,
    coalesce(latency_samples, '{}')::integer[] AS latency_samples,
    coalesce(latency_medians, '{}')::real[] AS latency_medians
FROM rate_state
WHERE account_id = $1
`

type RateStateRow struct {
	CurrentRate          float32
	Throttles            int32
	BucketLevel          float32
	BackoffUntilMs       int64
	BucketFilledMs       int64
	InteractiveAskedMs   int64
	SyncAskedMs          int64
	BatchAskedMs         int64
	LastGrantedMs        int64
	LatencyWindowStartMs int64
	LatencySamples       []int32
	LatencyMedians       []float32
}

// The rate state the rules decide from, with every instant in Unix milliseconds and zero for an instant
// never set. target_rate, hard_cap, baseline_p50_ms and classes are left out, because they are written
// only for display and the rules recompute them (ADR-0024).
func (q *Queries) RateState(ctx context.Context, accountID string) (RateStateRow, error) {
	row := q.db.QueryRow(ctx, rateState, accountID)
	var i RateStateRow
	err := row.Scan(
		&i.CurrentRate,
		&i.Throttles,
		&i.BucketLevel,
		&i.BackoffUntilMs,
		&i.BucketFilledMs,
		&i.InteractiveAskedMs,
		&i.SyncAskedMs,
		&i.BatchAskedMs,
		&i.LastGrantedMs,
		&i.LatencyWindowStartMs,
		&i.LatencySamples,
		&i.LatencyMedians,
	)
	return i, err
}

const updateController = `-- name: UpdateController :exec
UPDATE rate_state
SET
    current_rate = $1,
    target_rate = $2,
    hard_cap = $3,
    backoff_until = timestamptz 'epoch' + nullif(($4::bigint), 0) * interval '1 millisecond',
    throttles = $5,
    last_throttle_at = coalesce(
        timestamptz 'epoch' + nullif(($6::bigint), 0) * interval '1 millisecond', last_throttle_at
    ),
    latency_window_start
    = timestamptz 'epoch' + nullif(($7::bigint), 0) * interval '1 millisecond',
    latency_samples = $8::integer[],
    latency_medians = $9::real[],
    baseline_p50_ms = nullif($10::real, 0),
    updated_at = timestamptz 'epoch' + ($11::bigint) * interval '1 millisecond'
WHERE account_id = $12
`

type UpdateControllerParams struct {
	CurrentRate          float32
	TargetRate           float32
	HardCap              float32
	BackoffUntilMs       int64
	Throttles            int32
	ThrottledMs          int64
	LatencyWindowStartMs int64
	LatencySamples       []int32
	LatencyMedians       []float32
	BaselineMs           float32
	NowMs                int64
	AccountID            string
}

// Stores the controller's state after a call's outcome. A throttled_ms of zero leaves the latest
// throttle as it was, and a baseline of zero stores none.
func (q *Queries) UpdateController(ctx context.Context, arg UpdateControllerParams) error {
	_, err := q.db.Exec(ctx, updateController,
		arg.CurrentRate,
		arg.TargetRate,
		arg.HardCap,
		arg.BackoffUntilMs,
		arg.Throttles,
		arg.ThrottledMs,
		arg.LatencyWindowStartMs,
		arg.LatencySamples,
		arg.LatencyMedians,
		arg.BaselineMs,
		arg.NowMs,
		arg.AccountID,
	)
	return err
}

const updateIssuance = `-- name: UpdateIssuance :exec
UPDATE rate_state
SET
    target_rate = $1,
    hard_cap = $2,
    bucket_level = $3,
    bucket_filled_at = timestamptz 'epoch' + ($4::bigint) * interval '1 millisecond',
    class_asked_at = ARRAY[
        timestamptz 'epoch' + nullif(($5::bigint), 0) * interval '1 millisecond',
        timestamptz 'epoch' + nullif(($6::bigint), 0) * interval '1 millisecond',
        timestamptz 'epoch' + nullif(($7::bigint), 0) * interval '1 millisecond'
    ],
    last_granted_at = coalesce(
        timestamptz 'epoch' + nullif(($8::bigint), 0) * interval '1 millisecond', last_granted_at
    ),
    classes = $9,
    updated_at = timestamptz 'epoch' + ($10::bigint) * interval '1 millisecond'
WHERE account_id = $11
`

type UpdateIssuanceParams struct {
	TargetRate         float32
	HardCap            float32
	BucketLevel        float32
	BucketFilledMs     int64
	InteractiveAskedMs int64
	SyncAskedMs        int64
	BatchAskedMs       int64
	GrantedMs          int64
	Classes            []byte
	NowMs              int64
	AccountID          string
}

// Stores what issuance keeps after one request, whether or not it was granted. A granted_ms of zero
// leaves the latest grant as it was.
func (q *Queries) UpdateIssuance(ctx context.Context, arg UpdateIssuanceParams) error {
	_, err := q.db.Exec(ctx, updateIssuance,
		arg.TargetRate,
		arg.HardCap,
		arg.BucketLevel,
		arg.BucketFilledMs,
		arg.InteractiveAskedMs,
		arg.SyncAskedMs,
		arg.BatchAskedMs,
		arg.GrantedMs,
		arg.Classes,
		arg.NowMs,
		arg.AccountID,
	)
	return err
}
