// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package maskingsenders

import (
	"context"
)

type Querier interface {
	// Every sender and rule pair with more than a count of masking events since a time, for the masking
	// rule of Home's worth-a-look cards (docs/UI.md section 8.1). An event counts under the domain of its
	// message's sender, which every writer stores in the one form the domain normalizer gives, so each
	// domain has one spelling (ADR-0016), and an event whose message the index no longer holds counts
	// under no pair. Only an event whose scanner version and revision equal those its
	// message's subject was masked under counts, so the events of a masking a change of scanner replaced count
	// under none (ADR-0120, docs/UI.md section 8.5). Each pair carries its first event since the time.
	MaskingPairsAbove(ctx context.Context, arg MaskingPairsAboveParams) ([]MaskingPairsAboveRow, error)
}

var _ Querier = (*Queries)(nil)
