// Generates the dataset descriptor table the browser's URL grammar reads, src/generated/descriptors.ts,
// from the contract document ui/contract/openapi.json (ADR-0065).
//
// The registry declares no dataset yet, so the table is empty. The generated file names the document
// version it was generated from.
//
// Run it from ui/browser. With --check it writes nothing and fails when the checked-in table differs
// from what the document generates, which is the pipeline's third drift check.
//
//   bun scripts/descriptors.ts [--check]

const documentPath = "../contract/openapi.json";
const tablePath = "src/generated/descriptors.ts";

type ContractDocument = {
  openapi: string;
  info: { version: string };
};

export function generate(document: ContractDocument): string {
  return [
    "// Generated by scripts/descriptors.ts from ui/contract/openapi.json. Do not edit.",
    `// Contract document version ${JSON.stringify(document.info.version)}, OpenAPI ${document.openapi}.`,
    "",
    "export const descriptors = {} as const;",
    "",
  ].join("\n");
}

if (import.meta.main) {
  const document: ContractDocument = await Bun.file(documentPath).json();
  const table = generate(document);
  if (process.argv.includes("--check")) {
    const checkedIn = await Bun.file(tablePath)
      .text()
      .catch(() => undefined);
    if (checkedIn !== table) {
      console.error(
        `${tablePath} differs from what ${documentPath} generates. Regenerate with: bun run generate`,
      );
      process.exit(1);
    }
  } else {
    await Bun.write(tablePath, table);
  }
}
