// Generates the dataset descriptor table the browser's URL grammar reads, src/generated/descriptors.ts,
// from the contract document ui/contract/openapi.json (ADR-0065).
//
// The document carries each registry entry's declarative half in the dataset endpoint's x-datasets
// extension, which is the registry's name, parent, range, dimensions and defaults. The table is that
// list keyed by dataset name, so a dataset's defaults, groupable dimensions, filters and sortable
// columns reach the router without a hand edit.
//
// Run it from ui/browser. With --check it writes nothing and fails when the checked-in table differs
// from what the document generates, which is the pipeline's third drift check.
//
//   bun scripts/descriptors.ts [--check]

const documentPath = "../contract/openapi.json";
const tablePath = "src/generated/descriptors.ts";
const lensPath = "/api/{account}/lens";

type Dimension = {
  name: string;
  storage: string;
  groupable: boolean;
  filterable: boolean;
  sortable: boolean;
  wording: string;
  null_wording?: string;
  values?: string[];
};

type Descriptor = {
  name: string;
  parent?: string;
  ranged: boolean;
  range_column?: string;
  dimensions: Dimension[];
  default: {
    group?: string;
    level: number;
    range?: string;
    sort: string;
    filters?: Record<string, string[]>;
  };
};

type ContractDocument = {
  openapi: string;
  info: { version: string };
  paths: Record<string, { get?: { "x-datasets"?: Descriptor[] } }>;
};

export function generate(document: ContractDocument): string {
  const datasets = document.paths[lensPath]?.get?.["x-datasets"];
  if (datasets === undefined) {
    throw new Error(`${documentPath} has no x-datasets on GET ${lensPath}`);
  }
  const table: Record<string, Descriptor> = {};
  for (const dataset of datasets) {
    table[dataset.name] = dataset;
  }
  return [
    "// Generated by scripts/descriptors.ts from ui/contract/openapi.json. Do not edit.",
    `// Contract document version ${JSON.stringify(document.info.version)}, OpenAPI ${document.openapi}.`,
    "",
    `export const descriptors = ${JSON.stringify(table, null, 2)} as const;`,
    "",
  ].join("\n");
}

if (import.meta.main) {
  const document: ContractDocument = await Bun.file(documentPath).json();
  const table = generate(document);
  if (process.argv.includes("--check")) {
    const checkedIn = await Bun.file(tablePath)
      .text()
      .catch(() => undefined);
    if (checkedIn !== table) {
      console.error(
        `${tablePath} differs from what ${documentPath} generates. Regenerate with: bun run generate`,
      );
      process.exit(1);
    }
  } else {
    await Bun.write(tablePath, table);
  }
}
