// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reorgoplog

import (
	"context"
)

type Querier interface {
	// The op log's row count for one of the account's plans, shown beside the rollback that replays it
	// (docs/UI.md section 8.3). The op log carries no account, so the plan scopes it.
	OpLogCount(ctx context.Context, arg OpLogCountParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
