// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package reorgplans

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const planRows = `-- name: PlanRows :many
WITH apply_runs AS (
    SELECT DISTINCT ON (a.plan_id)
        a.plan_id,
        a.run_id,
        a.state
    FROM job_runs AS a
    WHERE a.account_id = $1 AND a.pass = 'apply'
    ORDER BY a.plan_id ASC, a.started_at DESC, a.run_id ASC
),

rollback_runs AS (
    SELECT DISTINCT ON (b.plan_id)
        b.plan_id,
        b.run_id
    FROM job_runs AS b
    WHERE b.account_id = $1 AND b.pass = 'rollback'
    ORDER BY b.plan_id ASC, b.started_at DESC, b.run_id ASC
)

SELECT
    p.plan_id,
    p.description,
    p.status,
    p.proposer,
    p.created_at,
    p.approved_at,
    p.approved_by,
    p.refusal_reason,
    ar.run_id AS apply_run_id,
    ar.state AS apply_run_state,
    rr.run_id AS rollback_run_id,
    (
        SELECT count(*)
        FROM reorg_plan_ops AS o
        WHERE o.account_id = p.account_id AND o.plan_id = p.plan_id
    ) AS messages
FROM reorg_plans AS p
LEFT JOIN apply_runs AS ar ON p.plan_id = ar.plan_id
LEFT JOIN rollback_runs AS rr ON p.plan_id = rr.plan_id
WHERE
    p.account_id = $1
    AND ($2::timestamptz IS NULL OR p.created_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR p.created_at < $3::timestamptz)
    AND ($4::text[] IS NULL OR p.status = any($4::text[]))
    AND ($5::text[] IS NULL OR p.status != all($5::text[]))
ORDER BY
    CASE WHEN $6::boolean THEN p.created_at END DESC,
    p.created_at ASC,
    p.plan_id ASC
LIMIT 50 OFFSET $7
`

type PlanRowsParams struct {
	AccountID  string
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	StatusIn   []string
	StatusOut  []string
	Descending bool
	RowOffset  int32
}

type PlanRowsRow struct {
	PlanID        pgtype.UUID
	Description   pgtype.Text
	Status        string
	Proposer      pgtype.Text
	CreatedAt     pgtype.Timestamptz
	ApprovedAt    pgtype.Timestamptz
	ApprovedBy    pgtype.Text
	RefusalReason pgtype.Text
	ApplyRunID    pgtype.Text
	ApplyRunState pgtype.Text
	RollbackRunID pgtype.Text
	Messages      int64
}

// One page of the plans dataset, fifty rows, under the same filters (docs/UI.md section 8.9). Each
// plan carries its message count, one operation per message (ADR-0020), and the latest apply and
// rollback runs found by their plan reference. created_at is the one sortable column, in either
// direction, and the plan's identity ends the sort.
func (q *Queries) PlanRows(ctx context.Context, arg PlanRowsParams) ([]PlanRowsRow, error) {
	rows, err := q.db.Query(ctx, planRows,
		arg.AccountID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.StatusIn,
		arg.StatusOut,
		arg.Descending,
		arg.RowOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanRowsRow
	for rows.Next() {
		var i PlanRowsRow
		if err := rows.Scan(
			&i.PlanID,
			&i.Description,
			&i.Status,
			&i.Proposer,
			&i.CreatedAt,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.RefusalReason,
			&i.ApplyRunID,
			&i.ApplyRunState,
			&i.RollbackRunID,
			&i.Messages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planStatusCounts = `-- name: PlanStatusCounts :many
SELECT
    p.status,
    count(*) AS plans
FROM reorg_plans AS p
WHERE
    p.account_id = $1
    AND ($2::timestamptz IS NULL OR p.created_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR p.created_at < $3::timestamptz)
    AND ($4::text[] IS NULL OR p.status = any($4::text[]))
    AND ($5::text[] IS NULL OR p.status != all($5::text[]))
GROUP BY p.status
ORDER BY p.status
`

type PlanStatusCountsParams struct {
	AccountID  string
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	StatusIn   []string
	StatusOut  []string
}

type PlanStatusCountsRow struct {
	Status string
	Plans  int64
}

// The plans dataset's figures, the count of plans per status, under the dataset's range and status
// filters (docs/UI.md sections 8.9 and 17.1). A status with no plan has no row. Its total is the sum,
// which the row pages count from. A null range bound is no bound, and a null status array no filter.
func (q *Queries) PlanStatusCounts(ctx context.Context, arg PlanStatusCountsParams) ([]PlanStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, planStatusCounts,
		arg.AccountID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.StatusIn,
		arg.StatusOut,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanStatusCountsRow
	for rows.Next() {
		var i PlanStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Plans); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamPlans = `-- name: StreamPlans :many
SELECT
    p.plan_id,
    p.status,
    (
        SELECT count(*)
        FROM reorg_op_log AS l
        WHERE l.plan_id = p.plan_id
    ) AS applied,
    (
        SELECT count(*)
        FROM reorg_plan_ops AS o
        WHERE o.account_id = p.account_id AND o.plan_id = p.plan_id
    ) AS total
FROM reorg_plans AS p
WHERE
    p.account_id = $1
    AND (p.status = 'APPLYING' OR p.plan_id = any($2::uuid[]))
ORDER BY p.plan_id
`

type StreamPlansParams struct {
	AccountID string
	Known     []pgtype.UUID
}

type StreamPlansRow struct {
	PlanID  pgtype.UUID
	Status  string
	Applied int64
	Total   int64
}

// The plans the event stream follows, every plan applying and each plan it already sent, so a plan
// that leaves APPLYING is sent once more with its new status (ADR-0058). applied counts the op log's
// rows, which the op log scopes through its plan, and total the plan's operations.
func (q *Queries) StreamPlans(ctx context.Context, arg StreamPlansParams) ([]StreamPlansRow, error) {
	rows, err := q.db.Query(ctx, streamPlans, arg.AccountID, arg.Known)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreamPlansRow
	for rows.Next() {
		var i StreamPlansRow
		if err := rows.Scan(
			&i.PlanID,
			&i.Status,
			&i.Applied,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
