// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reorgplans

import (
	"context"
)

type Querier interface {
	// One page of the plans dataset, fifty rows, under the same filters (docs/UI.md section 8.9). Each
	// plan carries its message count, one operation per message (ADR-0020), and the latest apply and
	// rollback runs found by their plan reference. created_at is the one sortable column, in either
	// direction, and the plan's identity ends the sort.
	PlanRows(ctx context.Context, arg PlanRowsParams) ([]PlanRowsRow, error)
	// The plans dataset's figures, the count of plans per status, under the dataset's range and status
	// filters (docs/UI.md sections 8.9 and 17.1). A status with no plan has no row. Its total is the sum,
	// which the row pages count from. A null range bound is no bound, and a null status array no filter.
	PlanStatusCounts(ctx context.Context, arg PlanStatusCountsParams) ([]PlanStatusCountsRow, error)
	// The plans the event stream follows, every plan applying and each plan it already sent, so a plan
	// that leaves APPLYING is sent once more with its new status (ADR-0058). applied counts the op log's
	// rows, which the op log scopes through its plan, and total the plan's operations.
	StreamPlans(ctx context.Context, arg StreamPlansParams) ([]StreamPlansRow, error)
}

var _ Querier = (*Queries)(nil)
