// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lens.sql

package jobruns

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const runFigures = `-- name: RunFigures :one
SELECT
    count(*) AS runs,
    count(*) FILTER (WHERE r.state = 'running') AS running,
    count(*) FILTER (WHERE r.state = 'failed') AS failed,
    max(coalesce(r.finished_at, r.started_at)) FILTER (WHERE r.state = 'failed')::timestamptz AS last_failure_at,
    coalesce((
        array_agg(r.run_id ORDER BY coalesce(r.finished_at, r.started_at) DESC, r.run_id ASC)
        FILTER (WHERE r.state = 'failed')
    )[1], '')::text AS last_failure_run
FROM job_runs AS r
WHERE
    r.account_id = $1
    AND ($2::timestamptz IS NULL OR r.started_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR r.started_at < $3::timestamptz)
    AND ($4::text[] IS NULL OR r.workload = any($4::text[]))
    AND ($5::text[] IS NULL OR r.workload != all($5::text[]))
    AND ($6::text[] IS NULL OR r.state = any($6::text[]))
    AND ($7::text[] IS NULL OR r.state != all($7::text[]))
    AND ($8::text[] IS NULL OR r.pass = any($8::text[]))
    AND ($9::text[] IS NULL OR r.pass IS NULL OR r.pass != all($9::text[]))
    AND ($10::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date = any($10::date[]))
    AND ($11::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date != all($11::date[]))
`

type RunFiguresParams struct {
	AccountID   string
	RangeStart  pgtype.Timestamptz
	RangeEnd    pgtype.Timestamptz
	WorkloadIn  []string
	WorkloadOut []string
	StateIn     []string
	StateOut    []string
	PassIn      []string
	PassOut     []string
	DayIn       []pgtype.Date
	DayOut      []pgtype.Date
}

type RunFiguresRow struct {
	Runs           int64
	Running        int64
	Failed         int64
	LastFailureAt  pgtype.Timestamptz
	LastFailureRun string
}

// The runs dataset's figures under its range and filters (docs/UI.md sections 8.3 and 17.1). runs is
// also the count the row pages count from. The last failure is the latest failed run's finish, or its
// start while it has none, with its identity for the figure's link, empty with no failed run. A null
// range bound is no bound, a null array no filter. Every run records a pass (ADR-0016), so the null
// test in a pass exclusion matches no run, and a day is the UTC date its run started on.
func (q *Queries) RunFigures(ctx context.Context, arg RunFiguresParams) (RunFiguresRow, error) {
	row := q.db.QueryRow(ctx, runFigures,
		arg.AccountID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.WorkloadIn,
		arg.WorkloadOut,
		arg.StateIn,
		arg.StateOut,
		arg.PassIn,
		arg.PassOut,
		arg.DayIn,
		arg.DayOut,
	)
	var i RunFiguresRow
	err := row.Scan(
		&i.Runs,
		&i.Running,
		&i.Failed,
		&i.LastFailureAt,
		&i.LastFailureRun,
	)
	return i, err
}

const runRows = `-- name: RunRows :many
WITH failure_counts AS (
    SELECT
        f.run_id,
        count(*) AS failures
    FROM job_run_failures AS f
    WHERE f.account_id = $1
    GROUP BY f.run_id
)

SELECT
    r.run_id,
    r.workload,
    r.pass,
    r.state,
    r.plan_id,
    pl.description AS plan_description,
    pl.status AS plan_status,
    r.resumed_from,
    r.started_at,
    r.finished_at,
    r.heartbeat_at,
    r.checkpoint,
    r.counters,
    r.last_error,
    coalesce(fc.failures, 0)::bigint AS failures
FROM job_runs AS r
LEFT JOIN reorg_plans AS pl ON r.account_id = pl.account_id AND r.plan_id = pl.plan_id
LEFT JOIN failure_counts AS fc ON r.run_id = fc.run_id
WHERE
    r.account_id = $1
    AND ($2::timestamptz IS NULL OR r.started_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR r.started_at < $3::timestamptz)
    AND ($4::text[] IS NULL OR r.workload = any($4::text[]))
    AND ($5::text[] IS NULL OR r.workload != all($5::text[]))
    AND ($6::text[] IS NULL OR r.state = any($6::text[]))
    AND ($7::text[] IS NULL OR r.state != all($7::text[]))
    AND ($8::text[] IS NULL OR r.pass = any($8::text[]))
    AND ($9::text[] IS NULL OR r.pass IS NULL OR r.pass != all($9::text[]))
    AND ($10::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date = any($10::date[]))
    AND ($11::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date != all($11::date[]))
ORDER BY
    CASE WHEN $12::text = 'started_at' AND $13::boolean THEN r.started_at END DESC,
    CASE WHEN $12::text = 'started_at' AND NOT $13::boolean THEN r.started_at END ASC,
    CASE
        WHEN $12::text = 'duration' AND $13::boolean
            THEN coalesce(r.finished_at, $14::timestamptz) - r.started_at
    END DESC,
    CASE
        WHEN $12::text = 'duration' AND NOT $13::boolean
            THEN coalesce(r.finished_at, $14::timestamptz) - r.started_at
    END ASC,
    CASE WHEN $12::text = 'failures' AND $13::boolean THEN coalesce(fc.failures, 0) END DESC,
    CASE WHEN $12::text = 'failures' AND NOT $13::boolean THEN coalesce(fc.failures, 0) END ASC,
    r.run_id ASC
LIMIT 50 OFFSET $15
`

type RunRowsParams struct {
	AccountID   string
	RangeStart  pgtype.Timestamptz
	RangeEnd    pgtype.Timestamptz
	WorkloadIn  []string
	WorkloadOut []string
	StateIn     []string
	StateOut    []string
	PassIn      []string
	PassOut     []string
	DayIn       []pgtype.Date
	DayOut      []pgtype.Date
	SortColumn  string
	Descending  bool
	AsOf        pgtype.Timestamptz
	RowOffset   int32
}

type RunRowsRow struct {
	RunID           string
	Workload        string
	Pass            string
	State           string
	PlanID          pgtype.UUID
	PlanDescription pgtype.Text
	PlanStatus      pgtype.Text
	ResumedFrom     pgtype.Text
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	HeartbeatAt     pgtype.Timestamptz
	Checkpoint      []byte
	Counters        []byte
	LastError       pgtype.Text
	Failures        int64
}

// One page of the runs dataset, fifty rows, under the same filters (docs/UI.md section 8.3). Each run
// carries its plan's description and status, as the jobs endpoint sends a run, and its count of item
// failures. sort_column names one of the three sortable columns, started_at, duration or failures, in
// either direction, and the run's identity ends the sort. duration runs to the finish, or to as_of
// while the run has none.
func (q *Queries) RunRows(ctx context.Context, arg RunRowsParams) ([]RunRowsRow, error) {
	rows, err := q.db.Query(ctx, runRows,
		arg.AccountID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.WorkloadIn,
		arg.WorkloadOut,
		arg.StateIn,
		arg.StateOut,
		arg.PassIn,
		arg.PassOut,
		arg.DayIn,
		arg.DayOut,
		arg.SortColumn,
		arg.Descending,
		arg.AsOf,
		arg.RowOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunRowsRow
	for rows.Next() {
		var i RunRowsRow
		if err := rows.Scan(
			&i.RunID,
			&i.Workload,
			&i.Pass,
			&i.State,
			&i.PlanID,
			&i.PlanDescription,
			&i.PlanStatus,
			&i.ResumedFrom,
			&i.StartedAt,
			&i.FinishedAt,
			&i.HeartbeatAt,
			&i.Checkpoint,
			&i.Counters,
			&i.LastError,
			&i.Failures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runsByDay = `-- name: RunsByDay :many
SELECT
    (r.started_at AT TIME ZONE 'UTC')::date AS day,
    count(*) AS runs
FROM job_runs AS r
WHERE
    r.account_id = $1
    AND ($2::timestamptz IS NULL OR r.started_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR r.started_at < $3::timestamptz)
    AND ($4::text[] IS NULL OR r.workload = any($4::text[]))
    AND ($5::text[] IS NULL OR r.workload != all($5::text[]))
    AND ($6::text[] IS NULL OR r.state = any($6::text[]))
    AND ($7::text[] IS NULL OR r.state != all($7::text[]))
    AND ($8::text[] IS NULL OR r.pass = any($8::text[]))
    AND ($9::text[] IS NULL OR r.pass IS NULL OR r.pass != all($9::text[]))
    AND ($10::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date = any($10::date[]))
    AND ($11::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date != all($11::date[]))
GROUP BY day
ORDER BY runs DESC, day ASC
`

type RunsByDayParams struct {
	AccountID   string
	RangeStart  pgtype.Timestamptz
	RangeEnd    pgtype.Timestamptz
	WorkloadIn  []string
	WorkloadOut []string
	StateIn     []string
	StateOut    []string
	PassIn      []string
	PassOut     []string
	DayIn       []pgtype.Date
	DayOut      []pgtype.Date
}

type RunsByDayRow struct {
	Day  pgtype.Date
	Runs int64
}

// Every group of the runs dataset by the UTC day each run started on, as RunsByWorkload.
func (q *Queries) RunsByDay(ctx context.Context, arg RunsByDayParams) ([]RunsByDayRow, error) {
	rows, err := q.db.Query(ctx, runsByDay,
		arg.AccountID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.WorkloadIn,
		arg.WorkloadOut,
		arg.StateIn,
		arg.StateOut,
		arg.PassIn,
		arg.PassOut,
		arg.DayIn,
		arg.DayOut,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunsByDayRow
	for rows.Next() {
		var i RunsByDayRow
		if err := rows.Scan(&i.Day, &i.Runs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runsByState = `-- name: RunsByState :many
SELECT
    r.state,
    count(*) AS runs
FROM job_runs AS r
WHERE
    r.account_id = $1
    AND ($2::timestamptz IS NULL OR r.started_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR r.started_at < $3::timestamptz)
    AND ($4::text[] IS NULL OR r.workload = any($4::text[]))
    AND ($5::text[] IS NULL OR r.workload != all($5::text[]))
    AND ($6::text[] IS NULL OR r.state = any($6::text[]))
    AND ($7::text[] IS NULL OR r.state != all($7::text[]))
    AND ($8::text[] IS NULL OR r.pass = any($8::text[]))
    AND ($9::text[] IS NULL OR r.pass IS NULL OR r.pass != all($9::text[]))
    AND ($10::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date = any($10::date[]))
    AND ($11::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date != all($11::date[]))
GROUP BY r.state
ORDER BY runs DESC, r.state ASC
`

type RunsByStateParams struct {
	AccountID   string
	RangeStart  pgtype.Timestamptz
	RangeEnd    pgtype.Timestamptz
	WorkloadIn  []string
	WorkloadOut []string
	StateIn     []string
	StateOut    []string
	PassIn      []string
	PassOut     []string
	DayIn       []pgtype.Date
	DayOut      []pgtype.Date
}

type RunsByStateRow struct {
	State string
	Runs  int64
}

// Every group of the runs dataset by run state, as RunsByWorkload.
func (q *Queries) RunsByState(ctx context.Context, arg RunsByStateParams) ([]RunsByStateRow, error) {
	rows, err := q.db.Query(ctx, runsByState,
		arg.AccountID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.WorkloadIn,
		arg.WorkloadOut,
		arg.StateIn,
		arg.StateOut,
		arg.PassIn,
		arg.PassOut,
		arg.DayIn,
		arg.DayOut,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunsByStateRow
	for rows.Next() {
		var i RunsByStateRow
		if err := rows.Scan(&i.State, &i.Runs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runsByWorkload = `-- name: RunsByWorkload :many
SELECT
    r.workload,
    count(*) AS runs
FROM job_runs AS r
WHERE
    r.account_id = $1
    AND ($2::timestamptz IS NULL OR r.started_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR r.started_at < $3::timestamptz)
    AND ($4::text[] IS NULL OR r.workload = any($4::text[]))
    AND ($5::text[] IS NULL OR r.workload != all($5::text[]))
    AND ($6::text[] IS NULL OR r.state = any($6::text[]))
    AND ($7::text[] IS NULL OR r.state != all($7::text[]))
    AND ($8::text[] IS NULL OR r.pass = any($8::text[]))
    AND ($9::text[] IS NULL OR r.pass IS NULL OR r.pass != all($9::text[]))
    AND ($10::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date = any($10::date[]))
    AND ($11::date[] IS NULL OR (r.started_at AT TIME ZONE 'UTC')::date != all($11::date[]))
GROUP BY r.workload
ORDER BY runs DESC, r.workload ASC
`

type RunsByWorkloadParams struct {
	AccountID   string
	RangeStart  pgtype.Timestamptz
	RangeEnd    pgtype.Timestamptz
	WorkloadIn  []string
	WorkloadOut []string
	StateIn     []string
	StateOut    []string
	PassIn      []string
	PassOut     []string
	DayIn       []pgtype.Date
	DayOut      []pgtype.Date
}

type RunsByWorkloadRow struct {
	Workload string
	Runs     int64
}

// Every group of the runs dataset by workload, under the same filters, ordered by count and then by
// the group's key, the order the bars draw (docs/UI.md section 17.1).
func (q *Queries) RunsByWorkload(ctx context.Context, arg RunsByWorkloadParams) ([]RunsByWorkloadRow, error) {
	rows, err := q.db.Query(ctx, runsByWorkload,
		arg.AccountID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.WorkloadIn,
		arg.WorkloadOut,
		arg.StateIn,
		arg.StateOut,
		arg.PassIn,
		arg.PassOut,
		arg.DayIn,
		arg.DayOut,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunsByWorkloadRow
	for rows.Next() {
		var i RunsByWorkloadRow
		if err := rows.Scan(&i.Workload, &i.Runs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
