// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package jobruns

import (
	"context"
)

type Querier interface {
	// The latest run of one workload and pass whose state is one of the given states. The jobs cards read
	// the last finished run beside a running one, and the system screen the last successful sync tick
	// (docs/UI.md sections 8.3 and 8.8). A null pass matches a workload that records none.
	LatestRunInStates(ctx context.Context, arg LatestRunInStatesParams) (LatestRunInStatesRow, error)
	// The latest run of each workload and pass, which the jobs cards read (docs/UI.md section 8.3). An
	// apply or rollback run carries its plan's description and status, so the card can title the run and
	// say whether rollback is available.
	LatestRuns(ctx context.Context, accountID string) ([]LatestRunsRow, error)
	// The first and last checkpoint page a run's progress events recorded since a time, from which the
	// backfill card estimates the time left (docs/UI.md section 8.1). With no progress event in the window,
	// events is zero and both pages read zero.
	ProgressSince(ctx context.Context, arg ProgressSinceParams) (ProgressSinceRow, error)
	// How many runs of one workload and pass started since a time, the gap recoveries of the last seven
	// days on the delta sync card (docs/UI.md section 8.3).
	RunsStartedSince(ctx context.Context, arg RunsStartedSinceParams) (int64, error)
	// The runs the event stream follows, every run still running and every run that finished since a time
	// (ADR-0058), each with its whole recorded state, the plan an apply or rollback run carries included,
	// the same shape the jobs endpoint sends. The stream sends a run whenever it differs from the last
	// state sent.
	StreamRuns(ctx context.Context, arg StreamRunsParams) ([]StreamRunsRow, error)
}

var _ Querier = (*Queries)(nil)
