// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package jobruns

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const gapRecoveriesSince = `-- name: GapRecoveriesSince :many
SELECT
    r.run_id,
    r.started_at,
    r.finished_at,
    r.counters
FROM job_runs AS r
WHERE
    r.account_id = $1
    AND r.workload = 'sync'
    AND r.pass = 'gap_recovery'
    AND r.state = 'succeeded'
    AND r.started_at >= $2
ORDER BY r.started_at, r.run_id
`

type GapRecoveriesSinceParams struct {
	AccountID string
	Since     pgtype.Timestamptz
}

type GapRecoveriesSinceRow struct {
	RunID      string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Counters   []byte
}

// The delta sync gap recoveries that succeeded and started since a time, oldest first, for the sync-gap
// rule of Home's worth-a-look cards (docs/UI.md section 8.1). Each carries its counters, which record
// the window it re-enumerated and the messages it reconciled (ADR-0016).
func (q *Queries) GapRecoveriesSince(ctx context.Context, arg GapRecoveriesSinceParams) ([]GapRecoveriesSinceRow, error) {
	rows, err := q.db.Query(ctx, gapRecoveriesSince, arg.AccountID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GapRecoveriesSinceRow
	for rows.Next() {
		var i GapRecoveriesSinceRow
		if err := rows.Scan(
			&i.RunID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Counters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestRunInStates = `-- name: LatestRunInStates :one
SELECT
    r.run_id,
    r.workload,
    r.pass,
    r.state,
    r.plan_id,
    pl.description AS plan_description,
    pl.status AS plan_status,
    r.resumed_from,
    r.started_at,
    r.finished_at,
    r.heartbeat_at,
    r.checkpoint,
    r.counters,
    r.last_error
FROM job_runs AS r
LEFT JOIN reorg_plans AS pl ON r.account_id = pl.account_id AND r.plan_id = pl.plan_id
WHERE
    r.account_id = $1
    AND r.workload = $2
    AND r.pass = $3
    AND r.state = any($4::text[])
ORDER BY r.started_at DESC, r.run_id ASC
LIMIT 1
`

type LatestRunInStatesParams struct {
	AccountID string
	Workload  string
	Pass      string
	States    []string
}

type LatestRunInStatesRow struct {
	RunID           string
	Workload        string
	Pass            string
	State           string
	PlanID          pgtype.UUID
	PlanDescription pgtype.Text
	PlanStatus      pgtype.Text
	ResumedFrom     pgtype.Text
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	HeartbeatAt     pgtype.Timestamptz
	Checkpoint      []byte
	Counters        []byte
	LastError       pgtype.Text
}

// The latest run of one workload and pass whose state is one of the given states. The jobs cards read
// the last finished run beside a running one, and the system screen the last successful sync tick
// (docs/UI.md sections 8.3 and 8.8).
func (q *Queries) LatestRunInStates(ctx context.Context, arg LatestRunInStatesParams) (LatestRunInStatesRow, error) {
	row := q.db.QueryRow(ctx, latestRunInStates,
		arg.AccountID,
		arg.Workload,
		arg.Pass,
		arg.States,
	)
	var i LatestRunInStatesRow
	err := row.Scan(
		&i.RunID,
		&i.Workload,
		&i.Pass,
		&i.State,
		&i.PlanID,
		&i.PlanDescription,
		&i.PlanStatus,
		&i.ResumedFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
		&i.Checkpoint,
		&i.Counters,
		&i.LastError,
	)
	return i, err
}

const latestRuns = `-- name: LatestRuns :many
SELECT
    l.run_id,
    l.workload,
    l.pass,
    l.state,
    l.plan_id,
    l.plan_description,
    l.plan_status,
    l.resumed_from,
    l.started_at,
    l.finished_at,
    l.heartbeat_at,
    l.checkpoint,
    l.counters,
    l.last_error
FROM (
    SELECT
        unnest($1::text[]) AS workload,
        unnest($2::text[]) AS pass
) AS k
CROSS JOIN
    LATERAL (
        SELECT
            r.run_id,
            r.workload,
            r.pass,
            r.state,
            r.plan_id,
            pl.description AS plan_description,
            pl.status AS plan_status,
            r.resumed_from,
            r.started_at,
            r.finished_at,
            r.heartbeat_at,
            r.checkpoint,
            r.counters,
            r.last_error
        FROM job_runs AS r
        LEFT JOIN reorg_plans AS pl ON r.account_id = pl.account_id AND r.plan_id = pl.plan_id
        WHERE r.account_id = $3 AND r.workload = k.workload AND r.pass = k.pass
        ORDER BY r.started_at DESC, r.run_id ASC
        LIMIT 1
    ) AS l
ORDER BY l.workload ASC, l.pass ASC
`

type LatestRunsParams struct {
	Workloads []string
	Passes    []string
	AccountID string
}

type LatestRunsRow struct {
	RunID           string
	Workload        string
	Pass            string
	State           string
	PlanID          pgtype.UUID
	PlanDescription pgtype.Text
	PlanStatus      pgtype.Text
	ResumedFrom     pgtype.Text
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	HeartbeatAt     pgtype.Timestamptz
	Checkpoint      []byte
	Counters        []byte
	LastError       pgtype.Text
}

// The latest run of each workload and pass the caller names, which the jobs cards read (docs/UI.md
// section 8.3). The pairs are the closed set the schema's check on job_runs holds, given as two arrays
// of one length read in step. Each pair is one lookup on the run index, newest first, and a pair with
// no run has no row. An apply or rollback run carries its plan's description and status, so the card
// can title the run and say whether rollback is available.
func (q *Queries) LatestRuns(ctx context.Context, arg LatestRunsParams) ([]LatestRunsRow, error) {
	rows, err := q.db.Query(ctx, latestRuns, arg.Workloads, arg.Passes, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestRunsRow
	for rows.Next() {
		var i LatestRunsRow
		if err := rows.Scan(
			&i.RunID,
			&i.Workload,
			&i.Pass,
			&i.State,
			&i.PlanID,
			&i.PlanDescription,
			&i.PlanStatus,
			&i.ResumedFrom,
			&i.StartedAt,
			&i.FinishedAt,
			&i.HeartbeatAt,
			&i.Checkpoint,
			&i.Counters,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const progressSince = `-- name: ProgressSince :one
SELECT
    count(e.page) AS events,
    coalesce(min(e.page), 0)::integer AS first_page,
    coalesce(max(e.page), 0)::integer AS last_page
FROM job_run_events AS e
WHERE
    e.account_id = $1
    AND e.run_id = $2
    AND e.kind = 'progress'
    AND e.at >= $3
`

type ProgressSinceParams struct {
	AccountID string
	RunID     string
	Since     pgtype.Timestamptz
}

type ProgressSinceRow struct {
	Events    int64
	FirstPage int32
	LastPage  int32
}

// The first and last checkpoint page a run's progress events recorded since a time, from which the
// backfill card estimates the time left (docs/UI.md section 8.1). With no progress event in the window,
// events is zero and both pages read zero.
func (q *Queries) ProgressSince(ctx context.Context, arg ProgressSinceParams) (ProgressSinceRow, error) {
	row := q.db.QueryRow(ctx, progressSince, arg.AccountID, arg.RunID, arg.Since)
	var i ProgressSinceRow
	err := row.Scan(&i.Events, &i.FirstPage, &i.LastPage)
	return i, err
}

const runsStartedSince = `-- name: RunsStartedSince :one
SELECT count(*) AS runs
FROM job_runs AS r
WHERE
    r.account_id = $1
    AND r.workload = $2
    AND r.pass = $3
    AND r.started_at >= $4
`

type RunsStartedSinceParams struct {
	AccountID string
	Workload  string
	Pass      string
	Since     pgtype.Timestamptz
}

// How many runs of one workload and pass started since a time, the gap recoveries of the last seven
// days on the delta sync card (docs/UI.md section 8.3).
func (q *Queries) RunsStartedSince(ctx context.Context, arg RunsStartedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, runsStartedSince,
		arg.AccountID,
		arg.Workload,
		arg.Pass,
		arg.Since,
	)
	var runs int64
	err := row.Scan(&runs)
	return runs, err
}

const streamRuns = `-- name: StreamRuns :many
SELECT
    r.run_id,
    r.workload,
    r.pass,
    r.state,
    r.plan_id,
    pl.description AS plan_description,
    pl.status AS plan_status,
    r.resumed_from,
    r.started_at,
    r.finished_at,
    r.heartbeat_at,
    r.checkpoint,
    r.counters,
    r.last_error
FROM job_runs AS r
LEFT JOIN reorg_plans AS pl ON r.account_id = pl.account_id AND r.plan_id = pl.plan_id
WHERE
    r.account_id = $1
    AND (r.state = 'running' OR r.finished_at >= $2)
ORDER BY r.started_at ASC, r.run_id ASC
`

type StreamRunsParams struct {
	AccountID string
	Since     pgtype.Timestamptz
}

type StreamRunsRow struct {
	RunID           string
	Workload        string
	Pass            string
	State           string
	PlanID          pgtype.UUID
	PlanDescription pgtype.Text
	PlanStatus      pgtype.Text
	ResumedFrom     pgtype.Text
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	HeartbeatAt     pgtype.Timestamptz
	Checkpoint      []byte
	Counters        []byte
	LastError       pgtype.Text
}

// The runs the event stream follows, every run still running and every run that finished since a time
// (ADR-0058), each with its whole recorded state, the plan an apply or rollback run carries included,
// the same shape the jobs endpoint sends. The stream sends a run whenever it differs from the last
// state sent.
func (q *Queries) StreamRuns(ctx context.Context, arg StreamRunsParams) ([]StreamRunsRow, error) {
	rows, err := q.db.Query(ctx, streamRuns, arg.AccountID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreamRunsRow
	for rows.Next() {
		var i StreamRunsRow
		if err := rows.Scan(
			&i.RunID,
			&i.Workload,
			&i.Pass,
			&i.State,
			&i.PlanID,
			&i.PlanDescription,
			&i.PlanStatus,
			&i.ResumedFrom,
			&i.StartedAt,
			&i.FinishedAt,
			&i.HeartbeatAt,
			&i.Checkpoint,
			&i.Counters,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
