// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summary.sql

package jobruns

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const failureDispositions = `-- name: FailureDispositions :many
SELECT
    f.disposition,
    count(*) AS failures
FROM job_run_failures AS f
WHERE f.account_id = $1 AND f.run_id = $2
GROUP BY f.disposition
ORDER BY f.disposition
`

type FailureDispositionsParams struct {
	AccountID string
	RunID     string
}

type FailureDispositionsRow struct {
	Disposition string
	Failures    int64
}

// A run's item failures counted per disposition, for the run summary's L0 (docs/UI.md section 8.4). A
// disposition with no failure has no row.
func (q *Queries) FailureDispositions(ctx context.Context, arg FailureDispositionsParams) ([]FailureDispositionsRow, error) {
	rows, err := q.db.Query(ctx, failureDispositions, arg.AccountID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailureDispositionsRow
	for rows.Next() {
		var i FailureDispositionsRow
		if err := rows.Scan(&i.Disposition, &i.Failures); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestResumer = `-- name: LatestResumer :one
SELECT
    r.run_id,
    r.workload,
    r.pass,
    r.state,
    r.plan_id,
    pl.description AS plan_description,
    pl.status AS plan_status,
    r.resumed_from,
    r.started_at,
    r.finished_at,
    r.heartbeat_at,
    r.checkpoint,
    r.counters,
    r.last_error
FROM job_runs AS r
LEFT JOIN reorg_plans AS pl ON r.account_id = pl.account_id AND r.plan_id = pl.plan_id
WHERE r.account_id = $1 AND r.resumed_from = $2
ORDER BY r.started_at DESC, r.run_id ASC
LIMIT 1
`

type LatestResumerParams struct {
	AccountID string
	RunID     pgtype.Text
}

type LatestResumerRow struct {
	RunID           string
	Workload        string
	Pass            string
	State           string
	PlanID          pgtype.UUID
	PlanDescription pgtype.Text
	PlanStatus      pgtype.Text
	ResumedFrom     pgtype.Text
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	HeartbeatAt     pgtype.Timestamptz
	Checkpoint      []byte
	Counters        []byte
	LastError       pgtype.Text
}

// The latest run whose resumed_from names a run, the run summary's resumer (docs/UI.md section 8.4).
func (q *Queries) LatestResumer(ctx context.Context, arg LatestResumerParams) (LatestResumerRow, error) {
	row := q.db.QueryRow(ctx, latestResumer, arg.AccountID, arg.RunID)
	var i LatestResumerRow
	err := row.Scan(
		&i.RunID,
		&i.Workload,
		&i.Pass,
		&i.State,
		&i.PlanID,
		&i.PlanDescription,
		&i.PlanStatus,
		&i.ResumedFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
		&i.Checkpoint,
		&i.Counters,
		&i.LastError,
	)
	return i, err
}

const recoveringRuns = `-- name: RecoveringRuns :many
SELECT
    f.recovered_by,
    count(*) AS recovered
FROM job_run_failures AS f
WHERE f.account_id = $1 AND f.run_id = $2 AND f.recovered_by IS NOT NULL
GROUP BY f.recovered_by
ORDER BY f.recovered_by
`

type RecoveringRunsParams struct {
	AccountID string
	RunID     string
}

type RecoveringRunsRow struct {
	RecoveredBy pgtype.Text
	Recovered   int64
}

// The runs that recovered a run's items, each with how many it recovered, for the run summary's L0
// (docs/UI.md section 8.4).
func (q *Queries) RecoveringRuns(ctx context.Context, arg RecoveringRunsParams) ([]RecoveringRunsRow, error) {
	rows, err := q.db.Query(ctx, recoveringRuns, arg.AccountID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecoveringRunsRow
	for rows.Next() {
		var i RecoveringRunsRow
		if err := rows.Scan(&i.RecoveredBy, &i.Recovered); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runByID = `-- name: RunByID :one
SELECT
    r.run_id,
    r.workload,
    r.pass,
    r.state,
    r.plan_id,
    pl.description AS plan_description,
    pl.status AS plan_status,
    r.resumed_from,
    r.started_at,
    r.finished_at,
    r.heartbeat_at,
    r.checkpoint,
    r.counters,
    r.last_error
FROM job_runs AS r
LEFT JOIN reorg_plans AS pl ON r.account_id = pl.account_id AND r.plan_id = pl.plan_id
WHERE r.account_id = $1 AND r.run_id = $2
`

type RunByIDParams struct {
	AccountID string
	RunID     string
}

type RunByIDRow struct {
	RunID           string
	Workload        string
	Pass            string
	State           string
	PlanID          pgtype.UUID
	PlanDescription pgtype.Text
	PlanStatus      pgtype.Text
	ResumedFrom     pgtype.Text
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	HeartbeatAt     pgtype.Timestamptz
	Checkpoint      []byte
	Counters        []byte
	LastError       pgtype.Text
}

// One run with its plan's description and status, the run summary endpoint's run (docs/UI.md section
// 17.4), in the shape the jobs endpoint sends a run.
func (q *Queries) RunByID(ctx context.Context, arg RunByIDParams) (RunByIDRow, error) {
	row := q.db.QueryRow(ctx, runByID, arg.AccountID, arg.RunID)
	var i RunByIDRow
	err := row.Scan(
		&i.RunID,
		&i.Workload,
		&i.Pass,
		&i.State,
		&i.PlanID,
		&i.PlanDescription,
		&i.PlanStatus,
		&i.ResumedFrom,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HeartbeatAt,
		&i.Checkpoint,
		&i.Counters,
		&i.LastError,
	)
	return i, err
}

const runEvents = `-- name: RunEvents :many
SELECT
    e.kind,
    e.at,
    e.page,
    e.detail
FROM job_run_events AS e
WHERE e.account_id = $1 AND e.run_id = $2
ORDER BY e.at ASC, e.seq ASC
`

type RunEventsParams struct {
	AccountID string
	RunID     string
}

type RunEventsRow struct {
	Kind   string
	At     pgtype.Timestamptz
	Page   pgtype.Int4
	Detail pgtype.Text
}

// Every event of a run's timeline in the order recorded, which the run timeline draws (docs/UI.md
// sections 7.3 and 8.4).
func (q *Queries) RunEvents(ctx context.Context, arg RunEventsParams) ([]RunEventsRow, error) {
	rows, err := q.db.Query(ctx, runEvents, arg.AccountID, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunEventsRow
	for rows.Next() {
		var i RunEventsRow
		if err := rows.Scan(
			&i.Kind,
			&i.At,
			&i.Page,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
