// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticks.sql

package jobruns

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lastSucceededTick = `-- name: LastSucceededTick :one
SELECT max(r.finished_at)::timestamptz AS finished_at
FROM job_runs AS r
WHERE
    r.account_id = $1
    AND r.workload = 'sync'
    AND r.pass = 'tick'
    AND r.state = 'succeeded'
`

// When the account's latest delta sync tick that succeeded finished, null when none has (ADR-0034).
func (q *Queries) LastSucceededTick(ctx context.Context, accountID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, lastSucceededTick, accountID)
	var finished_at pgtype.Timestamptz
	err := row.Scan(&finished_at)
	return finished_at, err
}
