// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package policycandidates

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const candidateRows = `-- name: CandidateRows :many
SELECT
    c.domain,
    c.score,
    c.signals,
    c.status,
    c.created_at,
    c.reviewed_at,
    c.reviewed_by,
    s.message_count,
    s.first_seen
FROM policy_candidates AS c
LEFT JOIN senders AS s ON c.account_id = s.account_id AND c.domain = s.domain
WHERE
    c.account_id = $1
    AND ($2::timestamptz IS NULL OR c.created_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR c.created_at < $3::timestamptz)
    AND ($4::text[] IS NULL OR c.status = any($4::text[]))
    AND ($5::text[] IS NULL OR c.status != all($5::text[]))
ORDER BY
    CASE WHEN $6::boolean AND $7::boolean THEN c.score END DESC,
    CASE WHEN $6::boolean AND NOT $7::boolean THEN c.score END ASC,
    CASE WHEN NOT $6::boolean AND $7::boolean THEN c.created_at END DESC,
    CASE WHEN NOT $6::boolean AND NOT $7::boolean THEN c.created_at END ASC,
    c.domain ASC
LIMIT 50 OFFSET $8
`

type CandidateRowsParams struct {
	AccountID  string
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	StatusIn   []string
	StatusOut  []string
	SortScore  bool
	Descending bool
	RowOffset  int32
}

type CandidateRowsRow struct {
	Domain       string
	Score        float32
	Signals      []byte
	Status       string
	CreatedAt    pgtype.Timestamptz
	ReviewedAt   pgtype.Timestamptz
	ReviewedBy   pgtype.Text
	MessageCount pgtype.Int8
	FirstSeen    pgtype.Timestamptz
}

// One page of the candidates dataset, fifty rows, under the same filters, each with its sender's
// message count and first-seen time from the sender statistics (docs/UI.md section 8.6). The sortable
// columns are score and created_at, in either direction, and the candidate's domain ends the sort.
func (q *Queries) CandidateRows(ctx context.Context, arg CandidateRowsParams) ([]CandidateRowsRow, error) {
	rows, err := q.db.Query(ctx, candidateRows,
		arg.AccountID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.StatusIn,
		arg.StatusOut,
		arg.SortScore,
		arg.Descending,
		arg.RowOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateRowsRow
	for rows.Next() {
		var i CandidateRowsRow
		if err := rows.Scan(
			&i.Domain,
			&i.Score,
			&i.Signals,
			&i.Status,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.MessageCount,
			&i.FirstSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const candidateStatusCounts = `-- name: CandidateStatusCounts :many
SELECT
    c.status,
    count(*) AS candidates
FROM policy_candidates AS c
WHERE
    c.account_id = $1
    AND ($2::timestamptz IS NULL OR c.created_at >= $2::timestamptz)
    AND ($3::timestamptz IS NULL OR c.created_at < $3::timestamptz)
    AND ($4::text[] IS NULL OR c.status = any($4::text[]))
    AND ($5::text[] IS NULL OR c.status != all($5::text[]))
GROUP BY c.status
ORDER BY c.status
`

type CandidateStatusCountsParams struct {
	AccountID  string
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
	StatusIn   []string
	StatusOut  []string
}

type CandidateStatusCountsRow struct {
	Status     string
	Candidates int64
}

// The candidates dataset's figures, the count of candidates per status, under the dataset's range and
// status filters (docs/UI.md sections 8.6 and 17.1). A status with no candidate has no row. A null
// range bound is no bound, and a null status array no filter.
func (q *Queries) CandidateStatusCounts(ctx context.Context, arg CandidateStatusCountsParams) ([]CandidateStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, candidateStatusCounts,
		arg.AccountID,
		arg.RangeStart,
		arg.RangeEnd,
		arg.StatusIn,
		arg.StatusOut,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateStatusCountsRow
	for rows.Next() {
		var i CandidateStatusCountsRow
		if err := rows.Scan(&i.Status, &i.Candidates); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
