// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package policycandidates

import (
	"context"
)

type Querier interface {
	// One page of the candidates dataset, fifty rows, under the same filters, each with its sender's
	// message count and first-seen time from the sender statistics (docs/UI.md section 8.6). The sortable
	// columns are score and created_at, in either direction, and the candidate's domain ends the sort.
	CandidateRows(ctx context.Context, arg CandidateRowsParams) ([]CandidateRowsRow, error)
	// The candidates dataset's figures, the count of candidates per status, under the dataset's range and
	// status filters (docs/UI.md sections 8.6 and 17.1). A status with no candidate has no row. A null
	// range bound is no bound, and a null status array no filter.
	CandidateStatusCounts(ctx context.Context, arg CandidateStatusCountsParams) ([]CandidateStatusCountsRow, error)
}

var _ Querier = (*Queries)(nil)
