// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package record

import (
	"context"
)

type Querier interface {
	// Records one body request's decision, a serve as READ_BODY and a denial as DENY_BODY, with the
	// sensitivity it was decided under and the rules that decided it, and never any of the body's text
	// (ADR-0002, ADR-0016). The audit log is append-only, so this is the only write it takes.
	RecordBodyDecision(ctx context.Context, arg RecordBodyDecisionParams) error
}

var _ Querier = (*Queries)(nil)
