// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record.sql

package auditrecord

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordBodyDecision = `-- name: RecordBodyDecision :exec
INSERT INTO audit_log (account_id, actor, action, message_id, sensitivity, rule_ids)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordBodyDecisionParams struct {
	AccountID   string
	Actor       string
	Action      string
	MessageID   pgtype.Text
	Sensitivity []byte
	RuleIds     []string
}

// Records one body request's decision, a serve as READ_BODY and a denial as DENY_BODY, with the
// sensitivity it was decided under and the rules that decided it, and never any of the body's text
// (ADR-0002, ADR-0016). The audit log is append-only, so this is the only write it takes.
func (q *Queries) RecordBodyDecision(ctx context.Context, arg RecordBodyDecisionParams) error {
	_, err := q.db.Exec(ctx, recordBodyDecision,
		arg.AccountID,
		arg.Actor,
		arg.Action,
		arg.MessageID,
		arg.Sensitivity,
		arg.RuleIds,
	)
	return err
}
