// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package setup

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addClient = `-- name: AddClient :exec
INSERT INTO oauth_clients (name, provider, client_id, client_secret, project_id)
VALUES ($1, $2, $3, $4, $5)
`

type AddClientParams struct {
	ClientName   string
	Provider     string
	ClientID     string
	ClientSecret []byte
	ProjectID    pgtype.Text
}

// Stores a new client under its name with its secret sealed to the row its name keys (ADR-0081,
// ADR-0088). The table's keys refuse a name another client holds and a client identifier the
// provider's other client holds (ADR-0106).
func (q *Queries) AddClient(ctx context.Context, arg AddClientParams) error {
	_, err := q.db.Exec(ctx, addClient,
		arg.ClientName,
		arg.Provider,
		arg.ClientID,
		arg.ClientSecret,
		arg.ProjectID,
	)
	return err
}

const clientIdentity = `-- name: ClientIdentity :many
SELECT
    provider,
    client_id
FROM oauth_clients
WHERE name = $1
`

type ClientIdentityRow struct {
	Provider string
	ClientID string
}

// The named client's provider and identifier, which finishing a consent reads in the transaction that
// writes the account, to refuse a client replaced or removed since the attempt started (docs/UI.md
// section 8.12).
func (q *Queries) ClientIdentity(ctx context.Context, clientName string) ([]ClientIdentityRow, error) {
	rows, err := q.db.Query(ctx, clientIdentity, clientName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientIdentityRow
	for rows.Next() {
		var i ClientIdentityRow
		if err := rows.Scan(&i.Provider, &i.ClientID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClient = `-- name: RemoveClient :execrows
DELETE FROM oauth_clients
WHERE name = $1 AND provider = $2
`

type RemoveClientParams struct {
	ClientName string
	Provider   string
}

// Removes the named client. An account that connects through it refuses the delete by its reference,
// so a client in use is never removed (ADR-0106). No row means no client of the provider holds the
// name.
func (q *Queries) RemoveClient(ctx context.Context, arg RemoveClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeClient, arg.ClientName, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceClient = `-- name: ReplaceClient :execrows
UPDATE oauth_clients
SET
    client_id = $1,
    client_secret = $2,
    project_id = $3
WHERE name = $4 AND provider = $5
`

type ReplaceClientParams struct {
	ClientID     string
	ClientSecret []byte
	ProjectID    pgtype.Text
	ClientName   string
	Provider     string
}

// Replaces the named client's identifier, secret and project ID, unconditionally, since the operator's
// write is the newest (ADR-0089). No row means no client of the provider holds the name.
func (q *Queries) ReplaceClient(ctx context.Context, arg ReplaceClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceClient,
		arg.ClientID,
		arg.ClientSecret,
		arg.ProjectID,
		arg.ClientName,
		arg.Provider,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setupClients = `-- name: SetupClients :many
SELECT
    name AS client_name,
    provider,
    client_id,
    project_id
FROM oauth_clients
ORDER BY name
`

type SetupClientsRow struct {
	ClientName string
	Provider   string
	ClientID   string
	ProjectID  pgtype.Text
}

// Every stored OAuth client's name, provider, client identifier and project ID, which the
// installation endpoint lists and client setup checks a name and an identifier against. It reads no
// secret. The role that runs it may read one only for the UI's client-secret part, which reads it
// through its own statement (ADR-0081, ADR-0084, ADR-0106).
func (q *Queries) SetupClients(ctx context.Context) ([]SetupClientsRow, error) {
	rows, err := q.db.Query(ctx, setupClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SetupClientsRow
	for rows.Next() {
		var i SetupClientsRow
		if err := rows.Scan(
			&i.ClientName,
			&i.Provider,
			&i.ClientID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
