// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package clientsetup

import (
	"context"
)

type Querier interface {
	// Stores a new client under its name with its secret sealed to the row its name keys (ADR-0081,
	// ADR-0088). The table's keys refuse a name another client holds and a client identifier the
	// provider's other client holds (ADR-0106).
	AddClient(ctx context.Context, arg AddClientParams) error
	// The named client's provider and identifier, which finishing a consent reads in the transaction that
	// writes the account, to refuse a client replaced or removed since the attempt started (docs/UI.md
	// section 8.12).
	ClientIdentity(ctx context.Context, clientName string) ([]ClientIdentityRow, error)
	// Removes the named client. An account that connects through it refuses the delete by its reference,
	// so a client in use is never removed (ADR-0106). No row means no client of the provider holds the
	// name.
	RemoveClient(ctx context.Context, arg RemoveClientParams) (int64, error)
	// Replaces the named client's identifier, secret and project ID, unconditionally, since the operator's
	// write is the newest (ADR-0089). No row means no client of the provider holds the name.
	ReplaceClient(ctx context.Context, arg ReplaceClientParams) (int64, error)
	// Every stored OAuth client's name, provider, client identifier and project ID, which the
	// installation endpoint lists and client setup checks a name and an identifier against. It reads no
	// secret. The role that runs it may read one only for the UI's client-secret part, which reads it
	// through its own statement (ADR-0081, ADR-0084, ADR-0106).
	SetupClients(ctx context.Context) ([]SetupClientsRow, error)
}

var _ Querier = (*Queries)(nil)
