// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authentication.sql

package authentication

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordAuthentication = `-- name: RecordAuthentication :exec
UPDATE account_state
SET
    last_auth_at = $1,
    last_auth_outcome = $2
WHERE
    account_id = $3
    AND (last_auth_at IS NULL OR last_auth_at < $1)
`

type RecordAuthenticationParams struct {
	AttemptedAt pgtype.Timestamptz
	Outcome     pgtype.Text
	AccountID   string
}

// Records an authentication attempt the account's provider adapter reported, at the end of a
// unit of work, only when the row holds no attempt or an older one, so the latest attempt of
// every deployable that records it wins and an older one changes nothing (ADR-0097, ADR-0016).
func (q *Queries) RecordAuthentication(ctx context.Context, arg RecordAuthenticationParams) error {
	_, err := q.db.Exec(ctx, recordAuthentication, arg.AttemptedAt, arg.Outcome, arg.AccountID)
	return err
}
