// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authentication

import (
	"context"
)

type Querier interface {
	// Records an authentication attempt the account's provider adapter reported, at the end of a
	// unit of work, only when the row holds no attempt or an older one, so the latest attempt of
	// every deployable that records it wins and an older one changes nothing (ADR-0097, ADR-0016).
	RecordAuthentication(ctx context.Context, arg RecordAuthenticationParams) error
}

var _ Querier = (*Queries)(nil)
