// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: failures.sql

package classification

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const failureDetail = `-- name: FailureDetail :one
SELECT
    f.seq,
    f.item_kind,
    f.item_id,
    m.message_id,
    m.from_email,
    m.subject,
    m.sent_at,
    m.labels,
    m.sender_class,
    m.content_flags,
    m.scan_state,
    f.page,
    f.error_class,
    f.attempts,
    f.first_at,
    f.last_at,
    f.disposition,
    f.recovered_by,
    f.error_summary,
    m.class_rule_id,
    m.rule_ids,
    m.scanned_at,
    m.scanner_version
FROM job_run_failures AS f
LEFT JOIN messages AS m
    ON f.account_id = m.account_id AND f.item_id = m.message_id AND f.item_kind IN ('message', 'op')
WHERE f.account_id = $1 AND f.run_id = $2 AND f.seq = $3
`

type FailureDetailParams struct {
	AccountID string
	RunID     string
	Seq       int64
}

type FailureDetailRow struct {
	Seq            int64
	ItemKind       string
	ItemID         string
	MessageID      pgtype.Text
	FromEmail      pgtype.Text
	Subject        pgtype.Text
	SentAt         pgtype.Timestamptz
	Labels         []string
	SenderClass    pgtype.Text
	ContentFlags   []string
	ScanState      pgtype.Text
	Page           pgtype.Int4
	ErrorClass     string
	Attempts       int32
	FirstAt        pgtype.Timestamptz
	LastAt         pgtype.Timestamptz
	Disposition    string
	RecoveredBy    pgtype.Text
	ErrorSummary   pgtype.Text
	ClassRuleID    pgtype.Text
	RuleIds        []string
	ScannedAt      pgtype.Timestamptz
	ScannerVersion pgtype.Int4
}

// One of a run's failures with the error summary as recorded, the failures dataset's provenance for its
// row detail, and its message's sensitivity block, the policy rule that set its class apart from the
// content rules that set its flags, the time it was scanned and the scanner version (docs/UI.md
// sections 7.1, 8.4 and 17.1).
func (q *Queries) FailureDetail(ctx context.Context, arg FailureDetailParams) (FailureDetailRow, error) {
	row := q.db.QueryRow(ctx, failureDetail, arg.AccountID, arg.RunID, arg.Seq)
	var i FailureDetailRow
	err := row.Scan(
		&i.Seq,
		&i.ItemKind,
		&i.ItemID,
		&i.MessageID,
		&i.FromEmail,
		&i.Subject,
		&i.SentAt,
		&i.Labels,
		&i.SenderClass,
		&i.ContentFlags,
		&i.ScanState,
		&i.Page,
		&i.ErrorClass,
		&i.Attempts,
		&i.FirstAt,
		&i.LastAt,
		&i.Disposition,
		&i.RecoveredBy,
		&i.ErrorSummary,
		&i.ClassRuleID,
		&i.RuleIds,
		&i.ScannedAt,
		&i.ScannerVersion,
	)
	return i, err
}

const failureFigures = `-- name: FailureFigures :many
SELECT
    f.disposition,
    count(*) AS failures,
    count(*) FILTER (WHERE m.sender_class = 'restricted') AS restricted,
    count(*) FILTER (WHERE cardinality(m.content_flags) > 0) AS flagged
FROM job_run_failures AS f
LEFT JOIN messages AS m
    ON f.account_id = m.account_id AND f.item_id = m.message_id AND f.item_kind IN ('message', 'op')
WHERE
    f.account_id = $1
    AND f.run_id = $2
    AND ($3::text[] IS NULL OR f.error_class = any($3::text[]))
    AND ($4::text[] IS NULL OR f.error_class != all($4::text[]))
    AND ($5::text[] IS NULL OR f.disposition = any($5::text[]))
    AND ($6::text[] IS NULL OR f.disposition != all($6::text[]))
    AND (
        ($7::citext[] IS NULL AND NOT $8::boolean)
        OR m.from_domain = any($7::citext[])
        OR ($8::boolean AND m.from_domain IS NULL)
    )
    AND ($9::citext[] IS NULL OR m.from_domain IS NULL OR m.from_domain != all($9::citext[]))
    AND (NOT $10::boolean OR m.from_domain IS NOT NULL)
    AND (
        ($11::integer[] IS NULL AND NOT $12::boolean)
        OR f.page = any($11::integer[])
        OR ($12::boolean AND f.page IS NULL)
    )
    AND ($13::integer[] IS NULL OR f.page IS NULL OR f.page != all($13::integer[]))
    AND (NOT $14::boolean OR f.page IS NOT NULL)
GROUP BY f.disposition
ORDER BY f.disposition
`

type FailureFiguresParams struct {
	AccountID      string
	RunID          string
	ErrorClassIn   []string
	ErrorClassOut  []string
	DispositionIn  []string
	DispositionOut []string
	SenderIn       []string
	SenderInNone   bool
	SenderOut      []string
	SenderOutNone  bool
	PageIn         []int32
	PageInNone     bool
	PageOut        []int32
	PageOutNone    bool
}

type FailureFiguresRow struct {
	Disposition string
	Failures    int64
	Restricted  int64
	Flagged     int64
}

// The failures dataset's figures under its filters, one row per disposition with its count and how many
// of those items' messages are restricted or flagged (docs/UI.md sections 8.4 and 17.1). The totals
// are their sums, which the pages count from. The joined message is the item's own, for a message or
// an operation item, and a page item joins none, so it counts as neither restricted nor flagged. A null
// array is no filter. The none flags select or exclude the items with no sender or no page.
func (q *Queries) FailureFigures(ctx context.Context, arg FailureFiguresParams) ([]FailureFiguresRow, error) {
	rows, err := q.db.Query(ctx, failureFigures,
		arg.AccountID,
		arg.RunID,
		arg.ErrorClassIn,
		arg.ErrorClassOut,
		arg.DispositionIn,
		arg.DispositionOut,
		arg.SenderIn,
		arg.SenderInNone,
		arg.SenderOut,
		arg.SenderOutNone,
		arg.PageIn,
		arg.PageInNone,
		arg.PageOut,
		arg.PageOutNone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailureFiguresRow
	for rows.Next() {
		var i FailureFiguresRow
		if err := rows.Scan(
			&i.Disposition,
			&i.Failures,
			&i.Restricted,
			&i.Flagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failureRows = `-- name: FailureRows :many
SELECT
    f.seq,
    f.item_kind,
    f.item_id,
    m.message_id,
    m.from_email,
    m.subject,
    m.sent_at,
    m.labels,
    m.sender_class,
    m.content_flags,
    m.scan_state,
    f.page,
    f.error_class,
    f.attempts,
    f.first_at,
    f.last_at,
    f.disposition,
    f.recovered_by
FROM job_run_failures AS f
LEFT JOIN messages AS m
    ON f.account_id = m.account_id AND f.item_id = m.message_id AND f.item_kind IN ('message', 'op')
WHERE
    f.account_id = $1
    AND f.run_id = $2
    AND ($3::text[] IS NULL OR f.error_class = any($3::text[]))
    AND ($4::text[] IS NULL OR f.error_class != all($4::text[]))
    AND ($5::text[] IS NULL OR f.disposition = any($5::text[]))
    AND ($6::text[] IS NULL OR f.disposition != all($6::text[]))
    AND (
        ($7::citext[] IS NULL AND NOT $8::boolean)
        OR m.from_domain = any($7::citext[])
        OR ($8::boolean AND m.from_domain IS NULL)
    )
    AND ($9::citext[] IS NULL OR m.from_domain IS NULL OR m.from_domain != all($9::citext[]))
    AND (NOT $10::boolean OR m.from_domain IS NOT NULL)
    AND (
        ($11::integer[] IS NULL AND NOT $12::boolean)
        OR f.page = any($11::integer[])
        OR ($12::boolean AND f.page IS NULL)
    )
    AND ($13::integer[] IS NULL OR f.page IS NULL OR f.page != all($13::integer[]))
    AND (NOT $14::boolean OR f.page IS NOT NULL)
ORDER BY
    CASE WHEN $15::text = 'last_at' AND $16::boolean THEN f.last_at END DESC,
    CASE WHEN $15::text = 'last_at' AND NOT $16::boolean THEN f.last_at END ASC,
    CASE WHEN $15::text = 'attempts' AND $16::boolean THEN f.attempts END DESC,
    CASE WHEN $15::text = 'attempts' AND NOT $16::boolean THEN f.attempts END ASC,
    f.run_id ASC,
    f.seq ASC
LIMIT 50 OFFSET $17
`

type FailureRowsParams struct {
	AccountID      string
	RunID          string
	ErrorClassIn   []string
	ErrorClassOut  []string
	DispositionIn  []string
	DispositionOut []string
	SenderIn       []string
	SenderInNone   bool
	SenderOut      []string
	SenderOutNone  bool
	PageIn         []int32
	PageInNone     bool
	PageOut        []int32
	PageOutNone    bool
	SortColumn     string
	Descending     bool
	RowOffset      int32
}

type FailureRowsRow struct {
	Seq          int64
	ItemKind     string
	ItemID       string
	MessageID    pgtype.Text
	FromEmail    pgtype.Text
	Subject      pgtype.Text
	SentAt       pgtype.Timestamptz
	Labels       []string
	SenderClass  pgtype.Text
	ContentFlags []string
	ScanState    pgtype.Text
	Page         pgtype.Int4
	ErrorClass   string
	Attempts     int32
	FirstAt      pgtype.Timestamptz
	LastAt       pgtype.Timestamptz
	Disposition  string
	RecoveredBy  pgtype.Text
}

// One page of a run's failures, fifty rows, under the same filters (docs/UI.md section 8.4). Each row
// carries the message-row fields of the item's message, null for a page item or a message the index no
// longer holds. sort_column names last_at or attempts, in either direction, and the failure's identity
// ends the sort.
func (q *Queries) FailureRows(ctx context.Context, arg FailureRowsParams) ([]FailureRowsRow, error) {
	rows, err := q.db.Query(ctx, failureRows,
		arg.AccountID,
		arg.RunID,
		arg.ErrorClassIn,
		arg.ErrorClassOut,
		arg.DispositionIn,
		arg.DispositionOut,
		arg.SenderIn,
		arg.SenderInNone,
		arg.SenderOut,
		arg.SenderOutNone,
		arg.PageIn,
		arg.PageInNone,
		arg.PageOut,
		arg.PageOutNone,
		arg.SortColumn,
		arg.Descending,
		arg.RowOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailureRowsRow
	for rows.Next() {
		var i FailureRowsRow
		if err := rows.Scan(
			&i.Seq,
			&i.ItemKind,
			&i.ItemID,
			&i.MessageID,
			&i.FromEmail,
			&i.Subject,
			&i.SentAt,
			&i.Labels,
			&i.SenderClass,
			&i.ContentFlags,
			&i.ScanState,
			&i.Page,
			&i.ErrorClass,
			&i.Attempts,
			&i.FirstAt,
			&i.LastAt,
			&i.Disposition,
			&i.RecoveredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failuresByDisposition = `-- name: FailuresByDisposition :many
SELECT
    f.disposition,
    count(*) AS failures,
    count(*) FILTER (WHERE m.sender_class = 'restricted') AS restricted,
    count(*) FILTER (WHERE cardinality(m.content_flags) > 0) AS flagged
FROM job_run_failures AS f
LEFT JOIN messages AS m
    ON f.account_id = m.account_id AND f.item_id = m.message_id AND f.item_kind IN ('message', 'op')
WHERE
    f.account_id = $1
    AND f.run_id = $2
    AND ($3::text[] IS NULL OR f.error_class = any($3::text[]))
    AND ($4::text[] IS NULL OR f.error_class != all($4::text[]))
    AND ($5::text[] IS NULL OR f.disposition = any($5::text[]))
    AND ($6::text[] IS NULL OR f.disposition != all($6::text[]))
    AND (
        ($7::citext[] IS NULL AND NOT $8::boolean)
        OR m.from_domain = any($7::citext[])
        OR ($8::boolean AND m.from_domain IS NULL)
    )
    AND ($9::citext[] IS NULL OR m.from_domain IS NULL OR m.from_domain != all($9::citext[]))
    AND (NOT $10::boolean OR m.from_domain IS NOT NULL)
    AND (
        ($11::integer[] IS NULL AND NOT $12::boolean)
        OR f.page = any($11::integer[])
        OR ($12::boolean AND f.page IS NULL)
    )
    AND ($13::integer[] IS NULL OR f.page IS NULL OR f.page != all($13::integer[]))
    AND (NOT $14::boolean OR f.page IS NOT NULL)
GROUP BY f.disposition
ORDER BY failures DESC, f.disposition ASC NULLS LAST
`

type FailuresByDispositionParams struct {
	AccountID      string
	RunID          string
	ErrorClassIn   []string
	ErrorClassOut  []string
	DispositionIn  []string
	DispositionOut []string
	SenderIn       []string
	SenderInNone   bool
	SenderOut      []string
	SenderOutNone  bool
	PageIn         []int32
	PageInNone     bool
	PageOut        []int32
	PageOutNone    bool
}

type FailuresByDispositionRow struct {
	Disposition string
	Failures    int64
	Restricted  int64
	Flagged     int64
}

// Every group of a run's failures by disposition, as FailuresByErrorClass.
func (q *Queries) FailuresByDisposition(ctx context.Context, arg FailuresByDispositionParams) ([]FailuresByDispositionRow, error) {
	rows, err := q.db.Query(ctx, failuresByDisposition,
		arg.AccountID,
		arg.RunID,
		arg.ErrorClassIn,
		arg.ErrorClassOut,
		arg.DispositionIn,
		arg.DispositionOut,
		arg.SenderIn,
		arg.SenderInNone,
		arg.SenderOut,
		arg.SenderOutNone,
		arg.PageIn,
		arg.PageInNone,
		arg.PageOut,
		arg.PageOutNone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailuresByDispositionRow
	for rows.Next() {
		var i FailuresByDispositionRow
		if err := rows.Scan(
			&i.Disposition,
			&i.Failures,
			&i.Restricted,
			&i.Flagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failuresByErrorClass = `-- name: FailuresByErrorClass :many
SELECT
    f.error_class,
    count(*) AS failures,
    count(*) FILTER (WHERE m.sender_class = 'restricted') AS restricted,
    count(*) FILTER (WHERE cardinality(m.content_flags) > 0) AS flagged
FROM job_run_failures AS f
LEFT JOIN messages AS m
    ON f.account_id = m.account_id AND f.item_id = m.message_id AND f.item_kind IN ('message', 'op')
WHERE
    f.account_id = $1
    AND f.run_id = $2
    AND ($3::text[] IS NULL OR f.error_class = any($3::text[]))
    AND ($4::text[] IS NULL OR f.error_class != all($4::text[]))
    AND ($5::text[] IS NULL OR f.disposition = any($5::text[]))
    AND ($6::text[] IS NULL OR f.disposition != all($6::text[]))
    AND (
        ($7::citext[] IS NULL AND NOT $8::boolean)
        OR m.from_domain = any($7::citext[])
        OR ($8::boolean AND m.from_domain IS NULL)
    )
    AND ($9::citext[] IS NULL OR m.from_domain IS NULL OR m.from_domain != all($9::citext[]))
    AND (NOT $10::boolean OR m.from_domain IS NOT NULL)
    AND (
        ($11::integer[] IS NULL AND NOT $12::boolean)
        OR f.page = any($11::integer[])
        OR ($12::boolean AND f.page IS NULL)
    )
    AND ($13::integer[] IS NULL OR f.page IS NULL OR f.page != all($13::integer[]))
    AND (NOT $14::boolean OR f.page IS NOT NULL)
GROUP BY f.error_class
ORDER BY failures DESC, f.error_class ASC NULLS LAST
`

type FailuresByErrorClassParams struct {
	AccountID      string
	RunID          string
	ErrorClassIn   []string
	ErrorClassOut  []string
	DispositionIn  []string
	DispositionOut []string
	SenderIn       []string
	SenderInNone   bool
	SenderOut      []string
	SenderOutNone  bool
	PageIn         []int32
	PageInNone     bool
	PageOut        []int32
	PageOutNone    bool
}

type FailuresByErrorClassRow struct {
	ErrorClass string
	Failures   int64
	Restricted int64
	Flagged    int64
}

// Every group of a run's failures by error class, under the same filters, ordered by count and then
// by the group's key, the order the bars draw (docs/UI.md section 17.1).
func (q *Queries) FailuresByErrorClass(ctx context.Context, arg FailuresByErrorClassParams) ([]FailuresByErrorClassRow, error) {
	rows, err := q.db.Query(ctx, failuresByErrorClass,
		arg.AccountID,
		arg.RunID,
		arg.ErrorClassIn,
		arg.ErrorClassOut,
		arg.DispositionIn,
		arg.DispositionOut,
		arg.SenderIn,
		arg.SenderInNone,
		arg.SenderOut,
		arg.SenderOutNone,
		arg.PageIn,
		arg.PageInNone,
		arg.PageOut,
		arg.PageOutNone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailuresByErrorClassRow
	for rows.Next() {
		var i FailuresByErrorClassRow
		if err := rows.Scan(
			&i.ErrorClass,
			&i.Failures,
			&i.Restricted,
			&i.Flagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failuresByPage = `-- name: FailuresByPage :many
SELECT
    f.page,
    count(*) AS failures,
    count(*) FILTER (WHERE m.sender_class = 'restricted') AS restricted,
    count(*) FILTER (WHERE cardinality(m.content_flags) > 0) AS flagged
FROM job_run_failures AS f
LEFT JOIN messages AS m
    ON f.account_id = m.account_id AND f.item_id = m.message_id AND f.item_kind IN ('message', 'op')
WHERE
    f.account_id = $1
    AND f.run_id = $2
    AND ($3::text[] IS NULL OR f.error_class = any($3::text[]))
    AND ($4::text[] IS NULL OR f.error_class != all($4::text[]))
    AND ($5::text[] IS NULL OR f.disposition = any($5::text[]))
    AND ($6::text[] IS NULL OR f.disposition != all($6::text[]))
    AND (
        ($7::citext[] IS NULL AND NOT $8::boolean)
        OR m.from_domain = any($7::citext[])
        OR ($8::boolean AND m.from_domain IS NULL)
    )
    AND ($9::citext[] IS NULL OR m.from_domain IS NULL OR m.from_domain != all($9::citext[]))
    AND (NOT $10::boolean OR m.from_domain IS NOT NULL)
    AND (
        ($11::integer[] IS NULL AND NOT $12::boolean)
        OR f.page = any($11::integer[])
        OR ($12::boolean AND f.page IS NULL)
    )
    AND ($13::integer[] IS NULL OR f.page IS NULL OR f.page != all($13::integer[]))
    AND (NOT $14::boolean OR f.page IS NOT NULL)
GROUP BY f.page
ORDER BY failures DESC, f.page ASC NULLS LAST
`

type FailuresByPageParams struct {
	AccountID      string
	RunID          string
	ErrorClassIn   []string
	ErrorClassOut  []string
	DispositionIn  []string
	DispositionOut []string
	SenderIn       []string
	SenderInNone   bool
	SenderOut      []string
	SenderOutNone  bool
	PageIn         []int32
	PageInNone     bool
	PageOut        []int32
	PageOutNone    bool
}

type FailuresByPageRow struct {
	Page       pgtype.Int4
	Failures   int64
	Restricted int64
	Flagged    int64
}

// Every group of a run's failures by the page each item was processed on, as
// FailuresByErrorClass, with the items that have none in a null group.
func (q *Queries) FailuresByPage(ctx context.Context, arg FailuresByPageParams) ([]FailuresByPageRow, error) {
	rows, err := q.db.Query(ctx, failuresByPage,
		arg.AccountID,
		arg.RunID,
		arg.ErrorClassIn,
		arg.ErrorClassOut,
		arg.DispositionIn,
		arg.DispositionOut,
		arg.SenderIn,
		arg.SenderInNone,
		arg.SenderOut,
		arg.SenderOutNone,
		arg.PageIn,
		arg.PageInNone,
		arg.PageOut,
		arg.PageOutNone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailuresByPageRow
	for rows.Next() {
		var i FailuresByPageRow
		if err := rows.Scan(
			&i.Page,
			&i.Failures,
			&i.Restricted,
			&i.Flagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failuresBySender = `-- name: FailuresBySender :many
SELECT
    coalesce(lower(m.from_domain), '')::text AS from_domain,
    (m.from_domain IS NULL)::boolean AS no_domain,
    count(*) AS failures,
    count(*) FILTER (WHERE m.sender_class = 'restricted') AS restricted,
    count(*) FILTER (WHERE cardinality(m.content_flags) > 0) AS flagged
FROM job_run_failures AS f
LEFT JOIN messages AS m
    ON f.account_id = m.account_id AND f.item_id = m.message_id AND f.item_kind IN ('message', 'op')
WHERE
    f.account_id = $1
    AND f.run_id = $2
    AND ($3::text[] IS NULL OR f.error_class = any($3::text[]))
    AND ($4::text[] IS NULL OR f.error_class != all($4::text[]))
    AND ($5::text[] IS NULL OR f.disposition = any($5::text[]))
    AND ($6::text[] IS NULL OR f.disposition != all($6::text[]))
    AND (
        ($7::citext[] IS NULL AND NOT $8::boolean)
        OR m.from_domain = any($7::citext[])
        OR ($8::boolean AND m.from_domain IS NULL)
    )
    AND ($9::citext[] IS NULL OR m.from_domain IS NULL OR m.from_domain != all($9::citext[]))
    AND (NOT $10::boolean OR m.from_domain IS NOT NULL)
    AND (
        ($11::integer[] IS NULL AND NOT $12::boolean)
        OR f.page = any($11::integer[])
        OR ($12::boolean AND f.page IS NULL)
    )
    AND ($13::integer[] IS NULL OR f.page IS NULL OR f.page != all($13::integer[]))
    AND (NOT $14::boolean OR f.page IS NOT NULL)
GROUP BY m.from_domain
ORDER BY failures DESC, m.from_domain ASC NULLS LAST
`

type FailuresBySenderParams struct {
	AccountID      string
	RunID          string
	ErrorClassIn   []string
	ErrorClassOut  []string
	DispositionIn  []string
	DispositionOut []string
	SenderIn       []string
	SenderInNone   bool
	SenderOut      []string
	SenderOutNone  bool
	PageIn         []int32
	PageInNone     bool
	PageOut        []int32
	PageOutNone    bool
}

type FailuresBySenderRow struct {
	FromDomain string
	NoDomain   bool
	Failures   int64
	Restricted int64
	Flagged    int64
}

// Every group of a run's failures by the domain of the item's message, as FailuresByErrorClass,
// with the items that have none in a null group, which no_domain marks. The domain is
// case-insensitive, so the spellings of one domain are one group, and its key is the domain lowered by
// the same function the case-insensitive comparison uses, so the key names the group whatever the
// spellings and the database's locale. The sender filter compares case-insensitively and matches
// every spelling. A stored empty domain is a group of its own, keyed empty, apart from the null group.
func (q *Queries) FailuresBySender(ctx context.Context, arg FailuresBySenderParams) ([]FailuresBySenderRow, error) {
	rows, err := q.db.Query(ctx, failuresBySender,
		arg.AccountID,
		arg.RunID,
		arg.ErrorClassIn,
		arg.ErrorClassOut,
		arg.DispositionIn,
		arg.DispositionOut,
		arg.SenderIn,
		arg.SenderInNone,
		arg.SenderOut,
		arg.SenderOutNone,
		arg.PageIn,
		arg.PageInNone,
		arg.PageOut,
		arg.PageOutNone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FailuresBySenderRow
	for rows.Next() {
		var i FailuresBySenderRow
		if err := rows.Scan(
			&i.FromDomain,
			&i.NoDomain,
			&i.Failures,
			&i.Restricted,
			&i.Flagged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
