// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package runclassification

import (
	"context"
)

type Querier interface {
	// One of a run's failures with the error summary as recorded, the failures dataset's provenance for its
	// row detail, and its message's sensitivity block, the policy rule that set its class apart from the
	// content rules that set its flags, the time it was scanned and the scanner version (docs/UI.md
	// sections 7.1, 8.4 and 17.1).
	FailureDetail(ctx context.Context, arg FailureDetailParams) (FailureDetailRow, error)
	// The failures dataset's figures under its filters, one row per disposition with its count and how many
	// of those items' messages are restricted or flagged (docs/UI.md sections 8.4 and 17.1). The totals
	// are their sums, which the pages count from. The joined message is the item's own, for a message or
	// an operation item, and a page item joins none, so it counts as neither restricted nor flagged. A null
	// array is no filter. The none flags select or exclude the items with no sender or no page.
	FailureFigures(ctx context.Context, arg FailureFiguresParams) ([]FailureFiguresRow, error)
	// One page of a run's failures, fifty rows, under the same filters (docs/UI.md section 8.4). Each row
	// carries the message-row fields of the item's message, null for a page item or a message the index no
	// longer holds. sort_column names last_at or attempts, in either direction, and the failure's identity
	// ends the sort.
	FailureRows(ctx context.Context, arg FailureRowsParams) ([]FailureRowsRow, error)
	// Every group of a run's failures by disposition, as FailuresByErrorClass.
	FailuresByDisposition(ctx context.Context, arg FailuresByDispositionParams) ([]FailuresByDispositionRow, error)
	// Every group of a run's failures by error class, under the same filters, ordered by count and then
	// by the group's key, the order the bars draw (docs/UI.md section 17.1).
	FailuresByErrorClass(ctx context.Context, arg FailuresByErrorClassParams) ([]FailuresByErrorClassRow, error)
	// Every group of a run's failures by the page each item was processed on, as
	// FailuresByErrorClass, with the items that have none in a null group.
	FailuresByPage(ctx context.Context, arg FailuresByPageParams) ([]FailuresByPageRow, error)
	// Every group of a run's failures by the domain of the item's message, as FailuresByErrorClass,
	// with the items that have none in a null group, which no_domain marks. Every writer stores a domain in
	// the one form the domain normalizer gives, so each domain has one spelling and its key is that
	// spelling, and the sender filter is given its values in the same form (ADR-0016). A stored empty
	// domain is a group of its own, keyed empty, apart from the null group.
	FailuresBySender(ctx context.Context, arg FailuresBySenderParams) ([]FailuresBySenderRow, error)
}

var _ Querier = (*Queries)(nil)
