// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package counting

import (
	"context"
)

type Querier interface {
	AddSenderMessages(ctx context.Context, arg AddSenderMessagesParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
