// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: senders.sql

package counting

import (
	"context"
)

const addSenderMessages = `-- name: AddSenderMessages :execrows
UPDATE fixture_senders
SET message_count = message_count + $1
WHERE account_id = $2 AND domain = $3
`

type AddSenderMessagesParams struct {
	Added     int64
	AccountID string
	Domain    string
}

func (q *Queries) AddSenderMessages(ctx context.Context, arg AddSenderMessagesParams) (int64, error) {
	result, err := q.db.Exec(ctx, addSenderMessages, arg.Added, arg.AccountID, arg.Domain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
