// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package record

import (
	"context"
)

type Querier interface {
	// Records that a running run ended, succeeded or failed, with its last error. A run that is no longer
	// running is left as it is, so a run a later one found stopped keeps the state that run gave it.
	EndRun(ctx context.Context, arg EndRunParams) error
	// The account's latest run of one workload and pass, whatever its state, which a workload reads to
	// decide whether it resumes that run (ADR-0017, ADR-0022).
	LatestRun(ctx context.Context, arg LatestRunParams) (LatestRunRow, error)
	// Adds one event to a run's timeline. A progress event carries the checkpoint page. The detail is
	// provider or scanner text, never a body (ADR-0022).
	RecordEvent(ctx context.Context, arg RecordEventParams) error
	// Records one item a run failed on, with its error class, how many attempts it took, when the first
	// and last were, and what became of it (ADR-0022).
	RecordFailure(ctx context.Context, arg RecordFailureParams) error
	// Records a running run's checkpoint and counters, in the transaction that made the work they count
	// durable, and its heartbeat.
	RecordProgress(ctx context.Context, arg RecordProgressParams) error
	// Records a run as it starts, with the checkpoint and counters it starts from and the run it resumes,
	// if any (ADR-0022).
	StartRun(ctx context.Context, arg StartRunParams) error
}

var _ Querier = (*Queries)(nil)
