// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record.sql

package record

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const endRun = `-- name: EndRun :exec
UPDATE job_runs
SET state = $1, finished_at = now(), heartbeat_at = now(), last_error = $2
WHERE account_id = $3 AND run_id = $4 AND state = 'running'
`

type EndRunParams struct {
	State     string
	LastError pgtype.Text
	AccountID string
	RunID     string
}

// Records that a running run ended, succeeded or failed, with its last error. A run that is no longer
// running is left as it is, so a run a later one found stopped keeps the state that run gave it.
func (q *Queries) EndRun(ctx context.Context, arg EndRunParams) error {
	_, err := q.db.Exec(ctx, endRun,
		arg.State,
		arg.LastError,
		arg.AccountID,
		arg.RunID,
	)
	return err
}

const latestRun = `-- name: LatestRun :one
SELECT
    r.run_id,
    r.state,
    r.checkpoint,
    r.counters
FROM job_runs AS r
WHERE r.account_id = $1 AND r.workload = $2 AND r.pass = $3
ORDER BY r.started_at DESC, r.run_id DESC
LIMIT 1
`

type LatestRunParams struct {
	AccountID string
	Workload  string
	Pass      pgtype.Text
}

type LatestRunRow struct {
	RunID      string
	State      string
	Checkpoint []byte
	Counters   []byte
}

// The account's latest run of one workload and pass, whatever its state, which a workload reads to
// decide whether it resumes that run (ADR-0017, ADR-0022).
func (q *Queries) LatestRun(ctx context.Context, arg LatestRunParams) (LatestRunRow, error) {
	row := q.db.QueryRow(ctx, latestRun, arg.AccountID, arg.Workload, arg.Pass)
	var i LatestRunRow
	err := row.Scan(
		&i.RunID,
		&i.State,
		&i.Checkpoint,
		&i.Counters,
	)
	return i, err
}

const recordEvent = `-- name: RecordEvent :exec
INSERT INTO job_run_events (account_id, run_id, kind, page, detail)
VALUES ($1, $2, $3, $4, $5)
`

type RecordEventParams struct {
	AccountID string
	RunID     string
	Kind      string
	Page      pgtype.Int4
	Detail    pgtype.Text
}

// Adds one event to a run's timeline. A progress event carries the checkpoint page. The detail is
// provider or scanner text, never a body (ADR-0022).
func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) error {
	_, err := q.db.Exec(ctx, recordEvent,
		arg.AccountID,
		arg.RunID,
		arg.Kind,
		arg.Page,
		arg.Detail,
	)
	return err
}

const recordFailure = `-- name: RecordFailure :exec
INSERT INTO job_run_failures (
    account_id,
    run_id,
    item_kind,
    item_id,
    page,
    error_class,
    error_summary,
    attempts,
    first_at,
    last_at,
    disposition
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type RecordFailureParams struct {
	AccountID    string
	RunID        string
	ItemKind     string
	ItemID       string
	Page         pgtype.Int4
	ErrorClass   string
	ErrorSummary pgtype.Text
	Attempts     int32
	FirstAt      pgtype.Timestamptz
	LastAt       pgtype.Timestamptz
	Disposition  string
}

// Records one item a run failed on, with its error class, how many attempts it took, when the first
// and last were, and what became of it (ADR-0022).
func (q *Queries) RecordFailure(ctx context.Context, arg RecordFailureParams) error {
	_, err := q.db.Exec(ctx, recordFailure,
		arg.AccountID,
		arg.RunID,
		arg.ItemKind,
		arg.ItemID,
		arg.Page,
		arg.ErrorClass,
		arg.ErrorSummary,
		arg.Attempts,
		arg.FirstAt,
		arg.LastAt,
		arg.Disposition,
	)
	return err
}

const recordProgress = `-- name: RecordProgress :exec
UPDATE job_runs
SET checkpoint = $1, counters = $2, heartbeat_at = now()
WHERE account_id = $3 AND run_id = $4
`

type RecordProgressParams struct {
	Checkpoint []byte
	Counters   []byte
	AccountID  string
	RunID      string
}

// Records a running run's checkpoint and counters, in the transaction that made the work they count
// durable, and its heartbeat.
func (q *Queries) RecordProgress(ctx context.Context, arg RecordProgressParams) error {
	_, err := q.db.Exec(ctx, recordProgress,
		arg.Checkpoint,
		arg.Counters,
		arg.AccountID,
		arg.RunID,
	)
	return err
}

const startRun = `-- name: StartRun :exec
INSERT INTO job_runs (
    account_id, run_id, workload, pass, state, resumed_from, started_at, heartbeat_at, checkpoint, counters
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'running',
    $5,
    now(),
    now(),
    $6,
    $7
)
`

type StartRunParams struct {
	AccountID   string
	RunID       string
	Workload    string
	Pass        pgtype.Text
	ResumedFrom pgtype.Text
	Checkpoint  []byte
	Counters    []byte
}

// Records a run as it starts, with the checkpoint and counters it starts from and the run it resumes,
// if any (ADR-0022).
func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) error {
	_, err := q.db.Exec(ctx, startRun,
		arg.AccountID,
		arg.RunID,
		arg.Workload,
		arg.Pass,
		arg.ResumedFrom,
		arg.Checkpoint,
		arg.Counters,
	)
	return err
}
