package check_test

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// generatedHeader starts every file sqlc writes.
const generatedHeader = "// Code generated by sqlc. DO NOT EDIT."

// declaredTypes returns the names of the types a Go source file declares.
func declaredTypes(t *testing.T, name string, src []byte) []string {
	t.Helper()
	file, err := parser.ParseFile(token.NewFileSet(), name, src, parser.SkipObjectResolution)
	if err != nil {
		t.Fatal(err)
	}
	var out []string
	for _, decl := range file.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.TYPE {
			for _, spec := range gen.Specs {
				if ts, ok := spec.(*ast.TypeSpec); ok {
					out = append(out, ts.Name.Name)
				}
			}
		}
	}
	return out
}

// declaredModelTypes is the declares-no-types assertion (ADR-0066). sqlc writes table structs and enum
// types into models.go, and no setting stops it reusing a table's struct for a statement that selects
// every column of that table in order. A type there would be shared across statements, which ADR-0047
// forbids.
func declaredModelTypes(t *testing.T, subs []subsection) []string {
	t.Helper()
	var out []string
	for _, s := range subs {
		// Without db.go nothing was generated, and a missing models.go would prove nothing.
		if _, err := os.Stat(filepath.Join(s.dir, "db.go")); err != nil {
			out = append(out, fmt.Sprintf("%s: no generated db.go. Run sqlc generate", s.dir))
			continue
		}
		models := filepath.Join(s.dir, "models.go")
		src, err := os.ReadFile(models)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		} else if err != nil {
			t.Fatal(err)
		}
		if types := declaredTypes(t, models, src); len(types) > 0 {
			out = append(out, fmt.Sprintf("%s declares %v. Select fewer columns or alias one, so the statement gets its own result type", models, types))
		}
	}
	return out
}

func TestGeneratedModelsDeclareNoTypes(t *testing.T) {
	requireNoProblems(t, declaredModelTypes(t, realLibrary.subsections(t)))
}

// TestUngeneratedSubsectionReported shows the assertion refusing a subsection sqlc never generated,
// where a missing models.go would otherwise pass it.
func TestUngeneratedSubsectionReported(t *testing.T) {
	subs, _ := layoutLibrary.layout(t)
	requireProblems(t, declaredModelTypes(t, subs), []string{
		"testdata/layout/ungenerated: no generated db.go. Run sqlc generate",
	})
}

func TestDeclaredModelTypesReported(t *testing.T) {
	requireProblems(t, declaredModelTypes(t, testLibrary.subsections(t)), []string{
		"testdata/reuse/models.go declares [FixtureSender]. Select fewer columns or alias one, so the statement gets its own result type",
	})
}

// staleGeneratedFiles reports a generated file sqlc would no longer write, such as the accessors of a
// deleted statement file or of a subsection removed from sqlc.yaml. Regenerating does not delete such
// files and sqlc diff does not report them, so without this check they would keep compiling.
func staleGeneratedFiles(t *testing.T, lib library) []string {
	t.Helper()
	subs := lib.subsections(t)
	var out []string
	err := walkSkippingTestdata(lib.dir, func(path string, d fs.DirEntry) error {
		if d.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}
		src, err := os.ReadFile(path)
		if err != nil || !bytes.HasPrefix(src, []byte(generatedHeader)) {
			return err
		}
		dir, name := filepath.Split(path)
		inSubsection := slices.ContainsFunc(subs, func(s subsection) bool { return sameFile(t, s.dir, dir) })
		statement, isStatement := strings.CutSuffix(name, ".go")
		_, statementErr := os.Stat(filepath.Join(dir, statement))
		switch {
		case !inSubsection:
			out = append(out, fmt.Sprintf("%s is generated but its directory is no subsection in sqlc.yaml", path))
		case slices.Contains([]string{"db.go", "models.go", "querier.go"}, name):
		case isStatement && strings.HasSuffix(statement, ".sql") && statementErr == nil:
		default:
			out = append(out, fmt.Sprintf("%s is generated from a statement file that no longer exists", path))
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func TestNoStaleGeneratedFiles(t *testing.T) {
	requireNoProblems(t, staleGeneratedFiles(t, realLibrary))
}

func TestStaleGeneratedFilesReported(t *testing.T) {
	requireProblems(t, staleGeneratedFiles(t, testLibrary), []string{
		"testdata/listing/removed.sql.go is generated from a statement file that no longer exists",
	})
}
