---
# yamllint disable rule:line-length
name: chart

on:
  pull_request:
    paths:
    - .github/workflows/chart.yaml
    - mise.lock
    - mise.toml
    - packaging/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - name: Setup repository and tools
      uses: ppat/homelab-ops-actions/actions/setup-repository-tools@2045fb6e6cb00ab099280625b6989cf62ccc1b77 # v2.7.0
      with:
        current_git_ref: ${{ github.head_ref || github.ref }}
        current_repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}

    # --strict fails on warnings as well as errors.
    - name: Lint the chart
      shell: bash
      working-directory: ./current
      run: mise exec -- helm lint --strict packaging/chart
