---
# yamllint disable rule:line-length
name: dockerfiles

# hadolint over every file named Dockerfile, failing on warnings. The images workflow builds them.
on:
  pull_request:
    paths:
    - .github/workflows/dockerfiles.yaml
    - '**/Dockerfile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  hadolint:
    uses: ppat/github-workflows/.github/workflows/lint-hadolint.yaml@367017389c9ea0a8cb3acedb93382fde96dfe599 # v8.2.0
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ALL
      failure_threshold: warning
